### ISSUE TITLE
forUserWithNewMessages not working with null values in participant table

### ISSUE THREAD

**Issue by bakerstreetsystems** [cmgmyr/laravel-messenger#10]
I like this package! Great work! I did notice one thing that didn't quite work for me, and that is when I create a new thread, the forUserWithNewMessages function doesn't work if I compare the 'threads.updated_at' to 'participants.last_read' with a null value.

You might think about changing this:

public function scopeForUserWithNewMessages($query, $userId)
    {
        return $query->join('participants', 'threads.id', '=', 'participants.thread_id')
            ->where('participants.user_id', $userId)
            ->where('participants.deleted_at', null)
            ->where('threads.updated_at', '>', $this->getConnection()->raw('participants.last_read'))
            ->select('threads.*')
            ->latest('updated_at')
            ->get();
    }

To this:

public function scopeForUserWithNewMessages($query, $userId)
    {
        return $query->join('participants', 'threads.id', '=', 'participants.thread_id')
            ->where('participants.user_id', $userId)
            ->where('participants.deleted_at', null)
            ->where(function($query) {
                  $query->where('threads.updated_at', '>', 'participants.last_read')
                    ->orWhereNull('participants.last_read');
                })
            //->where('threads.updated_at', '>', $this->getConnection()->raw('participants.last_read'))
            ->select('threads.*')
            ->latest('updated_at')
            ->get();
    }

... or is there something else I'm missing?

Thanks for a great plugin.

**Comment by cmgmyr** [comment]
thank you for this @bakerstreetsystems, I'll have this and a small tweak pushed up soon. Glad you like the package!
