### ISSUE TITLE
demo?

### ISSUE THREAD

**Issue by VickG** [cmgmyr/laravel-messenger#101]
Where can I find a demo of this application?

**Comment by RokSiEu** [comment]
You can find it here
https://github.com/cmgmyr/laravel-messenger-pusher-demo 

But keep in mind that it is not updated, you need to add some security to it
More here
https://github.com/cmgmyr/laravel-messenger/issues/43

**Comment by cmgmyr** [comment]
There is no live demo at the moment, just the repo mentioned above. There are example files included with this package so you can easily put together a working app in a few minutes.
