### ISSUE TITLE
$this->creator()->user not working for me.

### ISSUE THREAD

**Issue by JoanVt** [cmgmyr/laravel-messenger#103]
Well, I had my user's table created already with another index name (id instead user_id)

I don't know if that's the problem (I don't think os) but $this->creator() method of Thread is not working calling the "user" method after the query.

I "fixed" it doing like this:
return $this->messages()->with('user')->oldest()->first();
Instead of
return $this->messages()->oldest()->first()->user;

Just saying :>

**Comment by cmgmyr** [comment]
hmm, what version of Laravel are you using? Seems to be working ok for me

**Comment by JoanVt** [comment]
5.1

**Comment by cmgmyr** [comment]
hmm, I'm in a fresh install of 5.1 (`v5.1.28`) I'm getting the expected result from: `return $this->messages()->oldest()->first()->user;`. Do you have your code available somewhere online that I could check out?

**Comment by johannesschobel** [comment]
Hey,
found this issue while having the same problem here #229 . The problem might be, that the thread is empty (i.e., it has no message).
BTW i am also running on L5.1.46 (latest)
