### ISSUE TITLE
getting "Trying to get property of non-object" 

### ISSUE THREAD

**Issue by seancork** [cmgmyr/laravel-messenger#104]
getting 
ErrorException in Thread.php line 87:
Trying to get property of non-object because of 
 {!! $thread->creator()->name !!}

which is connected to this

public function creator()
    {
        return $this->messages()->oldest()->first()->user;
    }

any ideas why this is happening?

**Comment by JoanVt** [comment]
Read my last comment.

https://github.com/cmgmyr/laravel-messenger/issues/103
