### ISSUE TITLE
Message Threads

### ISSUE THREAD

**Issue by RudolfFussek** [cmgmyr/laravel-messenger#105]
Hey! I have a bug... When I send a Message to ONE User. all Users can see and read this thread, why? Can anyone help me?

**Comment by JoanVt** [comment]
Hey! You must get the user Thread like this:


Getting all user Threads:
$thread = Thread::forUser(Auth::user()->id)->latest('updated_at')->get();

Then, check participation:
$participant= Participant::where('thread_id',$thread->id)->where('user_id',Auth::user()->id)->first();

**Comment by RudolfFussek** [comment]
I add in the MessagesController.php show_message right? Must I edit the routes MessagesController@show in MessagesController@show_message?

**Comment by JoanVt** [comment]
Oh, well, sorry. I was using my own methods.

Use show() or show_message(), doesn't matter.

**Comment by Gummibeer** [comment]
I've did it with the explicit Model binding and just check the participation of the current user:

**routes.php**
```
Route::group(['prefix' => 'chat'], function () {
        Route::get('/', 'ChatController@getIndex');
        Route::get('/create', 'ChatController@getCreate');
        Route::post('/create', 'ChatController@postCreate');
        Route::get('/{chat_thread}', 'ChatController@getShow');
        Route::post('/{chat_thread}', 'ChatController@postReply');
});
```

**RouteServiceProvider**
```
$router->model('chat_thread', ChatThread::class);
```

**MessageController**
```
public function getShow(Thread $thread)
{
    if(!$thread->hasParticipant(\Auth::id())) {
        abort(404);
    }

    $thread->markAsRead(\Auth::id());

    return view('app.chat.index')->with([
        'display_thread' => $thread,
    ]);
}
```

**Comment by RudolfFussek** [comment]
@JoanVt: Okay. Now I have this:

[code]
public function show($id)
    {
        try {
            $thread = Thread::findOrFail($id);
        } catch (ModelNotFoundException $e) {
            Session::flash('error_message', 'The thread with ID: ' . $id . ' was not found.');

            return redirect('user/messages');
        }

        // show current user in list if not a current participant
        // $users = User::whereNotIn('id', $thread->participantsUserIds())->get();

        // don't show the current user in list
        $userId = Auth::user()->id;
        $users = User::whereNotIn('id', $thread->participantsUserIds($userId))->get();

        $thread->markAsRead($userId);

        return view('messenger.show', compact('thread', 'users'));
    }
[/code]

Where I can add 
$participant= Participant::where('thread_id',$thread->id)->where('user_id',Auth::user()->id)->first();


Sorry but just I´m very confused..... XD

**Comment by RudolfFussek** [comment]
Oh no!!!! I wanted not close it :(

**Comment by Gummibeer** [comment]
I'm also ... what is your problem and what are you trying to get working?
Do you want to list all Threads the current User is participating? Or do you want to display a single Thread, but only if the current user is a participant of this Thread, or what is your goal?

**Comment by RudolfFussek** [comment]
When I go to yourwebsite.com/messages/ID than I can see the Messages, but I'm not participant from this thread....

**Comment by Gummibeer** [comment]
Ok, than thsi will solve your problem:

```
if(!$thread->hasParticipant(\Auth::id())) {
    abort(404);
}
```

just add it in your show Method of your controller. You can do everything you want inside the if what you want to do if anyone want to see a message thread where he isn't a participant.

**Comment by JoanVt** [comment]
My routes: 
```php
Route::get('mis-mensajes', ['as' => 'messages', 'uses' => 'ProfileController@my_messages']);
			Route::get('nuevo-mensaje', ['as' => 'messages.create', 'uses' => 'ProfileController@new_message']);
			Route::post('enviar-message', ['as' => 'messages.store', 'uses' => 'ProfileController@send_message']);
			Route::get('mensaje/{id}', ['as' => 'messages.show', 'uses' => 'ProfileController@show_message']);
			Route::put('mensaje/{id}', ['as' => 'messages.update', 'uses' => 'ProfileController@update_message']);
```

My Controller:
```php

public function my_messages(){
        // All threads, ignore deleted/archived participants		
		$data_header['title'] = 'Tus mensajes '.Auth::user()->user_config->name1;
		$data_header['user'] = Auth::user();	
        $data_header['threads'] = Thread::forUser(Auth::user()->id)->latest('updated_at')->get();
        // All threads that user is participating in
        // $threads = Thread::forUser($currentUserId)->latest('updated_at')->get();
        // All threads that user is participating in, with new messages
        // $threads = Thread::forUserWithNewMessages($currentUserId)->latest('updated_at')->get();
        return view('statics/user_my_messages',$data_header);
	}
	
	public function new_message(){
		$data_header['title'] = 'Este es tu perfil '.Auth::user()->user_config->name1;
		$data_header['user'] = Auth::user();
		$data_header['users'] = User::where('id', '!=', Auth::id())->get();
		return view('statics/user_create_message',$data_header);
	}

public function show_message($id){
		$data_header = [];
		try {
            $thread = Thread::findOrFail($id);
        } catch (ModelNotFoundException $e) {
            Session::flash('error_message', 'No existe esta conversación.');
            return redirect('perfil/mis-mensajes');
        }
		
		$yo = Participant::where('thread_id',$thread->id)->where('user_id',Auth::user()->id)->first();
		
		if($yo){
			// show current user in list if not a current participant
			// $users = User::whereNotIn('id', $thread->participantsUserIds())->get();
			// don't show the current user in list
			$userId = Auth::user()->id;
			
			$participantes = $thread->participantsUserIds();
			if(count($participantes) != 2){
				redirect('/');
			}
			foreach($participantes as $v){
				if($v != Auth::user()->id){
					$to_find = $v;
				}
			}
			
			$user = User::find($to_find);
			
			if (isset($user->user_config->nickname)){ $name_user = $user->user_config->nickname; }else { $name_user = $user->user_config->name1; }
			
			
			$data_header['title'] = 'Mensajes intercambiados con '.$name_user;
			
			$thread->markAsRead($userId);
			
			Session::flash('to_send',$id);
			
			return view('statics/user_show_messages', compact('thread', 'user'))->with($data_header);
		}else{
			return redirect('perfil/mis-mensajes/');
		}
	}

public function update_message($id)
    {
        try {
            $thread = Thread::findOrFail($id);
        } catch (ModelNotFoundException $e) {
            Session::flash('error_message', 'The thread with ID: ' . $id . ' was not found.');
            return redirect('messages');
        }
        $thread->activateAllParticipants();
		
        // Message
        Message::create(
            [
                'thread_id' => $thread->id,
                'user_id'   => Auth::id(),
                'body'      => Input::get('message'),
            ]
        );
        // Add replier as a participant
        $participant = Participant::firstOrCreate(
            [
                'thread_id' => $thread->id,
                'user_id'   => Auth::user()->id
            ]
        );
        $participant->last_read = new Carbon;
        $participant->save();
        // Recipients
        if (Input::has('recipients')) {
            $thread->addParticipants(Input::get('recipients'));
        }
        return redirect('perfil/mensaje/' . $id);
    }

```

**Comment by Gummibeer** [comment]
You can use `\Auth::id()` instead of `\Auth::User()->id` just to say. ;)

**Comment by JoanVt** [comment]
@Gummibeer Your answer is ok! Don't know why i'm not using this method. Updating and posting in secs...

**Comment by RudolfFussek** [comment]
@Gummibeer THANKS!!!!!!!!!! <3 <3 <3...

But now a last question. In will the messages in thread sort by ID DESC. Your answer in the another issues not helpful *for me*...

[php]$messages = $thread->messages()->orderBy('id', 'desc')->get()[/php]

In my Controller show() or who?

**Comment by Gummibeer** [comment]
where you want to get the sorted collection of the messages. In the Controller, View or where ever you need it.
You get a collection of, by ID, ordered messages for the given thread.

**Comment by RudolfFussek** [comment]
Ohh now I have understand it! Thanks for you help.
