### ISSUE TITLE
screenshot

### ISSUE THREAD

**Issue by VickG** [cmgmyr/laravel-messenger#106]
Can someone please show me how this chat looks like? I demo or at least a screenshot would be very helpful!

**Comment by cmgmyr** [comment]
Well the package is primarily just the backend functionality of a messaging system. This leaves a lot more flexibility for the developer to make it into what they need it to be. I do have a few starting view files included that will give you some good basics (in Bootstrap).

Messages Index Page...
<img width="798" alt="screen shot 2016-01-20 at 4 05 21 pm" src="https://cloud.githubusercontent.com/assets/4693481/12463110/bc823b2c-bf8f-11e5-823f-fc91b58f0b0c.png">

Message Thread Page...
<img width="796" alt="screen shot 2016-01-20 at 4 05 37 pm" src="https://cloud.githubusercontent.com/assets/4693481/12463111/bc826958-bf8f-11e5-9720-6e7502e00c37.png">

**Comment by Gummibeer** [comment]
A custom responsive templates in mobile view:

![Chat](https://pl.vc/2m0v9)

**Comment by Gummibeer** [comment]
![Chat](https://picload.org/image/wdcwlgg/screenshot_2016-01-20-23-20-28.png) - sry, wrong link

**Comment by Gummibeer** [comment]
Like you See including twemoji, but I have to add some more replacement codes like :) ;) :P and so on

**Comment by Gummibeer** [comment]
Like @cmgmyr said: it's just the Backend, so you can do whatever you want, that's why I love this package cause it doesn't force you to any routing, views or anything you don't want.

**Comment by a-komarev** [comment]
@Gummibeer your link returned: `Not Found`
