### ISSUE TITLE
How to start this app on laravel fresh installation ?

### ISSUE THREAD

**Issue by m-gamal** [cmgmyr/laravel-messenger#112]
I walked through the installation steps , but I can't know where is the start point of this app ?

**Comment by cmgmyr** [comment]
Have you looked at the [example files](https://github.com/cmgmyr/laravel-messenger/tree/master/src/Cmgmyr/Messenger/examples)?

**Comment by m-gamal** [comment]
Yes but i don't know how to sort or use them ? sorry about my questions :)

**Comment by Kenny11CZ** [comment]
In your controller, fe: MessageController, u can include these models and use them.
`use Cmgmyr\Messenger\Models\Message;
use Cmgmyr\Messenger\Models\Participant;
use Cmgmyr\Messenger\Models\Thread;`

Now u can do for example:
`$thread = Thread::create(['subject' => 'test' ]);`
this will create thread with subject "test".
`Message::create(
            [
                'thread_id' => $thread->id, //id of thread
                'user_id'   => Auth::user()->id, //id of message author
                'body'      => 'foo message', //message
            ]
        );`
this will create message and asign it to the thread created above.
And finally:
`Participant::create(
            [
                'thread_id' => $thread->id, //id of thread
                'user_id'   => Auth::user()->id, //id of message author
                'last_read' => new Carbon, //timestamp
            ]
        );`
this will create participant, user link to the thread, so you can acquire all users in this thread for examle.
`return view('messenger.show', compact('thread'));`
this will return view with variable $thread. 
And now in view you can acquire these informations and show it:
`<p>{{ $thread->latestMessage->user->name }}: {{ $thread->latestMessage->body }}</p>`
will look like "UserName: foo message".

Hope this helps...

**Comment by m-gamal** [comment]
@Kenny11CZ  thanks for your comment :) . but I want where is the start page not only the codes

**Comment by avlastenok** [comment]
There is no start page in a clean laravel app if the message package is the only thing you have installed in the project and you have taken the example files into you project and updated the routes file with the example routes then youapp.dev/messages
