### ISSUE TITLE
Override functions in Messagable.php trait

### ISSUE THREAD

**Issue by schonhose** [cmgmyr/laravel-messenger#115]
I need to change the threadsWithNewMessages() function, it now returns only the thread->id, but I need the complete thread collection.

However, I am having difficulties to override the trait, how can this be done?

**Comment by a-komarev** [comment]
[Traits overriding](http://stackoverflow.com/questions/11939166/how-to-override-trait-function-and-call-it-from-the-overriden-function/11939306#11939306) hope this helps.

**Comment by schonhose** [comment]
Yes, I have tried this in my messageControler. Basically, from what I remember is that you don't need to rename the function, as the one in the controller automatically overrules the trait.

Anyway, I just can't get it to work.

**Comment by schonhose** [comment]
Obviously I need more sleep. The trait `Messagable` is added to the user model. Hence, to overwrite the functions in the trait all I have to do is add them to the user model as well.

Working as expected now.
