### ISSUE TITLE
How to get participants of a thread on index page ?

### ISSUE THREAD

**Issue by cyrilblankaert** [cmgmyr/laravel-messenger#119]
Hi,

I don't know how to retrieve participants of a thread on the index page. I would like to show their pictures located on the users table, like as show view of messenger but on index view for each thread ! :) 

Is it possible ? 
Thank you ;)

**Comment by cmgmyr** [comment]
So you can do something like this on your index page (untested):

```php
foreach($threads as $thread) {
    foreach($thread->participants() as $participant) {
        // display image: $participant->user->avatar
    }
}
```

but I would suggest look into eager loading the participants/users in order to get some better performance. I hope that helps.

**Comment by cyrilblankaert** [comment]
It doesn't work, it returns nothing :( 
I'm on Laravel 5.1

```
@foreach($threads as $thread)
     @foreach($thread->participants() as $participant)
       <img src="{{$participant->user->avatar}}" alt="" />
     @endforeach
@endforeach
```

No error, no image, nothing :o
