### ISSUE TITLE
Composer update not showing new additions

### ISSUE THREAD

**Issue by mmguide2003** [cmgmyr/laravel-messenger#127]
I manually added your unreadMessagesCount but was getting:
**Non-static method Cmgmyr\Messenger\Models\Thread::userUnreadMessages() should not be called statically**
 so decided to do a composer update only to revert back to the older version without unreadMessagesCount. Can you update composer files to reflect the latest github if stable. I also wonder about this error, though it may go on update?

**Comment by mmguide2003** [comment]
Generally it would be useful to have an example for how to use these:
userUnreadMessagesCount
userUnreadMessages

As I'm getting issues when calling them

**Comment by cmgmyr** [comment]
Right - the latest changes are just in the `master` branch and not versioned yet, so you'd have to update your composer to look at `dev-master`. To use this, you should be able to do: `$userCount = Thread::userUnreadMessagesCount(1);`.

I need to solidify a few things before these changes are versioned, but it should be soon.

**Comment by mmguide2003** [comment]
Non-static method Cmgmyr\Messenger\Models\Thread::userUnreadMessagesCount()

**Comment by mmguide2003** [comment]
Thanks.
