### ISSUE TITLE
L5 support

### ISSUE THREAD

**Issue by avlastenok** [cmgmyr/laravel-messenger#13]
Will this package support L5 or only L4 ?

**Comment by cmgmyr** [comment]
Yes, I plan to make any adjustments needed to support L5. I'm hoping to do this within the next week or so (maybe sooner).

**Comment by avlastenok** [comment]
Thanks a lot for your answer and looking forward to it, we have been so happy to use your package here.

**Comment by cmgmyr** [comment]
@avlastenok I just pushed a bunch of updates for L5 which you can find on the [develop](https://github.com/cmgmyr/laravel-messenger/tree/develop) branch, please give it a whirl and let me know how everything works out. I'd like to get some more testers on L5 before I start tagging V2

I'll keep this ticket open for now

**Comment by avlastenok** [comment]
That really sounds awesome will give it a try later today.

**Comment by cmgmyr** [comment]
@avlastenok did you get a chance to try it out?

**Comment by avlastenok** [comment]
Sorry I did mean to but work took up all my time, I will see to it tomorrow when I need to start migrating a project from L4 to L5 which also uses your package so will give some details on how that goes.

**Comment by cmgmyr** [comment]
@avlastenok, no rush, just checking in :)

**Comment by avlastenok** [comment]
So far so good, got it all working as it should just one little thing as of laravel 5 the Form package is no longer in the core so when people try your examples out you might want to just add the fact that they need to pull in the illuminate/html package.
But beside that I have no issues we just successfully migrated to L5 with this included.

**Comment by cmgmyr** [comment]
Thanks @avlastenok, good idea. I half assumed that most people know that L5 doesn't have the form/html packages anymore, but I guess it's a good idea to make sure. I'll put a note in the readme tomorrow. I'm glad that everything else is working as expected though. If no one else reports any L5 issues, I'll probably tag it V2 by the end of the week, so keep an eye out for that too.

**Comment by avlastenok** [comment]
Yes i'm sure your right that most people know that by now but someone brand new to laravel might not have that knowledge yet so was more as a helper for them.
Thanks for all your work on this package we really appreciate it.

**Comment by cmgmyr** [comment]
No problem at all! I'll probably be tagging v2 at some point tomorrow too

**Comment by cmgmyr** [comment]
just tagged v2
