### ISSUE TITLE
Getting attribute from related table

### ISSUE THREAD

**Issue by adehazril** [cmgmyr/laravel-messenger#135]
Hi, this is not an issue, but I'm having trouble while implementing this package to my program.

I have 2 kinds of user: client and vendor.
Both users stored on **users** table (name, email, etc), but vendor can create their business profile which the info about this are stored in **vendors** table (vendor_name, since, etc).

I'm creating the index page that lists all the thread, but I wanted the vendors to be listed by their vendor_name on the vendors table. I tried to use 

> $thread->participantsString(Auth::id(), ['vendor_name'])

 but it doesn't work. Any workaround?

**Comment by Gummibeer** [comment]
This method doesn't support related models - it directly puts the column in the select query. You can create your own method that loops over all the participants, gets the users and joins the display names depending on the type.
