### ISSUE TITLE
Create artisan command to generate foreign keys

### ISSUE THREAD

**Issue by cmgmyr** [cmgmyr/laravel-messenger#137]
Will adding an optional artisan command and migration file to the package make sense? Seems like we should just leave this up to the individual dev to work out.

Refs PR #131

**Comment by a-komarev** [comment]
That would be very useful in some cases.

**Comment by avlastenok** [comment]
It's so easy to add them if you need them that it would seem like a waste of extra artisan command.

**Comment by cmgmyr** [comment]
closing for now, please see #291 for a foreign key migration
