### ISSUE TITLE
BadMethodCallException  'Call to undefined method Builder::newMessagesCount()'

### ISSUE THREAD

**Issue by apaleja** [cmgmyr/laravel-messenger#138]
any guidance to solve this error ? 

`BadMethodCallException with message 'Call to undefined method Illuminate\Database\Query\Builder::newMessagesCount()'`

**Comment by cmgmyr** [comment]
What version of messenger and Laravel are you running?

**Comment by a-komarev** [comment]
@cmgmyr I'm not sure it's a solution, but check this comment out: #133#issuecomment-224885501

**Comment by cmgmyr** [comment]
I reverted the code from that PR, so that is pretty odd. I'll take a closer look

**Comment by apaleja** [comment]
@cmgmyr 
Laravel 5.2
Messenger 2.11

**Comment by cmgmyr** [comment]
Are you using the `unread-count.blade.php` file from the examples? That will need to be updated to use the changed method name of `newThreadsCount()`.

**Comment by apaleja** [comment]
@cmgmyr Yes. you are right. I missed notes of 2.11. Thanks for the heads up. and Great Package. BTW.

**Comment by cmgmyr** [comment]
No problem, glad it worked out. Thanks for using the package!

**Comment by apaleja** [comment]
I have another question, with is not related to this error . if you could answer.. 

What is the best way to have one open thread with group threads (I am able to implement this based on examples. ) . Any example ?

**Comment by cmgmyr** [comment]
sorry @apaleja, I'm not sure I follow - could you be more specific?

**Comment by apaleja** [comment]
@cmgmyr  based on examples, I have implemented one-to-one and group chat. with this, I also want to have one Open Thread where all users can chat. what is the best way to have a Open Thread for all current users (and auto add new users) ? any examples available ?

**Comment by cmgmyr** [comment]
I'd just set up two controllers - one for 1-to-1 messaging and another for group-based messaging, then have them use a shared parent controller for any shared functionality needed.

**Comment by apaleja** [comment]
Thank you very much for heads up @cmgmyr .
