### ISSUE TITLE
newMessagesCount() error

### ISSUE THREAD

**Issue by Nulimitz** [cmgmyr/laravel-messenger#140]
I am getting an error when i include newMessagesCount() in my navigation. I looked through the laravel/messenger models and could not see a function for that. Should it be in the user model ? or messages model ?

**Comment by Nulimitz** [comment]
I am also getting an error when submitting FatalErrorException in f7c98688a4e52d91fc351ec5221978a2301053f3.php line 15: Call to undefined function link_to()

    in f7c98688a4e52d91fc351ec5221978a2301053f3.php line 15

**Comment by cmgmyr** [comment]
Please look at the notes from the [latest release](https://github.com/cmgmyr/laravel-messenger/releases/tag/2.11). The API has changed for that method. The `link_to` function is from the LaravelCollective HTML package, so if you aren't using that in your project, you'll have to create the links a different way.

**Comment by Nulimitz** [comment]
Got it thank you I ended up using <a href="{{ url('messages/' . $thread->id) }}">{{ $thread->subject }}</a> Just have one minor glitch I need to figure out on the add new message form, it is not showing a username for a particular user.
