### ISSUE TITLE
Show a list of thread messages

### ISSUE THREAD

**Issue by theunreal** [cmgmyr/laravel-messenger#142]
I'm using this package only as a backend (laravel is just the backend of my app) and I find it difficult to output the thread with all the thread's messages. The example show() method outputs only the thread basic information:

![image](https://cloud.githubusercontent.com/assets/6171883/16518132/dff56e4c-3f89-11e6-953f-7f6fafdffce3.png)

**Comment by haheute** [comment]
In my site, this is happening:

`$thread = Thread::with('messages.user')->findOrFail($id);`

perhaps it helps

**Comment by theunreal** [comment]
Awesome, Thank you!
