### ISSUE TITLE
Restrict package to one-to-one messaging

### ISSUE THREAD

**Issue by halnex** [cmgmyr/laravel-messenger#145]
Hello,

First of all, great package, great work, thank you.

I have installed it and it works perfectly.

However, if User1 sends a message to User2, User3 can see the message and participate in it by default.

So I opted to using 

> $threads = Thread::forUser($currentUserId)->latest('updated_at')->get();

on the `show()` method to only show the messages related to the user directly.

However, if I login with User3 and navigate to `/messages/5` which is a private message between User1 and User2, I can still see it and participate in it.

How can I disable that? I would like to use only one-to-one messaging.

**Comment by halnex** [comment]
I browsed the closed issues here and found a thread talking about the same issue
https://github.com/cmgmyr/laravel-messenger/issues/29

You said that we need to create our own conditions and add them to the `show()` method to prevent users seeing messages that don't belong to them.

So I went and did just that, it looks like it is working but would appreciate if you can confirm that this is the correct method of doing it.

In `show()` method, I added the following

```
$participants = $thread->participantsUserIds()->toArray();

        if(in_array($userId, $participants)) {
            return view('messenger.show', compact('thread', 'users'));
        } else {
            Session::flash('error_message', 'You can\'t view this message');
            return redirect(route('messages'));
        }
```

so now if a user is not part of the message, he gets redirected to the messages route with an error message.

**Comment by cmgmyr** [comment]
Yes, you can either do that or use the built-in `$thread->hasParticipant($userId)`

Thanks for using the package, I'm glad you like it!

**Comment by Gummibeer** [comment]
If you use laravel 5 with authorization a good way would be to create a thread policy with methods like `read()` `create()` `respond()` and so on. With this you can simply check these things with the controller `authorize()` method or the `can()` one on the user Model or the `@can` Blade Tag. And if you want to add a check later simply extend the policy.
