### ISSUE TITLE
Replace users' checkboxes with Typeahead

### ISSUE THREAD

**Issue by halnex** [cmgmyr/laravel-messenger#146]
Giving users the ability to select the recipient through a checkbox is not really ideal.

Suppose I have thousands of users, it would become cumbersome to search and select the recipient.

So I'm trying to replace it with Typeahead JS library: https://twitter.github.io/typeahead.js/

I noticed then whenever I send a message to another user, 2 records get created in the `participants` table, one with my ID and another with the recipient user's ID.

But after integrating Typeahead, only 1 record is being created with my ID only, there's no trace of the recipient's ID in the table, therefore, no messages are being delivered.

This is what I did.

First, I created the route

`Route::get('messages/data/usernames/{query?}', 'MessagesController@getUsernames');`

Then I created a function in `MessagesController` to get the usernames and return JSON
```
public function getUsernames($query = '') {
        $q = User::select('id', 'username');
        if ($query) {
            $q->where('username', 'LIKE', '%' . $query . '%');
        }
        return Response::json($q->get());
    }
```

I then edited `create.blade.php` and added the input fields
```
<div class="form-group" id="remote">
     <input class="form-control typeahead" type="text" placeholder="Choose a Username" name="username_name">
     <input type="hidden" class="username_id" value="" name="username_id">
</div>
```

And this is the JS
```
var usernames = new Bloodhound({
        datumTokenizer: Bloodhound.tokenizers.obj.whitespace('username'),
        queryTokenizer: Bloodhound.tokenizers.whitespace,
        prefetch: 'data/usernames',
        remote: {
            url: 'data/usernames/%QUERY',
            wildcard: '%QUERY'
        }
    });
    $('#remote .typeahead').typeahead(null, {
        name: 'username',
        display: 'username',
        source: usernames
    });
    $('#remote .typeahead').bind('typeahead:select', function(ev, suggestion) {
        $('.username_id').val(suggestion.id);
    });
```

So when I start typing a name, it auto-completes it and I can select it and carry on with the message. But no record in the database is being insert with the recipient's ID.

**Comment by cmgmyr** [comment]
The checkboxes are just for demo/example purposes, it's really up to the dev to implement whatever they deem necessary in their own app. I'm going to leave the example files as-is for now, but I'm sure your code will help out other devs that need something similar. Thanks for your contribution!

**Comment by halnex** [comment]
That's too bad, I'm not able to integrate it with Typeahead.

O well... thanks anyway

**Comment by halnex** [comment]
I got it to work, I had to modify the MessagesController L106

Change `$input['recipients']` to `$input['user_id']`

and rename the hidden input field to `user_id[]'

```
<div class="form-group" id="remote">
       <input class="form-control typeahead" type="text" placeholder="Choose a Username" name="recipients[]">
       <input type="hidden" class="user_id" value="" name="user_id[]">
</div>
```

**Comment by Gummibeer** [comment]
@halnex: there are some more problemlos, the original Checkboxen way sends an Array of IDs to allow Group Chats. In your solution you can select multiple Users in the typeahead but just the last id is stored.
Two ways to solve it:

1. Append the id comma seperated and explode in PHP
2. Clone the hidden Input everytime and keep it as an Form Array.

The next Problem is that typeahead has also options to delete an entry, if you do this the id also should get deleted.
And the last thing is that the original typeahead package is abandoned - there is a Community fork that does future development.

As an idea: we use a extended select picker with search and so on. This performs very well and sends, without JavaScript Hacks the id and removed it from the Array and so on.

**Comment by halnex** [comment]
@Gummibeer Thank you for your suggestions. I had no idea Typeahead was abandoned, that changes everything.

You are correct that in my solution you can only add 1 users to the chat and that's what I wanted, one-to-one private messaging without any participants.

I thought about using a searchable select field but then again what if you have thousands of users, are you gonna load them all every time you want to message a user? Even if you got the users via ajax it would still be too much load on the server.

can you link me to the Typeahead community fork?

**Comment by Gummibeer** [comment]
https://github.com/corejavascript/typeahead.js

And the thing with loading thousands of entries: typeahead also loads them all, you use the prefetch ;)
The only thing is that they don't load them all as html - we solved this by creating a fake select - you HAVE to use the search cause the select as it is is empty - on search we are also querying via ajax and displaying the results als select options in addition to the already selected people.

So it's very similar to typeahead but with the advantage of a select field which has multiselect as array by default and different values from display names.

**Comment by halnex** [comment]
@Gummibeer I am using that typeahead library.

I suppose you are correct about typeahead fetching all the users on load, which is also a problem.

Mind sharing which multiselect library you are using?

**Comment by Gummibeer** [comment]
@halnex some links for you:

* http://getbootstrapadmin.com/remark/base/ great theme with a lot of javascript plugins
* https://select2.github.io/options.html pretty select with ability to load via ajax
* http://silviomoreto.github.io/bootstrap-select/ pretty select in bootstrap style - needs custom code to handle ajax source

**Comment by halnex** [comment]
@Gummibeer no need to share source code, I'll figure it out :)

Thank you for these links, that bootstrap admin looks sweet.

**Comment by HDVinnie** [comment]
@halnex did you figure out a way to accomplish this? As the checkboxes are not optimal when you have 1,000's of users

**Comment by Promixius** [comment]
Algolia
