### ISSUE TITLE
Need help in implementing private chat

### ISSUE THREAD

**Issue by SamuelYute** [cmgmyr/laravel-messenger#149]
So I'm new to laravel and php overall...i know a few things here and there... But i love this package and i want to include a private messaging system (inbox) how can i change the thread model and participants model to enable such a feature and that index.blade.php should show user threads

**Comment by Gummibeer** [comment]
You don't have to change anything on the Models. And this Question was asked and answered multiple times already - can you pls take a look in the closed issues!?

**Comment by SamuelYute** [comment]
Thanks for the help...i checked
