### ISSUE TITLE
Error: Call to undefined method Carbon\Carbon::all()

### ISSUE THREAD

**Issue by mpijierro** [cmgmyr/laravel-messenger#154]
Hi,

I updated Composer and updated last version of laravel-messenger.

**My config is:**
- Laravel Framework version 5.1.41 (LTS)

- Composer config:  "cmgmyr/messenger": "~2.0"   -> I do composer update and....

* Removing cmgmyr/messenger (2.11)
* Installing cmgmyr/messenger (2.12)

That is to say, I have 2.12 version.

**The error is:**
FatalThrowableError in Messagable.php line 75:
Call to undefined method Carbon\Carbon::all()

**The code is:**

$participants = Models::participant()->where('user_id', $this->id)->pluck('last_read', 'thread_id');

        /**
         * @todo: see if we can fix this more in the future.
         * Illuminate\Foundation is not available through composer, only in laravel/framework which
         * I don't want to include as a dependency for this package...it's overkill. So let's
         * exclude this check in the testing environment.
         */
        if (getenv('APP_ENV') == 'testing' || !str_contains(\Illuminate\Foundation\Application::VERSION, '5.0')) {
            $participants = $participants->all();   <----- LINE 75
        }

**If I do**:  dd($participants) I see..

Carbon {#1690 ▼
  +"date": "2016-04-06 17:20:45.000000"
  +"timezone_type": 3
  +"timezone": "Europe/Madrid"
}

My temporary solution is install 2.11 version. Its work.

Thanks

**Comment by cmgmyr** [comment]
Thanks for reporting. I'm going to look into this.

**Comment by spikerok** [comment]
This is due to recent change of lists to pluck, for some reason carbon date overrides it.

**Comment by cmgmyr** [comment]
@mpijierro this should be fixed in all version of Laravel. Can you please double check on your side? You can update your `composer.json` file to point to `dev-master`. This will be officially tagged shortly.

**Comment by mpijierro** [comment]
@cmgmyr I updated to dev-master (2.12). Everything works fine again.

Thank you very much, great job!

**Comment by cmgmyr** [comment]
this has now been released in `2.13`
