### ISSUE TITLE
How to implement new message count in Messagable

### ISSUE THREAD

**Issue by brygom** [cmgmyr/laravel-messenger#155]
Hi! please help me to implement a function in Messagable for access from unread-count.blade.php and count new messages in threads.

I already trying using `userUnreadMessagesCount($user_id)` for this way:

In Messagable i add this lines:
```
/**
     * Returns the new messages count for user.
     *
     * @return int
     */
    public function newMessageCount($user_id)
    {
        //$threads = Models::thread();
        return $this->noReadMessage($user_id);
    }

/**
     * Returns all threads with new messages.
     *
     * @return array
     */
    public function noReadMessage($id)
    {

        return $this->userUnreadMessagesCount($id);
    }
```

I giving this error:

> Call to undefined method Illuminate\Database\Query\Builder::userUnreadMessagesCount()

**Comment by zanderp** [comment]
https://github.com/cmgmyr/laravel-messenger/releases/tag/2.11

**Comment by cmgmyr** [comment]
You can try implementing something like this (untested):

```php
return Thread::forUserWithNewMessages($this->id)->map(function($thread) {
    return $thread->userUnreadMessagesCount($this->id);
})->sum();
```
