### ISSUE TITLE
Compatible with Laravel 5.1

### ISSUE THREAD

**Issue by tlandn** [cmgmyr/laravel-messenger#156]
Hi

Do you still support Laravel 5.1? Since use pluck instead of lists , the package not working anymore with 5.1.

Thanks.

**Comment by Promixius** [comment]
I see what you mean, but have you thought about updating?
It's only like 5 minutes of changing a few things and you get a bunch of improvements on top of it.
Further 5.3 is only days away now with even more great additions to the framework.

**Comment by tlandn** [comment]
Hi Promixius, my website is about to live , and I choose 5.1 because it's LTS. I hope my site can run 3,4 years before thinking of updating.

I want to know @cmgmyr  opinion about this. If this package only supports Laravel 5.3, then I must think of updating my site (not 5 minutes changing few things, it takes 6 months to develop my site, so you know).

**Comment by a-komarev** [comment]
@tlandn You can extend and override any model you want if you require it.

**Comment by Promixius** [comment]
You might have had a long development time on the project but if you look at the upgrade guide it's quite small changes you have to do, and most if not all are unlikely to affect your application.
Further LTS on 5.1 will only have bug fixes till June 2017 and security fixes till 2018 so your 3 to 4 year without upgrading should be reconsidered.

**Comment by cmgmyr** [comment]
@tlandn yes, I'm certainly hoping to support all Laravel 5 versions. The pluck vs lists has come up in a different issue (#154) which I started looking into. In the meantime, you can either downgrade the package to `2.11`, or override the package files with your own. I'm hoping to have a fix done within the next day or so.

The hard part with the Laravel version changes is that I've noticed certain versions doing something one way, then others doing something different. My hope is that I won't need to be checking the installed version number in the code (which is ridiculous), or keep this packages code locked to minor versions (ex L5.1.* => M2.11.*, L5.2.*=>M2.12.*, etc). Ideally, I'd like to have all new versions of Messenger available to all Laravel 5+ installs. We'll see how that works out, though.

As an aside, I would also recommend upgrading to Laravel 5.2, then 5.3 when it comes out. You can either do it manually as outlined in the docs, or use something like [Laravel Shift](https://laravelshift.com/) - as long as you are using Laravel in the standard way. It will be well worth the investment in the long run - especially if you are planning on maintaining it for the next few years.

**Comment by tlandn** [comment]
Thank @cmgmyr , @a-komarev, @Promixius , I already decide to upgrade to 5.2 (and 5.3 later).
