### ISSUE TITLE
Best way to notify user?

### ISSUE THREAD

**Issue by RokSiEu** [cmgmyr/laravel-messenger#16]
Hi, 

one question, did you think about implementing "notification" when new message arrives? 
If user A and B are chatting then it would be good idea that are somehow notified when new message comes (for example something like twitter/facebook notification).

**Comment by cmgmyr** [comment]
Hi @RokSiEu, yes I do have an example for new/unread threads. You can take a look at it in the [view file](https://github.com/cmgmyr/laravel-messenger/blob/master/src/Cmgmyr/Messenger/examples/views/messenger/unread-count.blade.php). Is that what you mean? There currently isn't anything built in for a pop up or email notification though.

**Comment by RokSiEu** [comment]
I'm looking for a way to implement real time notifications. That way messaging becomes instant :)

**Comment by ziming** [comment]
@RoksiEu you may wish to check out something like PubNub or Pusher for this.

**Comment by cmgmyr** [comment]
I'll second what @ziming said about using a service like Pusher. That would be your best option to make it more of a real time experience through your UI. As far as what you can use with the package, you could create some [Model Event Listeners](http://laravel.com/docs/5.0/eloquent#model-events) to see when a thread/message is saved, grab the data, and notify your participants.

**Comment by opheliadesign** [comment]
I am using Pusher to handle user notifications, combined with Bootstrap Growl (now $.notify JS). Each page in my Members section contains the Javascript to connect to a Pusher Private Channel and respond to message notifications. If the user is not directly viewing the thread for which the notification was created, a Growl appears and their message counter in the navbar flashes and increments. If they are viewing the same thread, the new messages is appended along with a Growl - basically realtime chat.

**Comment by cmgmyr** [comment]
Sounds like a nice system @opheliadesign!

I'm going to close this as an issue, but feel free to keep the discussion going if you want everyone.
