### ISSUE TITLE
Send images

### ISSUE THREAD

**Issue by nikolaynesov** [cmgmyr/laravel-messenger#162]
Hi,

What do you think is the best way for simple images sharing in chat app using this package?
1) upload image & create new message with image name and some prefix to determine that it is image, not a simple message. It means 1 message = 1 image. 
2) Separate attachments model. Upload images as attachments & attach them to some message with pivot table. 1 message + multiple images attached.
3) Use tags inside a message with image names like [img-name] and covert them to images in frontend. 1 message + multiple images attached.
Or maybe something else?

**Comment by a-komarev** [comment]
In my opinion images should be stored in external table to have manipulation capabilities and using them in other parts of the application.

**Comment by cmgmyr** [comment]
I'd also go with option 2, that way you can use the attachments any way you want and also implement them throughout the app if needed - like with [Polymorphic Relations](https://laravel.com/docs/5.3/eloquent-relationships#polymorphic-relations) (adding attachments to posts, pages, etc) might be helpful.
