### ISSUE TITLE
$this->threadsWithNewMessages() returns an empty array

### ISSUE THREAD

**Issue by schonhose** [cmgmyr/laravel-messenger#163]
The function `newThreadsCount()` in **Messagable.php** returns the number of unread messages. However, the `$this->threadsWithNewMessages()`  returns an empty array when there are no messages.

`$this->threadsWithNewMessages()->count();` does not work on an array, you will need to have use `count($this->threadsWithNewMessages());`

**Comment by cmgmyr** [comment]
What version of Laravel and Messenger are you using?

**Comment by schonhose** [comment]
`laravel/framework": "5.1.*`
`cmgmyr/messenger": "~2.0`

I did a `composer update` just an hour ago (before finding the issue).

**Comment by schonhose** [comment]
The way I have fixed this is changing the code for the newThreadsCount to:

```
public function newThreadsCount()
{
    $result = $this->threadsWithNewMessages();
    if (is_array($result))
    {
            return count($result);	
    } else {
            return $result->count();	
    }
}
```

**Comment by pvdptje** [comment]
I could be wrong, but the query builder returns a collection, which implements arrayaccess. So this should work as well:

```
public function newThreadsCount()
{
    return count($this->threadsWithNewMessages());
}
```

Could you try this out and let me know?

**Comment by schonhose** [comment]
I updated to cmgmyr/messenger (2.13.1) and was faced with the same problem. It was a nice opportunity to test the code above.

The code provided by pvdptje works.

**Comment by cmgmyr** [comment]
@schonhose what specific version of Laravel are you using? I'm using `5.1.45` in my test repo [here](https://github.com/cmgmyr/test-messenger-laravel51) and am not running into this issue.

**Comment by schonhose** [comment]
@cmgmyr I am using the same version of laravel: `5.1.45 (LTS)`.

However, my database is empty (e.g. there are no messages whatsoever).

**Comment by cmgmyr** [comment]
Hmm, I'm really not sure why you are getting this error. The `threadsWithNewMessages()` returns a query builder collection, which would have `->count()` available to it. In my test repo I have empty tables except for users, and I still can't come across this error. 

I'm going to close this issue for now, but I'll revisit if I see a lot of others having the same issue. In the meantime, you can add @pvdptje's solution in your `User` model which will override the trait method.
