### ISSUE TITLE
Get latest thread

### ISSUE THREAD

**Issue by danieljausovec** [cmgmyr/laravel-messenger#167]
Hi.

I get error because i don't have field "name" in users table. How to change this to custom one or more fields? (firstname and lastname).

Error message:
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'users.name' in 'field list' (SQL: select concat(users.name) as name from `users` inner join `messenger_participants` on `users`.`id` = `messenger_participants`.`user_id` where `messenger_participants`.`thread_id` = 2 and `users`.`id` != 1) 

**UPDATE**
I have solution...

I will do Fork.

**Comment by cmgmyr** [comment]
You can add additional column names to

```php
$thread->participantsString($userId, ['first_name', 'last_name']);
```
