### ISSUE TITLE
Select threads

### ISSUE THREAD

**Issue by danieljausovec** [cmgmyr/laravel-messenger#169]
Hi.

In function `participantsString()` (Model Thread) is set fixed user primary key to `id`. How to change this? 
I have in user table primary key `user_id`.

Error code:
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'users.id' in 'on clause' (SQL: select concat(users.firstname, ' ', users.lastname) as name from `users` inner join `messenger_participants` on `users`.`id` = `messenger_participants`.`user_id` where `messenger_participants`.`thread_id` = 1)

See PR **#168** to solution

**Comment by cmgmyr** [comment]
I just merged some changes into the `master` branch to fix this. Right now you can update your `composer.json` file to look at `dev-master`. This will be included in the next release

**Comment by danieljausovec** [comment]
I like it. Thanks.

**Comment by danieljausovec** [comment]
I have update plugin and get this error.

`Model.php line 765:
Class 'App\User' not found`

In config file i have set User model location

**Comment by cmgmyr** [comment]
@danieljausovec can you do another composer update against `dev-master` again? I made a few more adjustments. Hopefully, that fixed the issue

**Comment by danieljausovec** [comment]
It's works. Tnx.
