### ISSUE TITLE
models to json question / how to enhance?

### ISSUE THREAD

**Issue by marco-solare** [cmgmyr/laravel-messenger#17]
Hi there Chris, thanks for this great package!
Threw it into my new l5 version of one of my projects and it works like a charm.
I got one general question though:
Is there a generic way to get one or more threads as "flat" json objects that already contain properties like `latestMessage, isUnread, messages, participants`?

The reason I am asking is:
When working with AngularJS one cannot (of course) do something like you do in the example views:
{!! $message->user->first_name !!}
to access related data like messages or participants as we cannot call these php-methods on json objects.
So in my code I end up with something like:

    $threads = Thread::getAllLatest();
    foreach ($threads as $key => $thread) {
        $thread['latestMessage'] 	= $thread->latestMessage()->body;
        $thread['isUnread']		= $thread->isUnread($this->user_id);
    }

This works but it seems a bit odd (I guess there is a more elegant and more generic way to do this).

I event tried and succeeded in duplicating the Thread model, putting my version of it in the App namespace and do modifications on it.
I can use this Version but again, I think this is not the preferred way to do this.

To put it short:
would it be possible to have a `toJson()` method on the `Thread` model that would give properties like `latestMessage, isUnread, messages, participants` right away?

best, Marco

**Comment by cmgmyr** [comment]
Hi @marco-solare, I'm glad you like the package and that it's working out well for you in your project! I'll have to look into how to add those enhancements. I'm traveling until next week, so I won't be able to work on it too much, but I'll jump in more when I get back.

In the meantime, I think you are handing the problem correctly and building up the data you need in your controller. That's what I typically do when working with Angular. If you have any other questions, just let me know.

**Comment by marco-solare** [comment]
Hi @cmgmyr thanks for the quick reply!
Well, I would _try_ to implement some freaky json method myself for starters, maybe I could contribute some little method.
Just unsure how to go about it - maybe just implementing it in Thread model?

**Comment by cmgmyr** [comment]
Yeah, that would work on the Thread model. If you want to you can always make a new method and create a Pull Request.

**Comment by marco-solare** [comment]
alright, I'll look into it tonight. save travel to you

**Comment by 0mattoz** [comment]
I've opened a pull request for this feature.

**Comment by cmgmyr** [comment]
@0mattoz, thanks again for the PR #24. I left you a longer comment there, but I don't think this is a good fit for the package. The data needed by SPA devs can be vastly different and I don't think this package should be that opinionated. There are multiple ways that you can get the data needed, but I don't think there is a one size fits all solution.

I'm going to close this issue for now, but please feel free to continue the conversation if needed. Thanks again for the PR and using this package!
