### ISSUE TITLE
Call to undefined method Illuminate\Database\Query\Builder::newThreadsCount()

### ISSUE THREAD

**Issue by PortgasDKiba** [cmgmyr/laravel-messenger#172]
Hello,

I have this error when I'm trying to display the count of messenger.

The difference is that I use the count variable in my navbar.blade.php.

Can someone help me please ? :)

**Comment by toscani** [comment]
Did you include the Trait on your model?

**Comment by PortgasDKiba** [comment]
Oh my... I haven't save my User model since this morning... Thank you toscani !
