### ISSUE TITLE
Seeding database for testing

### ISSUE THREAD

**Issue by Evoolo** [cmgmyr/laravel-messenger#176]
Hi,

at first i want to thank you for that awesome package, i use it in an social network for user 2 user communication. 

I want to do some penetration testing so i need to seed my threads and messages table. 

It's really hard for me to figure out how to do that with threads and messages. I already seeded the user table with 50 random users. now i want to create threats and messages from every of that random user to one specific user wich i had defined seperate in the user table seeder. 

had anyone did this before and can tell me how it works?

I'm really new to laravel 

thanks in advance

**Comment by cmgmyr** [comment]
Hi @Evoolo, thanks for using the package! Please take a look at my testing repos for a few examples of how you can seed thread data. Just pick the repo that corresponds with the version of Laravel you're using. If you have any further questions, or need additional help, just let me know.

**Comment by Evoolo** [comment]
Oh i should open my eyes. You are Awesome. Thanks, that schould do the trick.
