### ISSUE TITLE
Any live demo?

### ISSUE THREAD

**Issue by artiumedia** [cmgmyr/laravel-messenger#177]
I would like to know is anyone has already set Laravel messenger, and if possible there is a live URL from where I can test it and see its functionality.

**Comment by a-komarev** [comment]
@artiumedia There is no official public demo available at this moment, but you read about implementations here: https://github.com/cmgmyr/laravel-messenger/issues/55

**Comment by cmgmyr** [comment]
@artiumedia you can also pull down one of the test repos, like for [Laravel 5.3](https://github.com/cmgmyr/test-messenger-laravel53), run the migrations and database seeders, and you'll get a basic working version.

I've been planning on making a demo site and maybe some videos, but just haven't gotten around to it yet. If you have any questions about the package, please let me know.

**Comment by MurKit** [comment]
@cmgmyr videos would be super nice. But while there is none, could you write sort of a guide or howto on using the main features of the package?
