### ISSUE TITLE
Trying to implement in a Golf Clubs community site, not working in Laravel 5.3  :\

### ISSUE THREAD

**Issue by djamesfar** [cmgmyr/laravel-messenger#178]

**Comment by a-komarev** [comment]
Can you describe your issue more concrete, please? Right now it's looks like: *Something isn't working.* And it could be anything... Your domain, server hardware, server software, database, Laravel itself or  Messenger package...

**Comment by cmgmyr** [comment]
closing for now, will reopen if needed after more details from @djamesfar are given
