### ISSUE TITLE
Getting participants name

### ISSUE THREAD

**Issue by HGtronic** [cmgmyr/laravel-messenger#18]
Hello, how to get all the participants names of some thread, want to list their name...
So when someone opens the index page should see from who he has received message...

**Comment by HGtronic** [comment]
I use this  {!! $thread->participantsString($thread->user) !!}
and the function is
    public function participantsString($user)
    {
        $user = $user ?: \Auth::user()->id;

        $participantNames = \DB::table('users')
            ->join('participants', 'users.id', '=', 'participants.user_id')
            ->where('users.id', '!=', $user)
            ->where('participants.thread_id', $this->id)
            ->lists('users.name');

        return implode(', ', $participantNames);
    }

**Comment by avlastenok** [comment]
That seems like a lot of work for something you already have by default.
you already have a Message Eloquent model, so why not just make a relationship.
public function user()
{
return $this->belongsTo('Users', 'foreign_key', 'local_key');
}

**Comment by cmgmyr** [comment]
@HGtronic Yes, I think adding the `participantsString` method back in would be helpful. I just have to see what the best way to accomplish this would be. In your example you just have a `users.name`, but it gets more complicated if you have `users.first_name` and `users.last_name`, or have that configurable. I have a few ideas, so I'll work on it.

@avlastenok doing something like that could be an option, but I think it would be too messy to get the data you wanted.

**Comment by avlastenok** [comment]
@cmgmyr  actually your totally right I was on the train while writing, and i failed to read his full query and therefor my reply reflected that.
So ignore my comment, as I thought the Op was talking about when viewing the message.

**Comment by cmgmyr** [comment]
@avlastenok no problem at all :)

**Comment by cmgmyr** [comment]
@HGtronic this is now in place in versions 1.1 and 2.1 (Laravel 4 & 5). Here are some uses:

```
# Show all participants, excluding current user, show default user first_name and last_name
$thread->participantsString(Auth::id());

# Show all participants, excluding current user, show only first_name
$thread->participantsString(Auth::id(), ['first_name']);

# Show all participants, including current user, different user name column
$thread->participantsString(null, ['username']);
```

Because you are just using `name` in your database table and not `first_name` and `last_name`, you'll have to pass `['name']` as the second parameter. Let me know if you have any questions.
