### ISSUE TITLE
Get participant that is not you in a private thread of only two

### ISSUE THREAD

**Issue by dmarman** [cmgmyr/laravel-messenger#182]
I find useful to get the name of the other person in a conversation one to one. I normally use it to display the name of the other participant in my "inbox" page. I couldn't find any method inside the Thread model that could do that so I wrote one for myself. This method will add the property "theOtherParticipant" when the method is called.

Let me know if something could be done better or something is missing.

```
public function scopeTheOtherParticipant()
    {
        if(count($this->participants) === 2)
        {
            foreach($this->participants as $participant)
            {
                if($participant->user_id !== Auth::user()->id)
                {
                    $this->theOtherParticipant = User::findOrFail($participant->user_id);
                };
            }
        }

    }
```

Example of use in the MessagesController:

```
public function index()
    {
        Carbon::setLocale('es');

        $currentUserId = Auth::user()->id;

        $threads = Thread::forUser($currentUserId)->latest('updated_at')->get();
        
        foreach($threads as $thread)
        {
            $thread->theOtherParticipant();
        }

        return view('messenger.index', compact('threads', 'currentUserId'));
    }
```

in the views:

`<strong>@if(isset($thread->theOtherParticipant->name)){{ ucfirst($thread->theOtherParticipant->name) }}@endif - {{ $thread->subject }}</strong>`

**Comment by a-komarev** [comment]
1) Wouldn't it be optimized to use `$this->participantsUserIds(Auth::id())`?

2) What will be if there are more than 2 users participate this thread?

3) I like your idea, but the name of method isn't so obvious. But I can't make any better names because PrivateParticipant is pretty complicated too.

**Comment by dmarman** [comment]
Yes, I should have implemeted with `$this->participantsUserIds(Auth::id())` . I guess it should be without the Auth::id(), the method is already fetching myself into the array.

My aplication does not allow threads with more than two participants.

The name it is kind of awkward, maybe somethink like interlocutor()?

**Comment by cmgmyr** [comment]
@dmarman thanks for the idea! I'm going to think on this one a bit more to see if I can come up with a more optimized option

**Comment by joshlabau** [comment]
I wrote an extension class for Thread that implements the following:

```
public function otherParticipant(User $user = null) {

	$user = $user ? $user : Auth::user();

	return $this->participants()->where('user_id', '<>', $user->id)->first()->user;
}
```
You could easily add some logic to return something different if no other participant were found, or to return the collection of other participants if you want all of them who aren't the specified user.

**Comment by a-komarev** [comment]
@joshlabau What if not instance of default User will be bypassed to the method? User can overwrite User model via config.

**Comment by Gummibeer** [comment]
@dmarman solving it with a scope isn't good. Scopes are for the querry builder and should get passed and Return a query builder instance.
Better way would be accessors and mutators.

Next point: settings it as a direct property of the model is also not good, attributes should be in the attributes Array and No property of the model.
To Cache the value you can put the result in the attributes array and do a simple `array_key_exists()`.

And like Said: there should be better Handling of 3+ users and the naming could be better.
