### ISSUE TITLE
Polymorphic relation instead of a set User model

### ISSUE THREAD

**Issue by xKairu** [cmgmyr/laravel-messenger#186]
I'm currently using this package for a user <-> user messaging system, which works fine. Now I'm wanting to have different models from Laravel Spark (Teams especially) being able to message a user or a group of users.

For example:

User <-> User
Team <-> User

I tried making the change myself, but the way the user is stored as a participant rather than a direct user->message relation made it rather confusing.

Is this possible to implement?

**Comment by a-komarev** [comment]
@xKairu I suppose you will be addressed to #121 and other related issues. This question has been raised couple of times before.

**Comment by cmgmyr** [comment]
@xKairu I haven't taken the plunge into Spark yet, but I'm assuming a `team` is just a group of `users`? If so, when a user messages a team you could grab all of the team's users, then add them as participants on the new thread, no? Once they are participants all of the team's users will be notified. The only tricky thing is when a new user is added to a team, they won't see any previous threads (which I think is your question/issue).

@a-komarev I've been meaning to make an FAQ wiki page :)

**Comment by xKairu** [comment]
@cmgmyr If you're using Spark properly, then yeah that's all it is. I'm using a Team as sort of like an organization that users can follow/like (using rtconner/laravel-likeable), then the users joining the team would be the managers that can access the messaging.

I actually forked the package into my project and made the changes myself and it seems to be working fine at the moment, essentially just making the Participant polymorphic rather than strictly bound to a User. I can refactor it a bit and make a starting pull request if you'd like? I ended up stripping a lot of the helper functions out that I didn't need, so I'm not sure if it would even be any help.

**Comment by Gummibeer** [comment]
@cmgmyr even if a team ist just a collection of users, they can change over time - with polymorphic relations this is no problem, with your solution it is!
I can't/won't keep track of all join/leave actions in all related modules. So polymorphic is really a thing needed.

Other cases, in times of IoT and Co. it's possible that your car, fridge or whatever will send you something, these will be type of Car/Object/Device or something like this. And a step further it's slso possible that the fridge writes your tesla to go shopping by itself. So just some future examples snd I bet that there are lot more current one.
