### ISSUE TITLE
Call to undefined method Illuminate\Database\Query\Builder::newThreadsCount()

### ISSUE THREAD

**Issue by sujeetjaiswara** [cmgmyr/laravel-messenger#188]
Hello,

I have this error when I'm trying to display the count of messenger.

Can someone help me please ? :)

`ErrorException in Builder.php line 2123:
Call to undefined method Illuminate\Database\Query\Builder::newThreadsCount() 
(View: C:\xampp\htdocs\test1\resources\views\messenger\unread-count.blade.php) 
(View: C:\xampp\htdocs\test1\resources\views\messenger\unread-count.blade.php) 
(View: C:\xampp\htdocs\test1\resources\views\messenger\unread-count.blade.php) 
(View: C:\xampp\htdocs\test1\resources\views\messenger\unread-count.blade.php)`

**Comment by a-komarev** [comment]
Use search, please:
- #172
- #138 
- #93

**Comment by sujeetjaiswara** [comment]
yes, but already used #172, #138, #93 and still have bugs.
Call to undefined method Illuminate\Database\Query\Builder::newThreadsCount()

**Comment by a-komarev** [comment]
Can you show your user model then?

**Comment by sujeetjaiswara** [comment]
it's solved

**Comment by RudolfFussek** [comment]
What have you do? newThreadsCount() don't work for me....

**Comment by rtd62** [comment]
@sujeetjaiswara How were you able to solve this? I have come across the same [issue](https://github.com/cmgmyr/laravel-messenger/issues/226) here in Laravel 5.3.
