### ISSUE TITLE
Hardcode App\User

### ISSUE THREAD

**Issue by aios** [cmgmyr/laravel-messenger#189]
in Participant.php
in Models.php
in Message.php

Should use config value
v. 2.13

**Comment by a-komarev** [comment]
It's using model registry:

```php
public function user()
{
    return $this->belongsTo(Models::user(), 'user_id');
}
```

So, it could be overrided in config `'user_model' => App\User::class,`.

**Comment by a-komarev** [comment]
You can check [how it works](https://github.com/cmgmyr/laravel-messenger/blob/e8992e5d1f8617b00e0a9fcb182020366f3eb3c4/src/Cmgmyr/Messenger/Models/Models.php).
