### ISSUE TITLE
Issues with restricting users in chat room

### ISSUE THREAD

**Issue by goodnesskay** [cmgmyr/laravel-messenger#191]
Please can someone help? I am having issues with restricting users to only the thread they were included to. what I mean is that I want users to only see messages they were added as recipients.

**Comment by a-komarev** [comment]
@goodnesskay To see threads where users are participants you mean?

Here is how you can get only threads where user is participant:

```php
$threads = Thread::forUser($userId)->get();
```

And in thread show method you can just check if user is participant and able to see thread content:

```
$thread = Thread::findOrFail($id);
if (!$thread->hasParticipant($userId)) {
    abort(403);
}
```
