### ISSUE TITLE
QueryException in Messagable.php with DB Prefix

### ISSUE THREAD

**Issue by cmgmyr** [cmgmyr/laravel-messenger#193]
Refs #183 

DB prefix was not getting added into the raw select query

**Comment by cmgmyr** [comment]
@michaeltintiuc this should fix the issue. Can you update your app to use `dev-master` to double check on your side? This will be tagged shortly if it works.

**Comment by michaeltintiuc** [comment]
@cmgmyr Yep, this fixed it. Thanks a lot, I really appreciate it!
