### ISSUE TITLE
Incompatible trait for user model

### ISSUE THREAD

**Issue by TomHowardUK** [cmgmyr/laravel-messenger#195]
The trait included in the user model should be as follows (on Laravel 5.3 with Authentication):
`class User extends Authenticatable {
    use Messagable;
}`

**Comment by DeepBurner** [comment]
Can you try adding `use Cmgmyr\Messenger\Traits\Messagable;` at the start of your User.php file

**Comment by cmgmyr** [comment]
@TomHowardUK are you referring to what is in the readme file?

**Comment by TomHowardUK** [comment]
Yeah @cmgmyr
