### ISSUE TITLE
Class 'App\User' not found

### ISSUE THREAD

**Issue by pirmax** [cmgmyr/laravel-messenger#198]
**Class 'App\User' not found** in **mail/{id}**

My config file is:

```
<?php
return [
    'user_model' => App\User::class,
    'message_model' => Cmgmyr\Messenger\Models\Message::class,
    'participant_model' => Cmgmyr\Messenger\Models\Participant::class,
    'thread_model' => Cmgmyr\Messenger\Models\Thread::class,
    'messages_table' => null,
    'participants_table' => null,
    'threads_table' => null,
];
```

**Comment by pvdptje** [comment]
Are you 100% sure the User model is in the App folder?

**Comment by pirmax** [comment]
Yes, it is.

![image](https://cloud.githubusercontent.com/assets/1739235/22474650/c8be8bc2-e7dc-11e6-85d8-c07a5213e708.png)

**Comment by DeepBurner** [comment]
Did you alter the `MessengerServiceProvider.php` file in any way?

**Comment by pvdptje** [comment]
Could you paste the stacktrace as well?

**Comment by cmgmyr** [comment]
@pirmax have you run or seen any issues with `composer dumpautoload -o`?

**Comment by pirmax** [comment]
Problem solved, I deleted the line in config/app.php by mistake.
