### ISSUE TITLE
disable non registered user to comment

### ISSUE THREAD

**Issue by dincio** [cmgmyr/laravel-messenger#20]
hi how can i disable non registered user to post comment and access the messages?

**Comment by avlastenok** [comment]
This really has nothing to do with this package, the package should never implement something like that.
With laravel you have your Auth to use for things like that.
http://laravel.com/docs/5.0/authentication

**Comment by dincio** [comment]
@avlastenok but the modification to make it work between 2 user only is also not part of this package?

**Comment by avlastenok** [comment]
Actually it is this package delivers a good bunch of tools for you to use as you wish and yes you can make it work out of the box between two users only but that is your job to limit the users to that functionality.

**Comment by dincio** [comment]
@avlastenok thanks, is there any documentation available for this?

**Comment by cmgmyr** [comment]
@dincio please take a look at the authentication docs that @avlastenok posted as well as maybe signing up for something like [Laracasts](https://laracasts.com/). As @avlastenok stated, the tasks that you want to accomplish are supposed to be on the application level and not included in this package.
