### ISSUE TITLE
table prefix

### ISSUE THREAD

**Issue by interludic** [cmgmyr/laravel-messenger#201]
Hello,

i am attempting a pull request when i find the line has already been updated, 

in Messageble.php

public function threadsWithNewMessages()

$q->orWhere(Models::table('threads') . '.updated_at', '>', $this->getConnection()->raw(DB::getTablePrefix().Models::table('participants') . '.last_read'));

so how come my code i just installed is out of date?

H

**Comment by cmgmyr** [comment]
my guess is that you aren't running the latest `2.13.2` version. Can you check your `composer.lock` file?

**Comment by interludic** [comment]
"cmgmyr/messenger": "^2.13",

**Comment by cmgmyr** [comment]
@interludic my bad, this was in the `v2` branch, but not tagged. I think I was going to work on a few other things before tagging, but didn't get around to it.

I've tagged `2.13.3` to fix this, so running `composer update cmgmyr/messenger` should fix. If it doesn't, please let me know.

**Comment by interludic** [comment]
Chris dont be so hard on yourself mate your doing the best you can. Your only human ffs
