### ISSUE TITLE
Get rid of SoftDelete in Threads and Participants

### ISSUE THREAD

**Issue by sugo23** [cmgmyr/laravel-messenger#205]
How can I get rid of the SoftDelete in Threads and Participants?

In my case it does not make sense and I think if a user deletes something privat it really should be deleted physically...

**Comment by Promixius** [comment]
forceDelete();

**Comment by sugo23** [comment]
Well, it seems I have to rewrite many of the code (and then i am unable to upgrade if a newer version is release).

eg. a user leaves a thread:
```
$thread->removeParticipant(Sentinel::getUser()->id);
```

**Comment by sugo23** [comment]
Heres my quick and dirty workaround when a user leaves a thread:

````
    	$thread->removeParticipant(Sentinel::getUser()->id);

    	// Workaround:

    	Participant::where('deleted_at', '>', Carbon::create(2000, 1, 1, 0, 0, 0))->forceDelete();
    	
    	$participants = $thread->participantsUserIds();
    	
    	if (!count($participants))
    	{
    		$thread->messages()->delete();
    		$thread->forceDelete();
    	}
````

**Comment by Gummibeer** [comment]
@sugo23 to increase the overall speed of your app and decrease the amount of queries in one request I suggest to put the "clear" queries in a job.
This way you can dispatch this job if a user leaves a thread but don't have to do this in the request.

**Comment by cmgmyr** [comment]
@sugo23 it looks like your solution will work fine, but I'll second @Gummibeer's suggestion to run this in a separate job queue. I'd also take a look at TightenCo's [Quicksand](https://github.com/tightenco/quicksand), which might be able to help you out as well.
