### ISSUE TITLE
Deleting Threads

### ISSUE THREAD

**Issue by jenellej** [cmgmyr/laravel-messenger#208]
Hi, implemeting this in my project, how would users be able to delete threads? Should, for example, the recipient decide to delete the thread, then the creator would also no longer be able to see the thread?

**Comment by cmgmyr** [comment]
Hi, and thanks for using this package in your project! First, you don't really want to "delete" a thread. Participants have soft deletes enabled, so if a participant would like to remove themselves from a thread, you can just soft delete them.

If a new reply is made after some participants removed themselves, you have the option of using `$thread->activateAllParticipants()` to restore them to the thread (un soft delete).

You also might want to implement something that checks to see if there are threads with all of its participants are deleted. If found you can force delete the thread and all of its relationships (messages & participants)
