### ISSUE TITLE
keep the messages between two users in a single thread

### ISSUE THREAD

**Issue by dincio** [cmgmyr/laravel-messenger#21]
i have seen this on closed question 
{Yes, you can definitely do that.

In your MessagesController@index method, you'll have to use $threads = Thread::forUser($currentUserId); as shown in the example file. 
This will make sure that your users only see the threads that they are participating in.
In your MessagesController@show method you'll have to do a check in order to see if the current user is a participant in the thread that they are requesting.
 You can do this fairly easily - after line 55 add: $thread->getParticipantFromUser(Auth::id());
You'll have to create a different route for your create method that will include a user id to add as a participant. So maybe something like Route::get('create/{toUser}', ['as' => 'messages.create', 'uses' => 'MessagesController@create']);
 Then in your store method you'll just use the current user id and the toUser as the participants.}

i dont get this part 
"Then in your store method you'll just use the current user id and the toUser as the participants." 
how to do that?

**Comment by avlastenok** [comment]
I am sorry but looking at the last few "issues" you have created none of them are issues
and they draw a quite clear picture of your ability's, you really should start by learning how to use Laravel and maybe php in general there are plenty of tutorials and guides on the web, for laravel specific I would suggest laracasts.com

**Comment by cmgmyr** [comment]
Please see #15
