### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by HDVinnie** [cmgmyr/laravel-messenger#212]
Does this package have a option like the Mail option in LARAVEL?

`Mail::to($topicCreator->email)->send(new NewReply($user, $topic));`

**Comment by cmgmyr** [comment]
No, currently the package doesn't have anything like this built in. I've been planning the `v3` of the package and definitely want to include events and other options that developers can hook into. Pre-made mailables would be nice too. I'll make a note of this :)

**Comment by HDVinnie** [comment]
thanks
