### ISSUE TITLE
Get Participant Users in one call

### ISSUE THREAD

**Issue by kinnedev** [cmgmyr/laravel-messenger#215]
Hi!

Great Package! This is a question as you have deeper knowledge of this package. I am using this package with Vue and building out my api's. 

I currently have this to for a single message view: 

```
return Thread::with('messages')->with('participants')->get()->find($id);
```

Thats great, but I would like to also get the users collection from each participant in this call so I have everything I need. It gets a little tricky with the relationship, any advice?

Thank you!

**Comment by cmgmyr** [comment]
Hey @kinnedev, thanks for using the package and I'm glad you like it! This should get you *most* of the way

```php
return Thread::with(['messages', 'messages.user', 'participants'])->find($id);
```

So three things with this:

1. You don't need `get()` with `find()`. `find()` will do the `get()` part for you 🙂
2. You don't need multiple `with()` calls, just send an array
3. Using the "dot" syntax you are able to call sub relationships, and will also nest the relationship data.

So the output will look something like:
![screen shot 2017-03-20 at 1 30 09 pm](https://cloud.githubusercontent.com/assets/4693481/24113106/0f158ab6-0d72-11e7-9ce3-7f7449513389.png)

You can play around with this a bit, but I thought it would be helpful to have the user nested within their message and another section for participants that you can use for something else.

If you are building an API I'd recommend looking at [fractal](http://fractal.thephpleague.com/) to format your json responses and add additional information like totals, pagination, etc. There are also a few Laravel specific wrappers too.

I'm going to close this, but feel free to keep the conversation going if you want to. Hope this helped!

**Comment by kinnedev** [comment]
Man thank you! I just learned 3 new things!! 

I have always just chained withs. Super helpful. 

Thanks again!
