### ISSUE TITLE
Soft deletes for messages

### ISSUE THREAD

**Issue by zlorkovic** [cmgmyr/laravel-messenger#216]
Hi,

Great package!
As I could notice Threads and Participants use soft deletes. 
However, Message model doesn't use soft deletes.

Is there any particular reason you don't use it in on Message model?

It would be great to include soft deletes into Message model as if somebody needs to delete it completely, he can use forceDelete on model.

**Comment by zlorkovic** [comment]
@a-komarev Thank you. Yeah, I know that. This was just notice added as all other model have soft deletes and only messages doesn't have.

**Comment by a-komarev** [comment]
I think it's not done because of optimization reasons. We need @cmgmyr to join the discussion.

**Comment by cmgmyr** [comment]
@zlorkovic hey, and thanks for using the package!

Honestly, I can't remember if I had an initial reason for this, or it was a simple oversight. I see no reason to not include soft deletes for `messages` though. This might work well with some new changes in the future too.

I have this pretty much done right now, so I'll push the code shortly and tag a new version in a few days.
