### ISSUE TITLE
Get Latest With Initial Call

### ISSUE THREAD

**Issue by kinnedev** [cmgmyr/laravel-messenger#217]
Hey!

Just looking for a way to get the latest message in my initial call to get all the threads. 

Right now I am doing this: 

```
$threads = Thread::forUser($currentUserId)->with(['messages', 'creator', 'participants.user'])->latest('updated_at')->get();

```
That works great but returns all messages, how can I convert that to return just the latest message on each thread? 

Thank You!

**Comment by a-komarev** [comment]
@kinnedev It's not about this package. It's how Laravel Eloquent & Collection works. Just change `->get()` to `->first()`.

**Comment by a-komarev** [comment]
Ah... sorry that wouldn't work because you need all the threads related to user to has only one latest message. One of the quick solutions is a using of `groupBy`.

**Comment by kinnedev** [comment]
Oh true I could just do a groupBy and then in my Vue just grab the first one in the array. 

I am can do that for now. I will keep digging to see if I can create a better way. 

Thanks for the feedback.

**Comment by Gummibeer** [comment]
With default eloquent logic this isn't possible cause relations are cached on the object. So if you call `with('messages.last')` it will store tge query result on `$thread` if you later do `$thread->messages` this will return the wrong result.

The best thing I can imagine is a appended attribute `$thread->last_message` defined by `getLastMessageAttribute()` and accessed by `$threads->pluck('last_message')`.

If you don't need/want eloquent models you also can create a custom query directly on the database `DB::table('threads')->join('messages')` and do what you want.

**Comment by Gummibeer** [comment]
PS: if you need it for vue and want to be flexible, you can split it.

`ThreadController::getIndex` return just the list of threads and the participants.

`ThreadController::getLastMessage` returns the last message by thread id. with this you can simply update the last message for a thread every x seconds and you speed it up and are able to display a thread list without the messages without the overhead of useless queries.
