### ISSUE TITLE
Just curious, is laravel-messenger a good fit as a light-weight forum?

### ISSUE THREAD

**Issue by ziming** [cmgmyr/laravel-messenger#22]
Just curious, is laravel-messenger a good fit as a light-weight forum? Has anyone done it this way (customize it to a forum with basic categories) and how is it?

**Comment by cmgmyr** [comment]
I'm actually thinking about doing this in a personal project. I don't see why it wouldn't work for a basic forum once you extend it to add in categories. Could work out pretty nicely actually

**Comment by ziming** [comment]
Hmm. In terms of forum packages for Laravel, are there any good recommendations?
