### ISSUE TITLE
Get error when I create a new subject with participants

### ISSUE THREAD

**Issue by DoMoCo** [cmgmyr/laravel-messenger#221]
SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: 'on' for column 'user_id' at row 1 (SQL: insert into `participants` (`user_id`, `thread_id`, `updated_at`, `created_at`) values (on, 11, 2017-04-12 13:50:46, 2017-04-12 13:50:46))

**Comment by DoMoCo** [comment]
How to solve it.

My code is:
```
if (Input::has('recipients')) {
            $thread->addParticipant(Input::get('recipients'));
        }
```

**Comment by a-komarev** [comment]
@DoMoCo can you show content of the Input::get('recipients')?

```
dd(Input::get('recipients'));
```

**Comment by rtd62** [comment]
Did you install Carbon via composer? As well, in the SQL database, change those values to `timestamp` instead of `integer`.

**Comment by DoMoCo** [comment]
Thanks,I have solved it.

**Comment by basmaezz** [comment]
how u solve it ?????????
