### ISSUE TITLE
How we use this with Socket IO 

### ISSUE THREAD

**Issue by cent040** [cmgmyr/laravel-messenger#222]
i wan to use this with socket IO. Like.. 

User is typing ..... 

other end user get message instantly when pushed by Admin or user. 

thanks

**Comment by cmgmyr** [comment]
This is more of a front-end question which doesn't get handled within the current code. The implementation would be up to you.

I have a (really old) [demo](https://github.com/cmgmyr/laravel-messenger-pusher-demo) with [Pusher](https://pusher.com/) that you can take a look at, but I didn't implement a typing feature. Pusher has also put out some recent [blog posts](https://blog.pusher.com/build-whos-typing-feature-laravel-pusher/) on the topic that you should check out. I haven't used Socket IO, but I'm sure the two are fairly similar.

I hope that helps! 🙂
