### ISSUE TITLE
Have system send messages - how?

### ISSUE THREAD

**Issue by nexxai** [cmgmyr/laravel-messenger#224]
I read the other issue threads about using the built in Laravel notifications system, but that won't really work in my use case.  I need the system to send a person a message to their messenger inbox when a certain route is triggered, but I'm not sure how I'd go about that.  I'm pretty new to PHP (and programming in general) so I apologize if this is a dumb question, but I'm not sure *how* to call the MessagesController@store function from anywhere other than a route.

Can someone give me a quick pointer?  Thanks!

**Comment by a-komarev** [comment]
@nexxai Controllers are for processing user requests, not for internal application calls. If you will call controller methods by the robot you will face an issues that session is not started, then you will need to populate input request collection by yourself.
The best way in my point of view is creating a dedicated Service class which will do the job for you. And then you'll have 2 places where your Service class is using.
- For internal usage: anywhere in your application (in exceptions, controllers, services, routes, listeners or any other classes).
- For users: in `MessagesController@store`.

**Comment by nexxai** [comment]
I've never created a service class before - looking at the Laravel docs, are you referring to a "Service Provider" or "Service Container"?

**Comment by a-komarev** [comment]
@nexxai It's not about Laravel. It's just a class which encapsulate some logic and could be used in multiple parts of the application. One of the [examples of Service class](https://github.com/cybercog/laravel-likeable/blob/master/src/Services/LikeableService.php) from one of my packages.

**Comment by nexxai** [comment]
I guess there's no chance of a service container feature being added to this package, is there?  I've tried wrapping my head around how to do something like that and every single time I get lost about 3 sentences in.

**Comment by a-komarev** [comment]
@nexxai Create class for example `MessengerService` and implement methods which will do the job. Then you will be able to initialize them anywhere you want and call methods which required in particular case. Start from one single action: `sendMessageTo($recipientUserId, $senderUserId)`. And then add methods which will be required.

I have service classes for this package in all projects which are using it. Each project has it's own service class because of different application logic and I can't give you completed solution out of the box.

**Comment by cmgmyr** [comment]
This is actually my main plan for `v3`. Instead of just calling the raw models all of the time, you'll interact with the messenger service class.

I'm going to close this for now, but if you have any questions, feel free to add them here.

ref #51
