### ISSUE TITLE
Pagination for messages and/or threads

### ISSUE THREAD

**Issue by MrMooky** [cmgmyr/laravel-messenger#225]
Hello again. I tried to implement a pager for the messages (->paginate(10)) but that does not work. Is there any way to limit the messages output within the show-action?

**Comment by a-komarev** [comment]
@MrMooky Could you show more detailed code block?

**Comment by MrMooky** [comment]
@a-komarev I have no working code, thus I'm asking. The following code does not support a pager:

That's the way a thread is called within the show-action, that automatically fetches the messages the thread is containing:

`$thread = Thread::findOrFail($id);`

The code should be something like this:
`$thread = DB::table('threads')->messages->simplePaginate(10);`

But that does not work.

**Comment by a-komarev** [comment]
```php
$thread = Thread::findOrFail($id);
$thread->messages()->simplePaginate(10);
```
Wouldn't this work?

**Comment by MrMooky** [comment]
I've tried the code you suggested. Did not throw an error instantly... but when adding the needed code to my blade file, I got

> Method links does not exist.

That's my current blade code, as provided [here](https://laravel.com/docs/5.4/pagination#displaying-pagination-results).

```
@each('messenger.partials.messages', $thread->messages, 'message')
{{ $thread->messages->links() }}
```

**Comment by a-komarev** [comment]
Read about Laravel pagination in documentation, please.

```php
$messages = $thread->messages()->paginate(10);
```

And use `$messages` collection in your views instead of fetching messages from thread again.

**Comment by MrMooky** [comment]
Ok, that worked. I was just using the example code that was provided [here](https://github.com/cmgmyr/laravel-messenger/blob/master/src/Cmgmyr/Messenger/examples/MessagesController.php) and figured it should work with this.

Thank you very much.
