### ISSUE TITLE
ErrorException in Builder.php line 2450 (for unread-count.blade.php)

### ISSUE THREAD

**Issue by rtd62** [cmgmyr/laravel-messenger#226]
I got an error with the `newThreadsCount()` method in `unread-count.blade.php`. Working in Laravel 5.3 -- full error below:

```Call to undefined method Illuminate\Database\Query\Builder::newThreadsCount() (View: /var/www/html/test-site/resources/views/messenger/unread-count.blade.php)```

**Comment by rtd62** [comment]
The user model also has `use Messagable;` - as stated of being the answer from previous issues.

**Comment by a-komarev** [comment]
@rtd62 the strange thing that `Auth::user()` returns Query Builder instance instead of Currently authenticated user. Issue still in place?

**Comment by rtd62** [comment]
@a-komarev 
The issue is still in place. I didn't edit the `unread-count.blade.php` file but I did alter the authentication from `php artisan make:auth` to add a `username` field, which is another issue I have altogether (with username info not saving to MYSQL database upon registration).

**Comment by a-komarev** [comment]
@rtd62 Issues with username field are related to [RegisterController](https://github.com/laravel/laravel/blob/master/app/Http/Controllers/Auth/RegisterController.php#L65-L68) and don't forget to update validation rules in `validate` method above too.

Try to dump authenticated user at the beginning of the `unread-count.blade.php`:
```php
{{ dd(Auth::user()) }}
```
This method should return `App\User` model instance.

And one more debug could be useful:
{{ dd(method_exists(Auth::user(), 'newThreadsCount')) }}

**Comment by rtd62** [comment]
@a-komarev 
I ran `{{ dd(method_exists(Auth::user(), 'newThreadsCount')) }}` and this
[screenshot](https://www.dropbox.com/s/ekrooq0mtgr9o2a/Screenshot%202017-05-01%2017.11.47.png?dl=0) is what I got. I'm rather new to Laravel and not sure what this means.

**Comment by rtd62** [comment]
@a-komarev 
When I ran `{{ dd(Auth::user()) }}`, it did dump the user I was "logged in" as - but the fillable array is missing the extra stuff I put in the `user` model.

**Comment by a-komarev** [comment]
Thats really strange. If you've used and imported `Messagable` trait in user model - `newThreadsCount` should exists in user model because [it's in a trait](https://github.com/cmgmyr/laravel-messenger/blob/master/src/Cmgmyr/Messenger/Traits/Messagable.php#L58).

**Comment by a-komarev** [comment]
What PHP version are you using? Traits were added in PHP 5.4.

**Comment by rtd62** [comment]
My PHP version is `7.0.15` - so I'm good there, even for the upcoming Laravel 5.5 😃

**Comment by a-komarev** [comment]
Your user model located as default in `/app/User.php`?

**Comment by rtd62** [comment]
@a-komarev Yessir, default as can be lol, I'll provide it below (forgive all the other fluff lol):
```
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Laravel\Cashier\Billable;
use Laravel\Scout\Searchable;
// use Fenos\Notifynder\Traits\NotifableLaravel53 as NotifableTrait; // for Laravel 5.3+
use Cmgmyr\Messenger\Traits\Messagable;
use Illuminate\Auth\UserTrait;
use Illuminate\Auth\UserInterface;
use Illuminate\Auth\Reminders\RemindableTrait;
use Illuminate\Auth\Reminders\RemindableInterface;

class user extends Model implements Authenticatable, UserInterface, RemindableInterface
{
    use Billable;
	use Searchable;
	use UserTrait, RemindableTrait;
	// use NotifableTrait;
	use Messagable;
	
	protected $fillable = ['name', 'email', 'password', 'slug', 'gender', 'avatar'];
	
	protected $hidden = ['password', 'remember_token'];
	
	public function profile()
	{
		return $this->hasOne('App\Profile');
	}
	
	public function getName()
	{
		return $this->name;
	}
	
	// Logic for User Connections
	public function connections()
	{
		return $this->belongsToMany('User', 'connections_users', 'user_id', 'connection_id');
	}
	
	// Add Connection
	public function addConnection(User $user)
	{
		$this->connections()->attach($user->id);
	}
	
	// Remove Connection
	public function removeConnection(User $user)
	{
		$this->connections()->detach($user->id);
	}
	
	// Algolia Search 
	public function searchableAs()
	{
		return 'user_index';
	}
	
	public function toSearchableArray()
	{
		$array = $this->toArray();
		
		// Customize array...
		
		return $array;
	}
}
```

**Comment by a-komarev** [comment]
Why your `User` class is lowercase `class user extends Model `?

And for your info you can simplify your `use`:
```
use Billable,
    Searchable,
    UserTrait,
    RemindableTrait,
    // NotifableTrait,
    Messagable;
```

**Comment by rtd62** [comment]
I was going to circle back around that in development to change it from `user` to `User`, but even with me changing it now, the error still occurs.

**Comment by a-komarev** [comment]
Hmmm... maybe your app not using this model as default for authentication? Could you provide `/config/auth.php` file content?

**Comment by rtd62** [comment]
Sure! Here it is below:
```
<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Authentication Defaults
    |--------------------------------------------------------------------------
    |
    | This option controls the default authentication "guard" and password
    | reset options for your application. You may change these defaults
    | as required, but they're a perfect start for most applications.
    |
    */

    'defaults' => [
        'guard' => 'web',
        'passwords' => 'users',
    ],

    /*
    |--------------------------------------------------------------------------
    | Authentication Guards
    |--------------------------------------------------------------------------
    |
    | Next, you may define every authentication guard for your application.
    | Of course, a great default configuration has been defined for you
    | here which uses session storage and the Eloquent user provider.
    |
    | All authentication drivers have a user provider. This defines how the
    | users are actually retrieved out of your database or other storage
    | mechanisms used by this application to persist your user's data.
    |
    | Supported: "session", "token"
    |
    */

    'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],

        'api' => [
            'driver' => 'passport',
            'provider' => 'users',
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | User Providers
    |--------------------------------------------------------------------------
    |
    | All authentication drivers have a user provider. This defines how the
    | users are actually retrieved out of your database or other storage
    | mechanisms used by this application to persist your user's data.
    |
    | If you have multiple user tables or models you may configure multiple
    | sources which represent each model / table. These sources may then
    | be assigned to any extra authentication guards you have defined.
    |
    | Supported: "database", "eloquent"
    |
    */

    'providers' => [
        'users' => [
            'driver' => 'eloquent',
            'model' => App\User::class,
        ],

        // 'users' => [
        //     'driver' => 'database',
        //     'table' => 'users',
        // ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Resetting Passwords
    |--------------------------------------------------------------------------
    |
    | You may specify multiple password reset configurations if you have more
    | than one user table or model in the application and you want to have
    | separate password reset settings based on the specific user types.
    |
    | The expire time is the number of minutes that the reset token should be
    | considered valid. This security feature keeps tokens short-lived so
    | they have less time to be guessed. You may change this as needed.
    |
    */

    'passwords' => [
        'users' => [
            'provider' => 'users',
            'table' => 'password_resets',
            'expire' => 60,
        ],
    ],

];
```

**Comment by rtd62** [comment]
This is what came out of the box for Laravel `5.3.31` - but I don't see any confliction here

**Comment by a-komarev** [comment]
Yeah... I can't see any issues here. The last thing I can advice to you - try to remove other traits, maybe there are some hidden magic there? At last - try to create fresh install in separate folder and try to use messenger package there. If it will work - step by step find whats wrong with your main app.

**Comment by rtd62** [comment]
I tried removing other traits -- looks like I'll have to try this on a fresh install. Maybe I missed a step. Thank you for all the help! I'll report back when I find the issue.

**Comment by cmgmyr** [comment]
@rtd62 I don't see anything else from a quick glance that @a-komarev didn't cover. I'll investigate more tomorrow morning

**Comment by rtd62** [comment]
Much appreciated @cmgmyr and @a-komarev! I might just have to do run this on a clean install and see where I messed up. I likely missed a step or misconfigured something.

**Comment by cmgmyr** [comment]
@rtd62 a few things to double check with you about:

1. Can you log in successfully to your app?
2. When you see this error are you logged in or not?

You might want to add a check for the count if you are having the `Messsages` link be available for guests (not logged in) and authenticated users. Something like this would work in `unread-count.blade.php`

```php
@if(Auth::user())
    <?php $count = Auth::user()->newThreadsCount(); ?>
    @if($count > 0)
        <span class="label label-danger">{{ $count }}</span>
    @endif
@endif
```
...or any other way you wanted to handle it. In the main layout file would work to.

**Comment by rtd62** [comment]
@cmgmyr 
I can log in successfully, and I see the errors when I am logged in. I just tried that new code you supplied, but I still came up with the same issue. I think my database is just screwed up. The problem is I am working on a project where I can't use `artisan` to flush it out because it's key data brought in from another app. I am going to try this again on a separate install.

**Comment by cmgmyr** [comment]
hrm. Ok keep us posted and we'll do our best to help out 🙂

**Comment by Xationch** [comment]
I got the same issue but after your last message I realise that I was not logged ...

**Comment by rtd62** [comment]
@cmgmyr @Xationch @a-komarev 
So after a lot of research, all I had to do was run `php artisan optimize`! I uninstalled a dependency I wasn't using and it ran the command and lone behold everything worked like a charm!

**Comment by a-komarev** [comment]
@rtd62 Thanks for sharing the solution!

**Comment by cmgmyr** [comment]
Thanks for the update @rtd62!

**Comment by rtd62** [comment]
No problem! Loved the support from you guys, by the way! Can't wait to see this continue being developed.

**Comment by pitter1104** [comment]
Hello, I have the same problem, is there a solution?
"Method Illuminate\Database\Query\Builder::newThreadsCount does not exist. (View: /htdocs/testmessenger/resources/views/messenger/unread-count.blade.php) 

Regards
Peter
