### ISSUE TITLE
Thread author?

### ISSUE THREAD

**Issue by rdpascua** [cmgmyr/laravel-messenger#227]
I assume the first participant will be the thread author? It would be great if we can have this function. I would be happy to send a PR for this function.

```php
Thread::getAuthor();
```

**Comment by rdpascua** [comment]
Oh there's already a `creator()` function in the thread. carry-on.

**Comment by johannesschobel** [comment]
hey @rdpascua ,
be careful when calling the `creator()` method on an *empty* thread.. this might fail.. 
Cheers
