### ISSUE TITLE
Creator throws Exception

### ISSUE THREAD

**Issue by johannesschobel** [cmgmyr/laravel-messenger#229]
Hey @cmgmyr ,

great work on this awesome piece of code - I really like it.
I recently stumbled upon an issue - may somebody can reproduce it!?

If i create an (empty) Thread (i.e., a thread that does not have any message yet) and somebody calls `$thread->creator()` it fails with an Exception (`"Trying to get property of non-object"`).

May you can fix this issue?
The respective method within the `Thread` class has to be replaced with:

``` php
    /**
     * Returns the user object that created the thread.
     *
     * @return mixed|null
     */
    public function creator()
    {
        if($this->messages()->count() === 0) {
            return null;
        }
        return $this->messages()->withTrashed()->oldest()->first()->user;
    }
```

Cheers from Germany,
Johannes

**Comment by a-komarev** [comment]
Hello @johannesschobel!

Nice catch! I've added PR #231 for case you've provided, but optimized it a bit.

**Comment by a-komarev** [comment]
At this moment creator is the user who left first message and not the user who actually was a creator of the thread. Without changing database structure there is the only way to get creator is check the owner of the first message.

**Comment by cmgmyr** [comment]
@johannesschobel thanks for using the package, I'm glad you like it!

@a-komarev's PR has been merged into `master`, so you can reference that in your `composer.json` file if you'd like until a new release is tagged.

**Comment by johannesschobel** [comment]
Hey @cmgmyr , thanks for merging the PR.. any chance you can tag it as a new minor / hotfix version?
Thanks a lot for your work and effort..
Cheers, Johannes

**Comment by cmgmyr** [comment]
Tagged it yesterday afternoon actually :) 2.14.1

**Comment by johannesschobel** [comment]
sorry, my bad ;) thanks a lot
