### ISSUE TITLE
Soft deleted Users = Trying to get property of non-object exceptions

### ISSUE THREAD

**Issue by opheliadesign** [cmgmyr/laravel-messenger#23]
Greetings,

First, love this project - thanks for making it! I did run into a huge roadblock, though. A site I am developing performs soft deletes on users so that their activity on the site is still visible after their login privileges have been revoked (using withTrashed()). I am using laravel-messenger as an internal alternative to email, so I want users to be able to still view messages sent to them by "deleted" users.

I am trying to go through the model configuration to tackle the soft-delete issues, it would be really helpful to have this capability ready to go out of the box.

Thanks again!

**Comment by opheliadesign** [comment]
I finally got it all working, I pushed the changed models to https://github.com/opheliadesign/laravel-messenger-models. Sorry, not sure how the whole pull request thing works, bit of a Github novice ;)

**Comment by cmgmyr** [comment]
Hi @opheliadesign, I'm glad you like the project and you've been implementing it! I don't think adding the soft-deletes into the package is the best course of action (at least at this point). This would force all users to have them turned on in their model and the additional column in their databases. I think it would be better for you (and others) to extend the models you need to and overwrite the relationship methods to take advantage of the soft-deletes. That way you can still get the latest updates and your relationships/soft-deletes will still be in tact. Make sense?
