### ISSUE TITLE
private messaging system with attached files

### ISSUE THREAD

**Issue by Rostom22** [cmgmyr/laravel-messenger#230]
Hi, i looked into the exemple of the package but i don't know how to implement it to make a private messaging system where users can send private message (with attached files) to one or multiple users ? thanks for any help.

**Comment by a-komarev** [comment]
This question were raised earlier #162

**Comment by Rostom22** [comment]
Thanks for that what about the private message to one or multiple users ?

**Comment by a-komarev** [comment]
This package designed to provide you maximum freedom of implementing private\public threads logic by yourself. If you need  to make all the threads private - just hide them from users and check the ability to join the thread in your controllers to prevent hijacking :}

Question about one-to-one messaging was raised a lot of times. Just use search by words: `private message` or `one-to-one`.
In short: it's completely up to you to restrict users to join threads where more than 2 participants exists.

**Comment by Rostom22** [comment]
I've seen the questions but i didn't understand the answers, i'll search again. Thanks.

**Comment by Rostom22** [comment]
I managed to make the thread between 2 participant and now i'd like to know how to implement delete message or thread for a user and keep it for the other user ? thanks !

**Comment by cmgmyr** [comment]
The `Participants` model has soft deletes enabled, so you can utilize that if you'd like. You also have the choice of [reactivating all participants](https://github.com/cmgmyr/laravel-messenger/blob/da569aa031136005966bbac7cd693e2f84a06d42/src/Cmgmyr/Messenger/examples/MessagesController.php#L133) on new reply, or not.

**Comment by Rostom22** [comment]
how to use that ? i don't need reactivation in my application, juste show thread between 2 users in their inbox and if a user delete his message or a thread it's just in his inbox. sorry for my bad english.

**Comment by cmgmyr** [comment]
You can use `$thread->removeParticipant(Auth::id());` which will soft delete the participant record for the current user. This might look like:

```php
Route::delete('{id}/destroy', ['as' => 'messages.destroy', 'uses' => 'MessagesController@destroy']);
```

```php
public function destroy($id)
{
    try {
        $thread = Thread::findOrFail($id);
    } catch (ModelNotFoundException $e) {
        Session::flash('error_message', 'The thread with ID: ' . $id . ' was not found.');

        return redirect('messages');
    }

    $thread->removeParticipant(Auth::id());

    return redirect('messages');
}
```

*Note*: You'll want to make sure the current user has access to the thread that they're trying to delete themselves from especially if you are creating a private message system.

I'm going to close this as an issue for now, but feel free to update it if you have any other questions.

**Comment by Rostom22** [comment]
I used what you said and it's worked the message is deleted from the inbox of the users who choose to delet and still visible for the other user but when the other user send another message in the thread it's appear again in the inbox with the previous messages, any idea how to fix this ? thanks !

**Comment by cmgmyr** [comment]
@Rostom22 are you using the example controller? If so, you'll want to remove [this line](https://github.com/cmgmyr/laravel-messenger/blob/a84169c74852fd4ea3fcf785d9e26e2f437b6880/src/Cmgmyr/Messenger/examples/MessagesController.php#L133) if you don't want to reactivate participants on reply

**Comment by Rostom22** [comment]
Perfect ! it's working. thank you so much for your amazing package and your help !
