### ISSUE TITLE
Call to a member function newThreadsCount() on null

### ISSUE THREAD

**Issue by pengjinning** [cmgmyr/laravel-messenger#232]
unread-count.blade.php
error for unlogined visitor:
Call to a member function newThreadsCount() on null

so I think should and auth:check, just like this:

<img width="498" alt="qq20170513-010330 2x" src="https://cloud.githubusercontent.com/assets/1288209/26008594/08365fce-3778-11e7-8f23-793b5e99bfd9.png">

**Comment by Oxicode** [comment]
And now in 2023 this same bug continues,
