### ISSUE TITLE
How get deleted/archived messages in list ?

### ISSUE THREAD

**Issue by pirmax** [cmgmyr/laravel-messenger#233]
Hi,

How get deleted/archived messages in list ?

I want to make a page to list the deleted and archived messages and I want too make another page to list the unread messages only.

Thanks.

**Comment by cmgmyr** [comment]
Hey @pirmax,
All of the models have the [soft deletes](https://laravel.com/docs/5.4/eloquent#soft-deleting) trait on them, so you can use `onlyTrashed()` to get the deleted/archived ones. Calling the models without `onlyTrashed()` will return the active models.
