### ISSUE TITLE
How to send message to all users and attach file?

### ISSUE THREAD

**Issue by Mioleris** [cmgmyr/laravel-messenger#234]
Hi, I want to send message to all user as main admin. But there is about 20k users so every time when I want to send message to all users it adds 20k records in DB every time. Someone is using like this or there is other way ?

And how about attachments in message ? Should I create attachments and messages_attachments tables to manage message attachments by my self?

**Comment by a-komarev** [comment]
Hello, @Mioleris!
I'm not sure that this package is good choice for announcements. Especially if you are not planning to receive answers from all 20k users. For such a things use standard [Laravel Notifications](https://laravel.com/docs/master/notifications).

Accordingly to attachments, yes you need to implement this feature by yourself. This package provide only base text message functionality: #162

**Comment by cmgmyr** [comment]
@a-komarev - hmm, I believe the native notifications will do the same thing (using the DB option) - unless I'm missing something?

@Mioleris - do you need the users to reply to the message/notification? If not, maybe you can get away with having site-wide notifications (1 record) with an optional attachment (1 record), and have an additional table for read/unread statuses (20k records).

**Comment by a-komarev** [comment]
@cmgmyr You are right. It will create the same thing, but it wouldn't create Thread for each notification, it wouldn't add 2 participants to it. And if you need just to send announcements and don't need to receive any feedback in the chat - using messenger for it is redundantly in my point of view.

**Comment by cmgmyr** [comment]
@a-komarev agreed :)

**Comment by Mioleris** [comment]
Thanks guys for explanation :) I think I will stick with second option as @cmgmyr commented because I don't need to receive replies from users :)

**Comment by a-komarev** [comment]
@Mioleris Yep, that's seems to be the best approach.
