### ISSUE TITLE
LatestMessage attribute not available

### ISSUE THREAD

**Issue by longestdrive** [cmgmyr/laravel-messenger#235]
Hi

I've been using this package for a while and recently updated. I have an issue with the `latestMessage ` attribute in the threads model.

On my development machine It works perfectly and can access `latestMessage`. This uses Php 7 (laravel homestead). However on my live server (php 5.6) it only returns null values.

I've established that I need to add the attribute to the `$appends` array to the model for it to work correctly - but the `Threads` model is in the package so will get overwritten next update.

Is this a bug or something to do with my set ups?

Thanks

**Comment by cmgmyr** [comment]
Hey @longestdrive,
Can you try updating your references from `$thread->latestMessage` to `$thread->latest_message` and see if that fixes it?

What version of Laravel are you on?
