### ISSUE TITLE
Column messages.deleted_at not found

### ISSUE THREAD

**Issue by chizzycrusty** [cmgmyr/laravel-messenger#236]
Hi, I'm having trouble accessing the list of threads as I get this error:

> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'messages.deleted_at' in 'where clause'

It works well on local, but I can't access it on my live server.

**Comment by a-komarev** [comment]
@chizzycrusty try to call `artisan migrate`. If no migrations were found - make `vendor:publish` from documentation first. There were changes in messages table and there should be migration for it.

**Comment by chizzycrusty** [comment]
Thank you ! I updated the package but not the migration.
