### ISSUE TITLE
which $query is to be passed in params in `scopeForUser` function in Thread model 

### ISSUE THREAD

**Issue by ankitjain28may** [cmgmyr/laravel-messenger#238]

**Comment by Gummibeer** [comment]
You don't have to pass anything - call it without the `scope` and with first letter lower case `forUser` and just the params after the `$query` it's one of the magic things in Laravel/Eloquent.
https://laravel.com/docs/5.4/eloquent#local-scopes

**Comment by ankitjain28may** [comment]
Ohkk Great, Its working as expected, Thanks !!
