### ISSUE TITLE
Read(seen) status for every message

### ISSUE THREAD

**Issue by nikolaynesov** [cmgmyr/laravel-messenger#241]
From what I understand, currently the package only allows to set read status for the whole thread in participants table.

How about to have the status for each message? Considering that the amount of recipients is dynamic - we can have 2 or 22, then we may need an additional table for that read status.
Does it make sense to you? Looks like it's the way modern messengers like Viber, Whatsapp and Telegram work. 

Thank you for this great package ;)

**Comment by a-komarev** [comment]
@nikolaynesov at this moment you could quickly say before what time all messages are read by the participant. Modern messengers possibly doing the same thing, but additionally they have table where exact timestamps are storing:
1) When message was sent to server
2) When message received by the server
3) When recipient was online and received the message
4) When recipient has opened message

My suggestion is keep current implementation and make customizable option to turn on detailed read states and keep them in separate table.

**Comment by nikolaynesov** [comment]
@a-komarev you are probably right, thank you. I left this as it is for now.
