### ISSUE TITLE
newThreadsCount vs old newMessagesCount in Messagable trait

### ISSUE THREAD

**Issue by nikolaynesov** [cmgmyr/laravel-messenger#242]
Why did you replace newMessagesCount with newThreadsCount in Messagable trait? So now to count new messages in all threads I need to implement my own method right? how about to have both in the package?

**Comment by nikolaynesov** [comment]
Thanks to this https://github.com/cmgmyr/laravel-messenger/issues/109
I found that the method was working wrong previously. Now we have `userUnreadMessages($user_id)` or `userUnreadMessagesCount($user_id)` in Thread Model. But to me it looks more logical to put that into the Messagable trait because to count ALL unread messages for user, not only related to specific thread. It's a common case when you need to display some badge in app navigation with total count of unread messages.

**Comment by cmgmyr** [comment]
yes, I agree there are a handful of `user` type methods that would be better suited on the trait. I'll take a look at moving them soon

**Comment by nikolaynesov** [comment]
Submitted a pull request to add this functionality https://github.com/cmgmyr/laravel-messenger/pull/245
