### ISSUE TITLE
User Model have to be in auth config?

### ISSUE THREAD

**Issue by BlueTeck** [cmgmyr/laravel-messenger#244]
Hi,
thanks for this package. Recently I want to change the "user" model in the config.

https://github.com/cmgmyr/laravel-messenger/blob/master/src/config/config.php

But it was not possible for me, because the serviceprovider checks the auth config. By my new model is not in there.

```php
private function setUserModel()
    {
        $config = $this->app->make('config');

        $model = $config->get('auth.providers.users.model', function () use ($config) {
            return $config->get('auth.model', $config->get('messenger.user_model'));
        });

        Models::setUserModel($model);

        Models::setTables([
            'users' => (new $model)->getTable(),
        ]);
    }
```

Is there a way to override the user model to a model that is not auth relevant, without overriding the serviceprovider (which is my current solution)?

```php
Models::setUserModel($config->get('messenger.user_model', \App\User::class));
```

Thanks for any answers or ideas

**Comment by a-komarev** [comment]
Hello, @BlueTeck!
You could call `\Cmgmyr\Messenger\Models\Models::setUserModel($yourCustomUserModel);` in default Laravel `AppServiceProvider` because it will be loaded after the package service providers it should overwrite the value.

**Comment by a-komarev** [comment]
It's checking for config key `auth.providers.users.model` because it's default place where Laravel keeps User model reference. If it's not found package trying to fallback to old Laravel versions config `auth.model` And at the end it's looking at the `messenger.user_model` config key.

**Comment by a-komarev** [comment]
Now I see that it's better to use `messenger.user_model` first of all, then fallback to `auth.providers.users.model`. But it's a breaking change, and shouldn't be introduced as minor release.

**Comment by BlueTeck** [comment]
Thanks for your reply, thats what I'am doing at the moment. Your idea regarding switching the order, sounds good, but I understand that this is a breaking change. So I will keep the override.

**Comment by a-komarev** [comment]
Why don't you define User model in `auth.providers.users.model` Laravel config?

**Comment by BlueTeck** [comment]
Because I have a normal User (for login) and a GameUser (which is a "user-instance" for every game). So one user could have many GameUser. And the GameUser should be used for the messages. Maybe a little bit confusing without having the whole data model and context. ;)

**Comment by a-komarev** [comment]
No, that make sense. GameUser == Hero :}
