### ISSUE TITLE
getParticipantFromUser Not working

### ISSUE THREAD

**Issue by MortezaFathi** [cmgmyr/laravel-messenger#246]
Hi,getParticipantFromUser() creates the following query and cause any method that uses this method to not work
`select * from participants where participants.deleted_at is null and participants.thread_id is null and participants.thread_id is not null and user_id = 2 limit 1`

**Comment by cmgmyr** [comment]
Can you share the code that you're working with? Is the thread that you are trying to access available in the DB?
