### ISSUE TITLE
Laravel 5.5 compatible

### ISSUE THREAD

**Issue by nfunwigabga** [cmgmyr/laravel-messenger#258]
Is this package compatible with L5.5?

**Comment by cmgmyr** [comment]
Yes, the `v2` branch will work in 5.5, but you'll still need to add the service provider. `dev-master` has the new service provider discovery option for composer. The master branch is pretty much ready to be tagged but just haven't done it yet 🙂

**Comment by cmgmyr** [comment]
`2.15` tagged w/ auto-discovery (among other things)
