### ISSUE TITLE
Show current user's messages only and Unread count issue

### ISSUE THREAD

**Issue by jmarietinio** [cmgmyr/laravel-messenger#259]
Hi. I just implemented this package to my project and I want to know how to display messages meant for the current logged in user only. Thank you so much

For example, logged in user is Cherry Love Pasumala. The first thread is the one she didn't participate in but it shows on the page.

Also the Notification or the Unread count is 1 even when there's no unread thread

![ff](https://user-images.githubusercontent.com/19433640/31264702-65435792-aa9d-11e7-96f2-bdc7f6a19faa.png)

**Comment by cmgmyr** [comment]
Which method did you implement to load the user's threads? [This one](https://github.com/cmgmyr/laravel-messenger/blob/master/examples/MessagesController.php#L28) should work. Can you also double check that you are loading the correct user id into the [count badge](https://github.com/cmgmyr/laravel-messenger/blob/master/examples/views/messenger/unread-count.blade.php#L1)?

**Comment by jmarietinio** [comment]
When I create new message to the same person, this is how it displays the messages. Is there a way to compress this into one thread only?


![ff](https://user-images.githubusercontent.com/19433640/31279483-d20ffcf2-aadb-11e7-932c-4c0800f9d582.png)

**Comment by cmgmyr** [comment]
There is no way to combine threads directly in the package, you'd have to do that directly through the DB, or create your own function to do that. 

I _think_ what you're looking to do is grab the thread that matches the given participants? If that is the case you can use the "between" scope, but beware that there is a small bug as referenced in the PR [here](https://github.com/cmgmyr/laravel-messenger/pull/210/files), but you could also do this manually with something like [this](https://github.com/cmgmyr/laravel-messenger/issues/265).
