### ISSUE TITLE
Real-Time or nah?

### ISSUE THREAD

**Issue by louiskareem** [cmgmyr/laravel-messenger#260]
Not really an issue, but how do I make this app real-time without having to refresh the page to get updates?

I'm new to laravel, have some patience with me. Lol

**Comment by Gummibeer** [comment]
Some already open issues: #197 #16 #58 
In addition to these, I don't know which version you use but Laravel supports PubSub https://laravel.com/docs/5.5/redis#pubsub

But you also can use sockets or any already existant service that handles real-time communication between back- and frontend. But this package doesn't do anything related to this. This is just a package that handles the data storage.

**Comment by louiskareem** [comment]
Thanks!

**Comment by ronlinet** [comment]
> Some already open issues: #197 #16 #58 In addition to these, I don't know which version you use but Laravel supports PubSub https://laravel.com/docs/5.5/redis#pubsub
> 
> But you also can use sockets or any already existant service that handles real-time communication between back- and frontend. But this package doesn't do anything related to this. This is just a package that handles the data storage.

For those who will land here while googling a realtime messaging solution [Redis pubsub](https://laravel.com/docs/6.x/redis#pubsub) does only the server side job. 

If you want to use this packages for real time communication you will need Pusher, Firestore or Websocket wrapper to push the content to users.
