### ISSUE TITLE
QUESTION - Recommend me how to make sample code realtime.

### ISSUE THREAD

**Issue by imonoid** [cmgmyr/laravel-messenger#263]
Nice project by the way.  I am using this to add chat feature to a project I am working on.  I would like to ask for advice what's need to make the sample code work in realtime.  Pusher/Echo seem to have been recommended, but for the moment, I would want to know if there is some way to implement it without having to study or become familiar with Pusher.

Is the code below good?  I am using it for the realtime feature, but not really sure if its the right way to do.

	(function chatUpdater() {
	 setTimeout(function() {
		$.ajax({ url: "/messages/getChatUpdates/{{ $thread->id }}", success: function(data) {
		  $.each(data.unreadMessages, function(index, value) {
			if ($(".msgs-list .msg-item-" + value.id).length > 0) {  
			} else {
			  $(".msgs-list").append(value.view);
			  $('.rbox').animate({scrollTop: $('.rbox').get(0).scrollHeight}, 2000);
			}
		  });
		  chatUpdater();
		}, dataType: "json"});
	}, 8000);
	})();

**Comment by Gummibeer** [comment]
#260 and linked issues from this issue.

@cmgmyr can you pls add any kind of note to the readme that this package doesn't handle the display/communication to the frontend in any kind and link some of the possible ways like the laravel internal PubSub, Pusher, Socket.io and whatever else is in your list!? :)

**Comment by Gummibeer** [comment]
@imonoid and to rate your code: it's not good. Your code isn't realtime - it's every 8sec pull. This means that I have to wait for 8sec plus network & render time to see a message. On the other hand this means that it calls the backend every 8sec even if there is nothing. So if I have an old chat open and the other person not it will request "changes" every 8sec and will never get any.
If you have some more users this results in a massive network-load and php instances just to return that there is nothing new.

So you won't come around of anykind of subscription/sockets that just communicate if there is something new. If you want to go with an `setInterval` (setTimeout runs just ones) I recommend you to pass the last message-id in the chat and have a lot of cache usage. The last message-id per thread for example. With this you can return with a 204 in super early state without any DB request.

```php
function postNewMessage(Thread $thread, $message) {
// store message in db and so on
Cache::put('thread_'.$thread->getKey().'_last_message_id', $message->getKey());
}

function getChatUpdate(Thread $thread, $lastMessageId) {
if($lastMessageId == Cache::get('thread_'.$thread->getKey().'_last_message_id')) {
return response('', 204);
}
// if there is another message than the last pulled one return the new messages
}
```

with this

**Comment by imonoid** [comment]
Hi Gummibeer,

Thanks for the very good and informative feedback.  I'll consider your advice and update my code.  

- Raymund

**Comment by cmgmyr** [comment]
will do @Gummibeer!
