### ISSUE TITLE
How to get the thread participated by only 2 users (One to one messaging?)

### ISSUE THREAD

**Issue by imonoid** [cmgmyr/laravel-messenger#265]
I need the ability to do one on one messaging and add some users later on, thus the need to get the thread participated by the two users.  What is the correct way of doing this, so that there will always be only a single on-on-one thread for both user?

**Comment by Gummibeer** [comment]
Hey, I think the easiest way would be to do it with a `whereHas` query.

```php
$threads = Thread::with('participants')->whereHas('participants', function ($query) use ($user1) {
    $query->where('user_id', $user1->getKey());
})->whereHas('participants', function ($query) use ($user2) {
    $query->where('user_id', $user2->getKey());
})->get();
$thread = $threads->filter(function(Thread $thread) {
    return $thread->participants->count() == 2;
})->first();
```
I have no idea how to put the count condition in the first query. (have no time to tinker with it). But this should do what you want. I'm not sure if this is the best or right way to do it.

**Comment by imonoid** [comment]
Hi, your code's good to go, exactly what i was looking for.  thanks a lot.

**Comment by Gummibeer** [comment]
@imonoid no problem, I think that there should be a way to put the php `filter()` into the query - but this should be a good starting point. :)

**Comment by a-komarev** [comment]
You could extend Thread model and store count of the participants in it. Or just store boolean if this thread a group chat or private.

**Comment by imonoid** [comment]
thanks a-komarev.  i'll look into your solution once i get all functionalities up and running.
