### ISSUE TITLE
"Type error: Argument 1 passed to Illuminate\Auth\EloquentUserProvider::validateCredentials() must be an instance of Illuminate\Contracts\Auth\Authenticatable, instance of App\User given, called in C:\xampp\htdocs\projects\mongo\vendor\laravel\framework\src\Illuminate\Auth\SessionGuard.php on line 381

### ISSUE THREAD

**Issue by osshaheen** [cmgmyr/laravel-messenger#266]
i use mongo db with laravel using jenssegers package , i try php artisan serve and the registration is complete but when i try to login this error appears to me . 
please tell me what i can do to solve this problem .

**Comment by a-komarev** [comment]
Hello, @osshaheen! I'm not sure it's related to messenger package. But i suppose that you need to add `implements \Illuminate\Contracts\Auth\Authenticatable` to your `User` model class definition.

**Comment by bhattaxay** [comment]
I am just facing the same issue. After following your above steps it throws me : Trait 'App\Authenticatable' not found.  What should i do?

**Comment by kerolesmonsef** [comment]
i think you should write 
`php artisan make:auth`

**Comment by MohammadaliMirhamed** [comment]
> i think you should write
> `php artisan make:auth`

:) Golabi hasti to

**Comment by sagarjethi** [comment]
you can directly extend this model also
laravel 7 i am using
```
use Illuminate\Foundation\Auth\User as Authenticatable;


class University extends Authenticatable {}
````
