### ISSUE TITLE
Question:  Regard Realtime Updates

### ISSUE THREAD

**Issue by imonoid** [cmgmyr/laravel-messenger#267]
![chatz](https://user-images.githubusercontent.com/20701396/31609979-59f25bda-b287-11e7-95c7-5d689c80d1c7.PNG)

I have successfully implemented Pusher in my chat, instead of using javascript poll to retrieve updates from server.  Its working correctly as updates are realtime.  Now, my the next feature I want to add is to make the chat items on the left of the screenshot have a background of blue whenever there is an update for them.  My question is, how are the updates for these implemented?  should each of them have their own listener?

**Comment by filtration** [comment]
Use The event variable inside the model, like so:

	/**
	 * The event map for the model.
	 *
	 * @var array
	 */
	protected $dispatchesEvents = [
		'created' => \App\Events\Messages\MessageCreatedEvent::class,
	];

Then you can create the eventfile which can push your event to where ever (preferably sockets)


```
<?php

namespace App\Events\Messages;

use Illuminate\Broadcasting\Channel;
use Illuminate\Queue\SerializesModels;
use Illuminate\Broadcasting\PrivateChannel;
use Illuminate\Broadcasting\PresenceChannel;
use Illuminate\Foundation\Events\Dispatchable;
use Illuminate\Broadcasting\InteractsWithSockets;
use Illuminate\Contracts\Broadcasting\ShouldBroadcast;

class MessageCreatedEvent implements ShouldBroadcast
{
    use Dispatchable, InteractsWithSockets, SerializesModels;

    public $message;

    /**
     * Create a new event instance.
     *
     * @return void
     */
    public function __construct(Messages $message)
    {
        $this->message = $message;
    }

    /**
     * Get the channels the event should broadcast on.
     *
     * @return \Illuminate\Broadcasting\Channel|array
     */
    public function broadcastOn()
    {
        return ['message-system'];
    }
}
```


Then client side you can listen to the even something like this to change the color of a new message

```
socket.on('message/event', function(event){
    // access your sidebar message 
    $('#message-' +event.message.id).addClass('alert alert-info');
})
```


You need to add a identifier to that row with an id like message-123

**Comment by imonoid** [comment]
hi @filtration,
thanks for the assist.  i have managed to implement realtime update notification based partially on your guide.  what i am not sure though is if I am doing it correctly.

basically, when some dude sends a message, all "participants" on that thread (likely only 2), will be "notified":

`	foreach($thread->participants as $p) {`
`		if ($p->user->id != Auth::id()) {`
`		  $tv = view('messenger.partials.thread1', ['thread' => $thread])->render();`
**`		  event(new MessageAddedOrUpdated($msg, $p->user, $p->user->newThreadsCount(), $tv));`**
`		}        `
`	}`

params of MessageAddedOrUpdated are as follows:
**$msg** = message data sent
**$p->user** = the participant
**$p->user->newThreadsCount()** = new thread count of participant.  to update new thread count on the lower right of the screen (not seen on the screenshot)
**$tv** = the thread rendered view.  to update the thread info on the left of the screenshot.

**Comment by filtration** [comment]
You can broadcast it privately with the message ID and then listen to that specific Id if they are authorized... More information can be found here: https://laravel.com/docs/5.5/broadcasting#authorizing-channels
