### ISSUE TITLE
Issue with deletes

### ISSUE THREAD

**Issue by fligen** [cmgmyr/laravel-messenger#27]
I'm having and issue querying the soft deleted messages. 

I have removed the ->where('participants.deleted_at', null) from scopeForUser with no luck.

Im trying to create a view so a user can see there deleted messages any help would be appreciated.

**Comment by avlastenok** [comment]
As you left out your code I will assume that you did not read the documentation on laravel.com so to get results containing deleted items you use 
withTrashed()
If you only want deleted items you use 
onlyTrashed()
You can find more about soft deleting at:
http://laravel.com/docs/5.0/eloquent#soft-deleting

**Comment by fligen** [comment]
Thank you, I was using withTrashed() but forgot to remove ->where('participants.deleted_at', null) from the line.  Thanks again for your help.
