### ISSUE TITLE
Messages are being sent twice

### ISSUE THREAD

**Issue by aflorin** [cmgmyr/laravel-messenger#270]
I have a problem when I reply to a message.
I am logged in with 2 different users, on different browsers. If I reply from one user, the replied message is being sent twice, from the both logged accounts.

**Comment by a-komarev** [comment]
Thats seems like issue in your controller logic. Not sure it's bug in package. Could you show code related to sending message in your project?

**Comment by cmgmyr** [comment]
Can you provide some code examples @aflorin?

**Comment by aflorin** [comment]
Sorry, it was a problem caused by browser-sync. I made all the steps again, without using browser-sync and everything works fine.
