### ISSUE TITLE
Displaying messages without calling the controller

### ISSUE THREAD

**Issue by jomayan** [cmgmyr/laravel-messenger#271]
Hi 

Newbie here...
Is it possible to display(in view) the messages of  a certain thread number without calling the controller function using the below.

`@each('messenger.partials.messages', $thread->messages , 'message')`

Thanks

**Comment by cmgmyr** [comment]
Hi @jomayan, sorry, I'm not sure what you mean. The `$thread` object is getting pushed to the view from the controller, but you aren't using anything in the controller after that.

**Comment by jomayan** [comment]
Hi Chris,
Sorry about my question for not being clear enough.
Anyways, here's what I want to achieve.

In the screenshot, the red box is achieved with this command. 
**@each('messenger.partials.thread', $threads , 'thread', 'messenger.partials.no-threads')** 

What I want to achieve is the blue box during the page loads. I was able to achieve it but I was using javascript (below).

**function loadfirstmessage(){
           var thread_id = {{ $threads->first()->id }} ;  
           var getmessages_url = "/messages/";
        $.get(getmessages_url + thread_id, function (itemdata2) {
                document.getElementById("conversation_window").innerHTML = itemdata2;                  
       });
	}

function get_messages(thread_id) {
        var getmessages_url = "/messages/";
        $.get(getmessages_url + thread_id, function (itemdata) {
                document.getElementById("conversation_window").innerHTML = itemdata;              
            });
    };**

Is there a way to load it like the way the threads being loaded ?

![screen shot 2017-10-27 at 12 26 35 pm](https://user-images.githubusercontent.com/25026077/32121869-3736b0f2-bb13-11e7-8409-ad66abfaa2aa.png)

**Comment by Gummibeer** [comment]
There are multiple ways.

1) You can render all messages onload in different `<div>` with IDs and show/hide the right one. This will result in a massive amount of html and pageload-time.
2) You can put all messages as json in a `data` attribute on the thread and load the messages via javascript from there.
3) Do it the right way and load them async from the backend.

**Why** is Nr.3 right!? Cause all other solutions will result in a massive amount of html and pageload-time. Also they will not allow to do pagination - so you will have to load/display all messages. With an async solution you can load everytime just 20 messages and if the user scrolls you load the next one (infinity scroll).

So yes - there are ways to avoid calling the controller but if your users will write some more messages it will affect the UX and also your server performance.

**Comment by Gummibeer** [comment]
@jomayan is your question/problem solved? Or do you need more hints?

**Comment by jomayan** [comment]
Thanks @Gummibeer ... 
We can close this issue :)
