### ISSUE TITLE
Please help me erro

### ISSUE THREAD

**Issue by phongtq2305** [cmgmyr/laravel-messenger#272]
"
<img width="1280" alt="screen shot 2017-11-06 at 11 53 29 pm" src="https://user-images.githubusercontent.com/29747493/32453053-d641f6b0-c34d-11e7-9e0c-5035d51f7eeb.png">
Call to undefined method App\User::newThreadsCount() (View: /Applications/XAMPP/xamppfiles/htdocs/dulich/local/resources/views/messenger/unread-count.blade.php) ▶"

**Comment by cmgmyr** [comment]
Couple questions:

1. Is the are you logged in or logged out in your app? The example file [here](https://github.com/cmgmyr/laravel-messenger/blob/master/examples/views/messenger/unread-count.blade.php) doesn't check if the user is logged in or not - so you'll need to implement that check.
2. Did you include the `Messagable` trait in your `User` model?

**Comment by phongtq2305** [comment]
thanks cmgmyr , because I not include Messagable , I included but have erro when run  /messages/create , please support to me
<img width="1280" alt="screen shot 2017-11-07 at 12 06 30 am" src="https://user-images.githubusercontent.com/29747493/32453847-f944eb02-c34f-11e7-83a7-3ffefdbd362d.png">

**Comment by cmgmyr** [comment]
In your `users` database table, I'm assuming you are not using `name` for the field...maybe something like `first_name`/`last_name`? If so, you'll have to send the columns you want through `participantsString()`, see [here](https://github.com/cmgmyr/laravel-messenger/blob/master/src/Models/Thread.php#L315).

**Comment by phongtq2305** [comment]
I not use table with name as users , I used table with name by ="customer" ,Which can be corrected ? in source PHP ?

**Comment by cmgmyr** [comment]
You can change the table names and models via the config file, please take a look at the `readme` file

**Comment by phongtq2305** [comment]
Thanks cmgmyr for answer , I built program , but I want not use column "name" and replace by "lastname" , where is file I can edit ? I can not find in source php if I install by composer ?

**Comment by cmgmyr** [comment]
@phongtq2305 you'll need to edit the `participantsString()` call, so...

`$thread->participantsString($userId, ['lastname'])` 

which is referenced [here](https://github.com/cmgmyr/laravel-messenger/blob/master/examples/views/messenger/partials/thread.blade.php#L14) in the examples
