### ISSUE TITLE
Exception: Integrity constraint violation: 1048 Column 'user_id' cannot be null

### ISSUE THREAD

**Issue by ivanzhujunwei** [cmgmyr/laravel-messenger#274]
Hi,
I am using the example from the code itself, When I tried to send the message, I got the exception,  `SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_id' cannot be null (SQL: insert into `messages`` 
any suggestions?  Thanks very much!
![wx20171201-232511](https://user-images.githubusercontent.com/14146339/33482849-1f3379d4-d6ef-11e7-8e6b-0591ed57ee2b.png)

**Comment by ivanzhujunwei** [comment]
No one encountered this issue?
I checked the code,
`// Message
        Message::create([
            'thread_id' => $thread->id,
            **'user_id' => Auth::id(),**
            'body' => $input['message'],
        ]);`
I found that when creating a message, it doesn't require user to login, so the problem occurs because there is not userId.
I am wondering didn't you guys have this issue? Or is there any mistake I made?

**Comment by Gummibeer** [comment]
I haven't Take a Look in the example but a simple `auth` Middleware will solved this.

**Comment by omitobi** [comment]
Seems user has to be logged in to use this service based on this issue. Did you fix this?

**Comment by Gummibeer** [comment]
@omitobi No, this package work's with whatever you want. But you need an user-model instance from where you get this is up to you. The `Auth::user()` is just an example. if you want to do it without auth, like a simple support chat, you can create an "empty" user just with email, if needed, and query it from DB by email like `User::byEmail($request->get('email'))->first()`.

The example isn't meant to be used in production. It's just an example/demo/template how the steps would be to create a thread, message, answer and so on.

**Comment by omitobi** [comment]
Thank you @Gummibeer for breaking it down.

**Comment by Gummibeer** [comment]
No problem, but feel free to add the `auth` middleware in the demo and create a PR for it. Open-Source is give and take. ;)

**Comment by ivanzhujunwei** [comment]
@Gummibeer  Thank you very much! I am sorry that I didn't go deep into this issue, I am new to laravel but I think you are right!
