### ISSUE TITLE
Multiple guard support

### ISSUE THREAD

**Issue by joooseb** [cmgmyr/laravel-messenger#275]
This package is supporting multiple guard messages? (For example send a message to guard Admin to a guard (web) User)

**Comment by cmgmyr** [comment]
Yes, you could certainly do this. Authorization for viewing/updating message threads is totally up to the developer. One of the easier ways is to add an additional check on the `show()` [method](https://github.com/cmgmyr/laravel-messenger/blob/master/examples/MessagesController.php#L42) that will check if the user is a participant, admin, etc. You could also use guards, another auth package, etc.

**Comment by MohammadBasel** [comment]
Hey @cmgmyr,

My goal is not only authorizing the viewing and updating of the messages, but also sending messages across different guards.
Meaning, the admin (from the admins table and admin guard) can send a message to the user (from the users table and web guard) and vice versa. Is this supported?

Thanks in advance,

Basel

**Comment by cmgmyr** [comment]
@MohammadBasel this package only supports one "users" table, which is configurable in the config file. You'd have to make additional changes to the participants to instead have a polymorphic relationship with users and admins

**Comment by MohammadBasel** [comment]
@cmgmyr thanks for the fast reply!
That what I was thinking of doing, but I just wanted to confirm with you if it can be configured before going through the trouble.

Maybe this can be added as a feature in the future.
