### ISSUE TITLE
how can i install messenger manually without composer update

### ISSUE THREAD

**Issue by hassanshuja** [cmgmyr/laravel-messenger#276]
Please tell me the files which i have to update manually with out composer install or update as composer update is breaking my application by upgrading other dependencies and laravel version. So i need it to install manually. Please tell me the files i have to update.

**Comment by a-komarev** [comment]
1. Create in your Laravel root directories named `./packages/laravel-messenger` for example, then place all the files from this repository in it.
Let's imagine your Laravel root directory is `/var/www/com/super-app`. Then you'll have `/var/www/com/super-app/packages/laravel-messenger/src` where all the source files will be stored.

2. Add to your `composer.json` file `autoload.psr-4` section new namespace:
```
"Cmgmyr\\Messenger\\": "packages/laravel-messenger/src/"
```
You'll have something like:
```json
"autoload": {
        "classmap": [
            "database/seeds",
            "database/factories"
        ],
        "psr-4": {
            "App\\": "app/",
            "Cmgmyr\\Messenger\\": "packages/laravel-messenger/src/"
        }
    },
```

3. Execute `composer dump` command to index new namespace.

After this 3 simple steps you are ready to start configuration process.

**Comment by a-komarev** [comment]
But keep in mind, that `composer.json` from custom loaded packages wouldn't be used, then you need to register `Cmgmyr\Messenger\MessengerServiceProvider` in your `./config/app.php` by yourself.

**Comment by Gummibeer** [comment]
@hassanshuja If this is the case your current `composer.json` version constraints aren't right. A `composer update/install` command should **NEVER** break an installation/setup. If it does you have to be more precise with your versions. If a package doesn't use https://semver.org and you have `^5.3` for example you can specify the last working version like `5.3.7`. This is also possible for packages that are required by another dependency as long as all version-constraints don't conflict. So until another package requires `^5.4` everything is fine.

These links should help you.
https://getcomposer.org/doc/03-cli.md#show
https://getcomposer.org/doc/03-cli.md#depends-why-

**Why** is a working `composer.json` this important?
Cause if your current setup is destroyed/unusable cause of whatever you will never get your app running.
