### ISSUE TITLE
How can I add extra $fillable

### ISSUE THREAD

**Issue by naumanahmed19** [cmgmyr/laravel-messenger#277]
I have added more columns but how can I override fillable.
here is my class
```
namespace App;

class Message extends \Cmgmyr\Messenger\Models\Message
{
    protected $fillable = ['thread_id', 'user_id', 'body', 'price','quotation'];

}
```

**Comment by cmgmyr** [comment]
Hi @naumanahmed19, this is correct - the next step would be to update the package's config file to reference your new model and not the default.
