### ISSUE TITLE
Pulling Email/Avatar from Participating Users

### ISSUE THREAD

**Issue by mprythero** [cmgmyr/laravel-messenger#278]
I have run into an issue that I'm not entirely sure about. Based on the suggestions here: https://laracasts.com/discuss/channels/laravel/has-anyone-used-the-cmgmyrlaravel-messenger, I have created another function which is meant to pull either the user's email or avatar file path from the users table (rather than just having the names).

I'm curious if I'm doing it the right way, because nothing appears when I update the file with the new function.

Here's an example of my function with the avatar:

```
public function participantsAvatar($userId = null, $columns = ['avatar'])
    {
        $participantsTable = Models::table('participants');
        $usersTable = Models::table('users');
        $userPrimaryKey = Models::user()->getKeyName();

        $selectString = $this->createSelectString($columns);

        $participantNames = $this->getConnection()->table($usersTable)
            ->join($participantsTable, $usersTable . '.' . $userPrimaryKey, '=', $participantsTable . '.user_id')
            ->where($participantsTable . '.thread_id', $this->id)
            ->select($this->getConnection()->raw($selectString));

        if ($userId !== null) {
            $participantNames->where($usersTable . '.' . $userPrimaryKey, '!=', $userId);
        }

        return $participantNames->implode('avatar', ', ');
    }
```

The column name is avatar, and usually returns the format of "public/images/image-filename.jpg" and I pull the images using:` <img src="{{Storage::disk('local')->url(Auth::user()->avatar)}}" class="img-circle" alt="User Image">` but I'm not sure about doing it in this case.

If you can help or have any suggestions, please let me know. I'd very much appreciate them!
Matt

**Comment by a-komarev** [comment]
```php
return $participantNames->implode('avatar', ', ');
```
This is totally useless for your case, if I understood you right. Because it will create string of avatars of all the participants concatenated with `,` character.

```php
    public function participantsAvatar($userId = null, $columns = ['avatar'])
    {
        $participantsTable = Models::table('participants');
        $usersTable = Models::table('users');
        $userPrimaryKey = Models::user()->getKeyName();

        $selectString = $this->createSelectString($columns);

        $participants = $this->getConnection()->table($usersTable)
            ->join($participantsTable, $usersTable . '.' . $userPrimaryKey, '=', $participantsTable . '.user_id')
            ->where($participantsTable . '.thread_id', $this->id)
            ->select($this->getConnection()->raw($selectString));

        if ($userId !== null) {
            $participants->where($usersTable . '.' . $userPrimaryKey, '!=', $userId);
        }

        return $participants->get();
    }
```
I haven't tested this code, but should be something similar to it.

**Comment by mprythero** [comment]
At the moment, this is the return I receive on text (just testing out before I start to work with the images altogether), would you have any suggestions for any alterations?

[{"name":"public\/avatars\/default.png"}]

**Comment by Gummibeer** [comment]
I have no Idea about what you try to so!? But if you can so `$user->avatar` you don't have to create any other method.
Your User model is available from everywhere, sometimes through the participant model.

```php
foreach($thread->participants as $participant) {
  $avatar = $participant->user->avatar;
}
$message->user->avatar;
foreach($message->recipient as $participant) {
  $avatar = $participant->user->avatar;
}
```

You can speed it up by eager load the relations. But there is for 100% no reason to write custom queries and don't use eloquent.

**Comment by a-komarev** [comment]
Agree with @Gummibeer. Start from an Eloquent queries. And later optimize it if there is a need.

**Comment by Gummibeer** [comment]
In your case you can do:
```php
$avatars = $thread->load('participants.user')->participants->map(function(Participant $participant) {
    return $participant->user->avatar;
})->toArray();
```

or if you want to save the map call and so on Just add a `users` relation to the thread model with the `hasManyThrough` https://laravel.com/docs/5.5/eloquent-relationships#has-many-through

After this it's easy like:
```php
$avatars = $thread->users()->pluck('avatar')->toArray();
```

Both solutions save you a massive amount of custom code and queries.
