### ISSUE TITLE
Combine messenger with Laravel registration

### ISSUE THREAD

**Issue by MrMooky** [cmgmyr/laravel-messenger#279]
This is a feature request, not a bug report. Or maybe a "how-to" question...

I'm using the default Laravel auth methods for users to register and login. What would be nice is to send out a new message to any new users who registers to the site.

Is this possible with the current version?

**Comment by Gummibeer** [comment]
It is, just use laravel events or model observers. With this you can react on the `user-created` event  (not the real name) and do whatever you want. Send an in app message with this package, send an email and so on.

**Comment by a-komarev** [comment]
@Gummibeer is right, create listener which will wait for the user registration event.

As soon as it fired:
1. Create new thread.
2. Add newcomer and your system user as participants to this thread.
3. Send greetings message from system user to this thread.

**Comment by MrMooky** [comment]
Ok, thanks for the help. My concern was that I'm not able to retrieve a user id right within the RegisterController. It's a value that is given when writing into the DB and not created within the controller.

**Comment by a-komarev** [comment]
Create `app/Observers/UserObserver`:

```php
<?php

namespace App\Observers;

use App\User;

class UserObserver
{
    public function created(User $user)
    {
        event(new UserWasCreated($user);
    }
}
```

In your `app/Providers/AppServiceProvider.php` add:

```php
\App\User::observe(\App\Observers\UserObserver::class);
```

And you will fire event right after User model will be created, so you will be sure you have an id.
