### ISSUE TITLE
Paginate Threads?

### ISSUE THREAD

**Issue by dubcanada** [cmgmyr/laravel-messenger#28]
Hello,

Is there any way to Paginate the threads? It seems to return the results with a `->get();` couldn't you just return the query builder and have the user then use `->get(10);` or `->paginate();` etc. That way it is more extendable?

**Comment by fetch404** [comment]
Hi there. I know I'm not the person who made the package, but anyway...
This should be possible. I actually planned to try to get this working on my own site. I might make a pull request if I can A: figure out how to make one (I'm not good with Git), and B: get this working without messing everything up. I'll get back to you if I get it working.

**Comment by dubcanada** [comment]
I have it working by removing the `->get()` and just returning the built query. It will also allow you to add additional stuff to it like where states and limits and stuff if you want.

I'll make a pull request shortly as it appears to be more then just me wanting it.

**Comment by avlastenok** [comment]
If you want limits and the likes it would seem scopes would be better. 
If you want pagination to the results instead of get just replace it with paginate(X);

**Comment by fetch404** [comment]
@avlastenok Personally, I think scopes are better for only retrieving certain data, like posts by a user or message threads that have a user as a participant, stuff like that. Scopes should NOT, in my opinion, be used for getting paginated data, since, let's face it, you can just do that in controllers or views.

The main thing I like about this package is that there is so much you can do. On my website, I added a private message dropdown, but that's not all; the envelope icon will blink when you have a new message!

@dubcanada It's nice to hear that you got it working. Making a pull request is a good idea; especially because in the future, tons of people who use this may have their time saved if you get this little change merged. Good luck!

I guess I'll tag @cmgmyr and see what he thinks.

**Comment by avlastenok** [comment]
Actually you would want to add scopes instead of building querys up in the controller. 
But that's beside the point.
If you would want something like this it would need to be made an option and not forced on everyone to use.

**Comment by cmgmyr** [comment]
Hey everyone, thank you very much for the input. Pagination would definitely be helpful.

My primary concern is the current API and not having to make too many breaking changes, if I can help it. Right now I see two options:

1. remove the `->get()` from the scopes and just return the query
2. add additional methods for pagination like `scopeForUserPaginate($query, $userId, $perPage)`

The problem with no 1 is that it would break the current workflow/api and users would have to update their apps to include `->get()`, `->paginate()`, or whatever...

The problem with no 2 is that it just adds more code/bloat to the package and could start to take away the simplicity of the package.

Now, with all of that said, I think no 1 would still be the best option. This corresponds better to [Laravel's Example](http://laravel.com/docs/5.0/eloquent#query-scopes) and would let the users take more control in extending the query as they need.

Thoughts?

**Comment by tshafer** [comment]
I say number one. Im fine with just using the query and adding what I need. This makes it pretty flexible.

While this is a breaking change, just tag and it and make notes.

**Comment by cmgmyr** [comment]
Yeah, definitely. I'll be tagging the new release with the change and adding a note along with updating the example files.

**Comment by dubcanada** [comment]
What is your thought on also removing the

`->latest('updated_at')`

And requiring people add it if they want that? Reason being is if you want to do a `->count()` mysql complains about the order by being ambiguous.

Or maybe make another function without it?

I ended up making 4 new scopes

* scopeForUserWithNewMessages
* scopeForUserWithTrashNoSort
* scopeForUserNoSort
* scopeForUserWithTrash

And overriding `scopeForUser` to remove `->get();`

And everything seems to be working fine.

Thoughts?

**Comment by cmgmyr** [comment]
yes, I think removing the `->latest('updated_at')` would be ok too. More flexibility would be helpful to most I believe

**Comment by cmgmyr** [comment]
These changes have been added to the latest release. Please let me know if anyone has any questions/issues. Thanks again everyone for your feedback and opinions!
