### ISSUE TITLE
Fast query for "unread messages"

### ISSUE THREAD

**Issue by wflaschka** [cmgmyr/laravel-messenger#280]
Referencing issue #245 

After setting up a project on a staging server I had **extremely slow pageloads** (~3 minutes) and it took me a while to trace it to the `unreadMessagesCount()` implementation. (My DB has 30k messages, 7.2k threads, and 14.5k participants.)

The slowdown was inexplicable, because on my laptop the _same_ query took 100ms.

If you experience the same problem, and don't want to start reconfiguring your mysql, I found this version of the query much more performant:

```sql
select count(mm.id) as aggregate
FROM messenger_messages AS mm 
LEFT JOIN messenger_threads as mt ON (mm.thread_id = mt.id)
LEFT JOIN messenger_participants as mp ON (mm.thread_id = mp.thread_id)
WHERE 1=1 
AND mm.user_id != USER_ID
AND mp.user_id = USER_ID 
AND (mp.last_read < mm.created_at or mp.last_read IS NULL)
AND mp.deleted_at is NULL
AND mm.deleted_at is NULL
AND mt.deleted_at is NULL
```

Query time went from 3 minutes to 0.09 seconds.

**Comment by zilveer** [comment]
@cmgyr is it possible to add this as an PDO for the related query?

**Comment by vaishnavmhetre** [comment]
> @cmgyr is it possible to add this as an PDO for the related query?

Yes, it is possible through query builder. But, it's just that we need to write query builder (DB or model name - should refer currently implemented solution) methods explicitly and give the result as expected in return to avoid breaking changes.
