### ISSUE TITLE
Adding new column to messages table

### ISSUE THREAD

**Issue by MrMooky** [cmgmyr/laravel-messenger#281]
I added a new column _image_ to the messages table but cannot seem to save it.

```
Message::create(
    [
        'thread_id' => $thread->id,
        'user_id'   => Auth::id(),
        'body'      => Input::get('message'),
        'image'     => $imageName
    ]
 );
```

`$imageName` is definitely not empty, but the value is not saved into the db. How can I allow a new column to access data?

**Comment by cmgmyr** [comment]
Hi @MrMooky,
The `image` column is not in the `$fillable` array on the package's default [Message Model](https://github.com/cmgmyr/laravel-messenger/blob/master/src/Models/Message.php#L32), so you cannot use the `create()` method like you have explained as it will drop the `image` data. I'd suggest creating your own `Message` model which extends the package's one, then override the `$fillable` property with the values that you need. Finally, you'll need to update the [config file](https://github.com/cmgmyr/laravel-messenger/blob/master/config/config.php#L7) to point to your new model.

**Comment by MrMooky** [comment]
Hej @cmgmyr,

sounded really simple, but after trying a few things the field still does not get saved. Could you please point me into the right direction?

That is my new `Messages` Model:

```
namespace App;
use Cmgmyr\Messenger\Models\Message as Eloquent;

class Messages extends Eloquent
{
    /**
     * The attributes that can be set with Mass Assignment.
     *
     * @var array
     */
    protected $fillable = ['thread_id', 'user_id', 'body', 'image'];
}
```

This is the updated line within config/messenger:

`'message_model' => App\Messages::class,`

Have I forgotten something?

**Comment by cmgmyr** [comment]
Hmm, did you update your controller code to point to your new model?

**Comment by MrMooky** [comment]
That's it! Thank you very much. :)
