### ISSUE TITLE
Just wanna say thank you

### ISSUE THREAD

**Issue by riskevolve** [cmgmyr/laravel-messenger#282]
This is a great package. Truly plug n play i.e. install, copy the controller, route, and view, and working as expected.  Integrate easily with AdminLTE.  Save my life and my time. God bless you and your family. 
Sorry I am newbie, pls delete this post if not appropiate.
Regards from Indonesia,
Herry

**Comment by cmgmyr** [comment]
You're very welcome and I'm glad you like the package!
