### ISSUE TITLE
guest usage

### ISSUE THREAD

**Issue by icuMedia** [cmgmyr/laravel-messenger#286]
Is there any provision for use by guests (starting a thread with a contact form)?

I'm thinking along the lines of adding a guest table and use a polymorphic relationship.

Otherwise this package is awesome

**Comment by cmgmyr** [comment]
thanks for using the package!

there isn't anything out of the box to support this, but you can certainly extend the base models to use polymorphic relationships. You'd have to create some sort of `guest` "user" model though.

**Comment by icuMedia** [comment]
Just one quick question.. I got it working, but I can't really work out how to get the `creator` method working again for the threads after implementing a polymorphic relationship.

**Comment by a-komarev** [comment]
@icuMedia you'd better to show how you've done it if you want a advice how to make this code work.

**Comment by icuMedia** [comment]
@a-komarev okay. These are my models:

`User`:
```
class User extends Authenticatable
{
/**
     * Relation to message
     */
    public function messages()
    {
        return $this->morphMany(Message::class, 'messagable');
    }
}

```
`Guest`:
```
class Guest extends Model
{
    public function messages()
    {
        return $this->morphMany(Message::class, 'messagable');
    }
}

```
`Message`:
```
class Message extends Messenger
{
    protected $fillable = ['thread_id', 'body', 'messagable_id', 'messagable_type'];

    public function messagable()
    {
        return $this->morphTo();
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function guest()
    {
        return $this->belongsTo(Guest::class);
    }
}
```

**Comment by a-komarev** [comment]
Have you tried to use `messagable` method to get it?

**Comment by icuMedia** [comment]
Could you elaborate on that. To be honest this is the first time I'm using a polymorphic relationship.

**Comment by a-komarev** [comment]
I'd recommend you to read the documentation: https://laravel.com/docs/5.6/eloquent-relationships#polymorphic-relations
There are a lot of useful examples there.

By adding `messageble` method to your `Message` model which returns `morphTo` relationship you may retrieve the owner of a polymorphic relation by accessing the name of the method that performs the call to `morphTo`.

```php
public function messagable()
{
    return $this->morphTo();
}
```


So, you could access that method as a dynamic property:
```php
$message = Message::find($messageId);
$userOrGuestModel = $message->messagable;
```

The `messagable` relation on the `Message` model will return either a `User` or `Guest` instance, depending on which type of model owns the message.

**Comment by a-komarev** [comment]
If you want to name your method as `creator` you should pass additional parameter to `morphTo` method to instruct it how columns are named in database.

```php
public function creator()
{
    return $this->morphTo('messagable');
}
```

Then you'll be able to write:

```php
$message = Message::find($messageId);
$userOrGuestModel = $message->creator;
```

And in database columns will be `messagable_type` and `messagable_id`.

**Comment by a-komarev** [comment]
Don't forget to declare in Laravel Messenger configuration file your custom `Message` model.

**Comment by icuMedia** [comment]
Awesome that got me moving again. Thank you so much!
