### ISSUE TITLE
Group messages

### ISSUE THREAD

**Issue by bajki** [cmgmyr/laravel-messenger#292]
So this is example:

id | conversation_id | text | user_id

1 | 1 | Test0 | 1

2 | 1 | Test1 | 1

3 | 1 | Test2 | 1

4 | 1 | Test3 | 2

5 | 1 | Test4 | 2

6 | 1 | Test5 | 1

7 | 1 | Test6 | 1

8 | 1 | Test7 | 1

How to group messages from id 1-3, 4-5, 6-8, so when user sends few messages in row it's a group until another user sends message.

**Comment by Gummibeer** [comment]
**markdown table:**
| id | conversation_id | text | user_id |
|---|---|---|---|
| 1 | 1 | Test0 | 1 |
| 2 | 1 | Test1 | 1 |
| 3 | 1 | Test2 | 1 |
| 4 | 1 | Test3 | 2 |
| 5 | 1 | Test4 | 2 |
| 6 | 1 | Test5 | 1 |
| 7 | 1 | Test6 | 1 |
| 8 | 1 | Test7 | 1 |

**Comment by Gummibeer** [comment]
I would do it in the blade view - save the last user-id and compare it to the current one. If they match don't start a new message block, just a new paragraph.

**Comment by bajki** [comment]
Can you provide code for that?

**Comment by Gummibeer** [comment]
```blade
@php($lastUserId = null)
@foreach($messages as $message)
    @if($lastUserId != $message->user_id)
        <div>
    @endif
    <p>{{ $message->Text }}</p>
    @php($lastUserId = $message->user_id)
    @if($lastUserId != $message->user_id)
        </div>
    @endif
@endforeach
```

It's untested but in my head it works 😅🙄
