### ISSUE TITLE
How can I change the default user model and table?

### ISSUE THREAD

**Issue by mohamedsabil83** [cmgmyr/laravel-messenger#293]
I'm building a system using Laravel. I had an account's model and table. What I have to change to use this package with it instead of the user's model and table?

I was published the config file **messenger** and change the **user_model** from `App\User::class` to `App\Account::class` but not work correctly cause `$thread->participantsString()` function bring data from users table instead of accounts.

I had to change every `Models::table('users')` to `Models::table('accounts')` in the core of the package to let it work.

Did I miss something or package need some addition to deal with another table instead of users?

**Comment by a-komarev** [comment]
Try to register user table in your AppServiceProvider:

```php
\Cmgmyr\Messenger\Models\Models\Models::setTables([
    'users' => 'accounts'),
]);
```

**Comment by a-komarev** [comment]
I've made a PR which should fix this issue. And as for now you should define `auth.providers.users.model` as `App\Account::class` or register model & table in your AppServiceProvider manually.

```php
\Cmgmyr\Messenger\Models\Models\Models::setUserModel(\App\Account::class);
\Cmgmyr\Messenger\Models\Models\Models::setTables([
    'users' => 'accounts',
]);
```

**Comment by mohamedsabil83** [comment]
Thank you @a-komarev your suggestion is right and it works as perfect.
For your question, no the `auth.providers.users.model` is for users with passwords to log in the system. and `user_model` is for accounts table which every user has many accounts.

**Comment by a-komarev** [comment]
@mohamedsabil83 I see. Thanks for highlighting this issue, I hope Chris will be able to merge it soon and it will work out of the box.

**Comment by mohamedsabil83** [comment]
Yes, when I review the code I note that. so, I want to check first if I missing something before making a PR to fix that but good you do it.
