### ISSUE TITLE
I cant change the default user model 

### ISSUE THREAD

**Issue by saiiiif** [cmgmyr/laravel-messenger#296]

**Comment by saiiiif** [comment]
Im new with laravel can you give me tha step by step to change the default table 'user' to my table  membre

**Comment by mirkinoid** [comment]
the similar issue is open, the provided solution seems to be working:
https://github.com/cmgmyr/laravel-messenger/issues/293

**Comment by saiiiif** [comment]
it didnt work for me ?? i dont know why

**Comment by a-komarev** [comment]
@saiiiif If you don't know why - then nobody will be able to help you out. You should expose some more information about your application then.

**Comment by saiiiif** [comment]
i just need to change the default user table to my table membre 
in my messanger.php
return [

    'user_model' => App\Membre::class,

    'message_model' => Cmgmyr\Messenger\Models\Message::class,

    'participant_model' => Cmgmyr\Messenger\Models\Participant::class,

    'thread_model' => Cmgmyr\Messenger\Models\Thread::class,

    /**
     * Define custom database table names - without prefixes.
     */
    'messages_table' => null,

    'participants_table' => null,

    'threads_table' => null,
];
also change the package user.model to membre table ?? 
what i m  missing

**Comment by saiiiif** [comment]
@a-komarev  i saw your solution but i dont know what im doing wrong can you please show me the step by step to fix this issue and thank you

**Comment by a-komarev** [comment]
There is an issue with User model reassign, waiting for PR #293 to be merged.

In `app/Providers/AppServiceProvider.php` register method try to add:

```php
public function register()
{
    \Cmgmyr\Messenger\Models\Models\Models::setUserModel(\App\Membre::class);
    \Cmgmyr\Messenger\Models\Models\Models::setTables([
        'users' => 'membre',
    ]);
}
```

**Comment by saiiiif** [comment]
@a-komarev  i try it before i get a Class 'Cmgmyr\Messenger\Models\Models\Models' not found

**Comment by a-komarev** [comment]
Did you copied it with a backslash prefix `\Cmgmyr\Messenger\Models\Models\Models`?

`\Cmgmyr\Messenger\Models\Models\Models !== Cmgmyr\Messenger\Models\Models\Models`

**Comment by saiiiif** [comment]
@a-komarev  yes i tried with and without backslash prefix keep getting the same error

**Comment by a-komarev** [comment]
Then check if you latest version of the package is installed.

**Comment by saiiiif** [comment]
@a-komarev  i m using  "cmgmyr/messenger": "~2.0"

**Comment by a-komarev** [comment]
That's strange, because this class exists in this version:
https://github.com/cmgmyr/laravel-messenger/blob/3da74c4edd8f0caa292ba1fbfc2f42d209519f1b/src/Models/Models.php

**Comment by saiiiif** [comment]
@a-komarev 

C:\xampp\htdocs\tunisia\app\Providers\AppServiceProvider.php
    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        Schema::defaultStringLength(191);
    }
 
    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
 
        
            \Cmgmyr\Messenger\Models\Models\Models::setUserModel(\App\Membre::class);
            \Cmgmyr\Messenger\Models\Models\Models::setTables([
                'users' => 'membre',
            ]);
        
 
    }
}
 
Arguments
"Class 'Cmgmyr\Messenger\Models\Models\Models' not found"
Any suggestion ??

**Comment by a-komarev** [comment]
Ah... wait... there is a typo in my example! Change it to:

```php
public function register()
{
    \Cmgmyr\Messenger\Models\Models::setUserModel(\App\Membre::class);
    \Cmgmyr\Messenger\Models\Models::setTables([
        'users' => 'membre',
    ]);
}
```

**Comment by saiiiif** [comment]
@a-komarev Yes  i dont get any error but when i open my application still showing User table not membre

**Comment by a-komarev** [comment]
@saiiiif you should provide more information if you need help from other people. We don't know what you are building, or how you do it. Show exact code blocks what you are executing, what you expect to get and its actual output.

**Comment by saiiiif** [comment]
@a-komarev 
![github](https://user-images.githubusercontent.com/28693100/41097613-7d4d6e2c-6a50-11e8-8203-b749d8af722a.PNG)
-------
As u can see the 'user' called saif is from table user BUT! i want to get the users from table membre I want the package messanger between Users in  membre

**Comment by saiiiif** [comment]
@a-komarev  do you want to see my application

**Comment by a-komarev** [comment]
@saiiiif it would be better to see the code how you are trying to get members list and some more debug information.

**Comment by a-komarev** [comment]
@saiiiif, we have a good news. @cmgmyr merged my PR which should fix this issue. You can try to install `"cmgmyr/messenger": "dev-master"` and check if it help.

**Comment by a-komarev** [comment]
@saiiiif package version [v2.16](https://github.com/cmgmyr/laravel-messenger/releases/tag/2.16) was published. Does it fix your problem?

**Comment by mohamedsabil83** [comment]
@saiiiif if package v2.16 not working with you, I'll let you try something. If it works then that will be another point to fix.

**Comment by saiiiif** [comment]
thank you my problem is solved

**Comment by saiiiif** [comment]
this version  v 2.16 solve the problem :)
