### ISSUE TITLE
Fired event on thread create and message

### ISSUE THREAD

**Issue by herryswastika** [cmgmyr/laravel-messenger#299]
Hi. Many thanks for this package. Work like a charm. After using it for a while, i have a question. Which event is fired when new thread topic is started, and inside that thread, whic event for new message? I want to send notification using mailgun. Again thanks for this.
Herry

**Comment by a-komarev** [comment]
@herryswastika you are free to place your own events. There is no custom events being fired out of the box.

**Comment by Gummibeer** [comment]
But I think that this is covered by normal eloquent events.
https://laravel.com/docs/5.6/eloquent#events

**Comment by herryswastika** [comment]
Yupp. Just figured it out. I dont use fired event. Not because I dont want to, but because I dont know how to do it. But, I just use the normal code in MessagesController. 
In public function store () in MessagesController, just below this line 
```
        Participant::create([
            'thread_id' => $thread->id,
            'user_id' => Auth::id(),
            'last_read' => new Carbon,
        ]);
        if (Input::has('recipients')) {
            $thread->addParticipant($input['recipients']);
        }
```
I just add :
```
        // if option of sending mail to threadmessages is activated by Admin
        if (DB::table('options')->value('isemailthread') == 1) {

	    	// get all the emails
	        $emails = DB::table('participants')->where('thread_id', $thread->id)
				->join('users', 'participants.user_id', 'users.id')
				->selectRaw("users.email")
				->pluck('email')->toArray();

			// populate email data. I dont use Notification because I am not familiar. I just use regular Mail
			$infothread = new \stdClass();
	        $infothread->title = $input['subject'];
	        $infothread->messagebody = 'New ThreadMessage for you just arrived. Click the below link to open';
	        $infothread->url = '/messages/'.$thread->id;
	        $infothread->sender = 'postmaster@mygreatapp.com';
	        $infothread->sendername = 'MyGreatApp EmailSystem';

			foreach($emails as $email) {
		        Mail::to($email)->send(new InfoThreadEmail($infothread));
	        }
        }
```

Will test the above code tomorrow morning. Now already dark in Indonesia :)

**Comment by herryswastika** [comment]
Now I need to figure out for a User to subscribe/unsubscribe for email. I think I need to add column in table 'participants' with default value (1) so User will automatically subscribed unless he/she chooses otherwise.

**Comment by herryswastika** [comment]
It is working just fine. Now when a new thread message created, or a new message updated in existing thread, an email will be sent.
