### ISSUE TITLE
 Syntax error or access violation 

### ISSUE THREAD

**Issue by Shaher11** [cmgmyr/laravel-messenger#306]
i use laravel 5.2 and when i write this command "php artisan migrate:refresh " 
i get this error below !!
[PDOExcepon] SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'deleted_at'; check that column/key exists

**Comment by cmgmyr** [comment]
I'm sorry, I'm not seeing this issue in my test 5.2 repo. Can you:

1. Pull the latest version of the package `composer update cmgmyr/messenger`
2. `composer dumpautoload -o`
3. `php artisan vendor:publish --provider="Cmgmyr\Messenger\MessengerServiceProvider" --force`
4. `php artisan migrate:refresh`

**Comment by zahirzohair** [comment]
i got the same kind of issue. i followed the above steps, in first step i got a message saying that : Package "cmgmyr/messenger" listed for update is not installed. Ignoring. in step 4 i got this error:   SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'isAgency'; check that column/key exists (SQL: alter table
   `users` drop `isAgency`)

any solution please ?
