### ISSUE TITLE
Get Users Sent Messages

### ISSUE THREAD

**Issue by jsuske1985** [cmgmyr/laravel-messenger#309]
Hi again,

This is how you would get the users sent messages?

$threads = Thread::forUser($token->id)->latest('updated_at')->get();

Not messages sent to the user, but messages the user has sent?

**Comment by jsuske1985** [comment]
Or this?

$threads = Thread::forUserWithNewMessages($token->id)->latest('updated_at')->get();

**Comment by Qoraiche** [comment]
I don't understand your question, you want to get the messages sent by a user?

**Comment by Gummibeer** [comment]
The `user_id` column in the `messages` table is the user-id of the user who send the message:
https://github.com/cmgmyr/laravel-messenger/blob/d4ca1fd3c1e2f9cd55f9af7ed89d46850eed95f9/migrations/2014_10_28_175710_create_messages_table.php#L20
On the `Message` model the `user` relationship is defined - so you just have to define the counter part on your user model.
https://github.com/cmgmyr/laravel-messenger/blob/d4ca1fd3c1e2f9cd55f9af7ed89d46850eed95f9/src/Models/Message.php#L70-L73
