### ISSUE TITLE
Thread::getAllLatest() method dont work when composer install in laravel 5

### ISSUE THREAD

**Issue by slavepens** [cmgmyr/laravel-messenger#31]
Hi there! the method Thread::getAllLatest() is incomplete when you use composer to install the package:

    public static function getAllLatest()
    {
        return self::latest('updated_at');
    }

the method need ->get(); at the end, also there are other issues like this one in this class at line 70, 103, 124... etc

sorry for my bad english!

**Comment by cmgmyr** [comment]
You'll need to add the `->get()` or other chains manually. Please see closed issue #28

**Comment by slavepens** [comment]
Thanks! :D sorry for the inconvenience!
