### ISSUE TITLE
BadMethodCallException: Call to undefined method Illuminate\Database\Query\Builder::otherParticipant()

### ISSUE THREAD

**Issue by baldemir** [cmgmyr/laravel-messenger#310]
Hi,

When i try to use otherParticipant() function of Thread object i'm getting BadMethodCallException. The problem occurs only on production server, while on my local server there is no problem. 

Is there anything that i'm missing which can cause this error?

Thanks for help in advance,

**Comment by antonkomarev** [comment]
But there is no such method in Thread model. Maybe it's you custom implementation?

**Comment by baldemir** [comment]
Yes, you can't be more right about it. It is a change which is not in documentation. So error occured after composer update. Thanks for that!
