### ISSUE TITLE
Best practice to remove all messages/threads from deleted user

### ISSUE THREAD

**Issue by SPQRInc** [cmgmyr/laravel-messenger#311]
Hello,

is there any best practice to remove all messages a user created when the user is deleted? At the moment I'd search for:

```
Thread::forUser(Auth::id())->latest('updated_at')->get()
```

and loop through the result...?

**Comment by cmgmyr** [comment]
It depends on how your user's model is set up. You could do something like 

```php
$user->participants()->delete();
$user->messages()->delete();
```

To soft delete the participant and message records for the user, but in some cases, the user's name might still be shown - like in the participant's string and/or if the user was the creator. If those are the cases and you want to completely hide them you could 1) force delete the user's participant/message records, or 2) override and adjust the methods on the messenger package models to remove the `withTrashed()` scopes.

I hope that helps 🙂
