### ISSUE TITLE
how to integrate this pkg in case of multiauth baised app

### ISSUE THREAD

**Issue by abdul191993** [cmgmyr/laravel-messenger#315]
I am working on Multiauth app where i want to use this pkg is there any way to use this pkg in a multiauth baised app..????

**Comment by antonkomarev** [comment]
Hi, @abdul191993!
Could you describe your question in more details? What do you mean multi auth and why this package doesn't fit your requirements?

**Comment by abdul191993** [comment]
I am working on a project which involves multiple authentications like it have 4 type of users these users named consultants entrepreneurs.... and each have its own table own model own controllers separate register and login pages.
but in this package one user model is targeted but there are 4 user models with different names and i want that each user exchange massages with each other..
https://www.tutsmake.com/laravel-multi-auth-lara-5-8-5-7-5-6-multiple-authentication/
this is the link for more details if you want more clear concept of multiauth.

**Comment by antonkomarev** [comment]
I might be wrong, but this package not designed to work this way. Each model in this package is exendable, so you can overwrite default behavior with your own.

**Comment by Gummibeer** [comment]
You only have to change the participant model to a polymorph relationship to the user.
This should solve your setup.
