### ISSUE TITLE
Lumen Support

### ISSUE THREAD

**Issue by vaishnavmhetre** [cmgmyr/laravel-messenger#316]
I had a look at the documentation finding that the Lumen support is WIP. Then is this package well able to support Lumen or how long should I wait for any updates on Lumen WIP project (no commits since 2016 probably). I'm building an enterprise application possibly and wish to use your package for it!

**Comment by antonkomarev** [comment]
@vaishnavmhetre if there is something missing for Lumen support - feel free to add PRs. I'm not sure that it's in near future plans.

**Comment by vaishnavmhetre** [comment]
Okay. One more thing. Don't want a full issue just for a simple question.

I'm exploring graphql with laravel, can we have any possible support for graphql (https://github.com/rebing/graphql-laravel) using existing available methods!?

**Comment by antonkomarev** [comment]
IMHO it should be done inside of the application. There is no need to add extra dependency to this package if it's not mandatory.

**Comment by vaishnavmhetre** [comment]
@antonkomarev Okay. Thanks a lot. I'll get in touch if I need some help.

**Comment by cmgmyr** [comment]
@vaishnavmhetre The Lumen API app is just an example project. You should be able to follow the readme and see the changes that I made in the first few commits to get up and running. That said, that example project is pretty old so you might need some tweaks along the way.

**Comment by vaishnavmhetre** [comment]
Sure thing. I'll look into it. Thanks for the support @cmgmyr 😁
