### ISSUE TITLE
Laravel 5.8 Support?

### ISSUE THREAD

**Issue by rkytie** [cmgmyr/laravel-messenger#317]
Can i use on Laravel 5.8?

**Comment by antonkomarev** [comment]
@rkytie yes, it should work. If there are any issues - write about them or make a PR to make it work as expected!

**Comment by rkytie** [comment]
> @rkytie yes, it should work. If there are any issues - write about them or make a PR to make it work as expected!

Ok! I will try, if i can ill share.
