### ISSUE TITLE
laravel-messenger with email notification

### ISSUE THREAD

**Issue by kirie17** [cmgmyr/laravel-messenger#318]
how can i send an email to the recipient whenever i sent a message to them?

**Comment by cmgmyr** [comment]
Once you have a new message you can add a listener, or send a notification to participants. If you are using the example files as a starting point you could add a notification [here](https://github.com/cmgmyr/laravel-messenger/blob/master/examples/MessagesController.php#L107) and [here](https://github.com/cmgmyr/laravel-messenger/blob/master/examples/MessagesController.php#L148). You could also add a model event listener to the message model after you extend it.
