### ISSUE TITLE
Threads: Reply to the message sender only instead of replying to everyone on the thread

### ISSUE THREAD

**Issue by matthewsuan** [cmgmyr/laravel-messenger#319]
Hi,

How can someone reply only to the message sender? Instead of having everyone see the reply.

Say user A initiates a thread with users B,C,D,E as recipients. Now, how can user B responds to user A without CDE knowing about it?

Thanks for the cool package, btw.

**Comment by cmgmyr** [comment]
Hey @matthewsuan, thanks for using the package! Out of the box all participants can view all messages in a thread, but I think you have a few choices.

1. Add something like a `visible_only_to` field to messages, which would include user ids. When you're rendering the messages on the page, then you can check if the current user can see the message. `null` would refer to everyone being able to see it.
2. Add an option/button to create a new thread from a message that would only include the 2 users. Then you'd be able to use the thread as before (as long as you didn't add any participants to it)

No 1 would be more complex, but you could keep the public and private messages in-line, which would cut down on confusion compared to No 2, which would separate out into multiple conversations/threads. So if you go with No 2, you might want to track what the parent/previous thread was so you can always link back to it.

Of course, these are just a few options that you could do and your mileage may vary. I hope that helps!
