### ISSUE TITLE
Searching against created messages.

### ISSUE THREAD

**Issue by damienIN** [cmgmyr/laravel-messenger#32]
Is there any kind of searching implementation in this so that a user can search against their messages?

**Comment by fetch404** [comment]
Hello,

As far as I know, there is no search functionality included. You would have to program this yourself, but it should not be that hard. Just have a basic search controller, then have users search by subject, do a database query, filter the stuff, render it, and you're done.

**Comment by cmgmyr** [comment]
Correct, there aren't any specific search options built in, but you can just extend the query methods/scopes to include different search options.
