### ISSUE TITLE
Laravel 6 Support please?

### ISSUE THREAD

**Issue by hassanazimi** [cmgmyr/laravel-messenger#320]

**Comment by antonkomarev** [comment]
You can make a PR to push it forward. I just updated one of my packages and changes are pretty trivial if there is no `str_` & `array_` helpers in code being used: https://github.com/cybercog/laravel-love/pull/113/files

**Comment by hassanazimi** [comment]
I don't see any `str_` & `array_` anywhere in the code. That change was made in 5.8.

**Comment by igorbabko** [comment]
PR [321](https://github.com/cmgmyr/laravel-messenger/pull/321)

**Comment by davehowson** [comment]
@hassanazimi does this not support Laravel 6? I was planning to use this in Laravel 6 and now I'm not so sure about it. Could you please elaborate on why you opened this issue?

**Comment by hassanazimi** [comment]
@davehowson No it does not, PR 321 hasn't even been merged yet! So this package does not support Laravel 6.

**Comment by antonkomarev** [comment]
I've reviewed PR, it need to be updated.

**Comment by davehowson** [comment]
Does this support Laravel 5.8 though?

**Comment by antonkomarev** [comment]
@davehowson yes tag `2.19` supports Laravel 5.* and 6 versions.
