### ISSUE TITLE
How do I get conversations between two users?

### ISSUE THREAD

**Issue by davehowson** [cmgmyr/laravel-messenger#323]
Apologies for opening an issue regarding this as this is no bug. I just couldn't find any documentation or discussions about this whatsoever. 

How do I use the _scopeBetween_ function to get a list of all the threads that occurred between two user ids?
I need to get a list of all the threads that are present between two users but I cannot figure out what to pass as the $query parameter for the above method.

An example of this method in use would be ideal.

Thanks in advance.

**Comment by davehowson** [comment]
Just read about Scopes in Laravel and decided to call the function like this

```php
public function between()
{
    $threads = Thread::between([1, 3]);
    return $threads;
}
```

but this results in a `Object of class Illuminate\Database\Eloquent\Builder could not be converted to string` error.
Anything wrong with what I did?

**Comment by cmgmyr** [comment]
hey @davehowson, scopes in Laravel are a little bit "magical". You don't need to include `scope` when you call it, and the `$query` is automatically filled in my Laravel for you. So all you need to do is call

```php
$threads = Thread::between([1, 3]);
```

Please let me know if you have any other questions 🙂

**Comment by davehowson** [comment]
@cmgmyr I tried this, but it gives me the following error.

`Object of class Illuminate\Database\Eloquent\Builder could not be converted to string`

Stack Trace : [https://pastebin.com/gfnPLBgz](https://pastebin.com/gfnPLBgz)

The function I use to call the between method is:

```php
public function between()
{
    $threads = Thread::between([1, 3]);
    return $threads;
}
```

I use `"cmgmyr/messenger": "^2.19"` with `"laravel/framework": "5.8.*"`

**Comment by davehowson** [comment]
Apologies. I just realized that the issue is not with the `scopeBetween` function but with the fact that I am returning a Builder object. I fixed it by adding the following.

`$threads = Thread::between([7, 5])->get();`

Thank you @cmgmyr for your support and for your amazing library. 
:)
