### ISSUE TITLE
File upload possibility

### ISSUE THREAD

**Issue by daniellord32** [cmgmyr/laravel-messenger#326]
Hey,

I am interested in using this package for my project but I am wondering if it would be possible for the users to be able to upload files that another user would be able to download.

thank you

Daniel

**Comment by texnika01** [comment]
this is not necessary. in each message there may be a link to the file or resource to be downloaded or uploaded.

**Comment by daniellord32** [comment]
I would agree, except the client would like to make it as easy as possible for their user base. It's a fairly large user base and quite a few would not be tech savy so to speak.

**Comment by cmgmyr** [comment]
Hi @daniellord32, good question! Yes, you can certainly do that. 

First, you'd want to create a new `Message` model which extends the [packaged one](https://github.com/cmgmyr/laravel-messenger/blob/master/src/Models/Message.php). 

Next, [update the config file](https://github.com/cmgmyr/laravel-messenger/blob/2ba36bac5f14e0780c553bd7af138bfa859ed8f0/config/config.php#L7) to point to your new custom Message model. 

Finally, you can add whatever functionality/data onto the model as you need. You'd probably want a new migration for the file information per message, or another relationship for a one-to-one, or one-to-many (if you want multiple files per message). Then your new UI and controller would need to account for the file form fields and handling those.

I hope that helps, please let me know if you have any other questions.
