### ISSUE TITLE
$thread->participantsString() Passing 'name' issue.

### ISSUE THREAD

**Issue by more-yogesh** [cmgmyr/laravel-messenger#327]
**Laravel version 6.6.0**

In my users' tables I have only `email, password, created_at ` columns.  It does not contain any name, first_name, last_name column and I think due to that I am facing error

```
Facade\Ignition\Exceptions\ViewException
Trying to get property 'body' of non-object (View: D:\xampp\htdocs\corporate\resources\views\chat\messenger\partials\thread.blade.php)
http://localhost:8000/messages
```
I tried  `{{ $thread->participantsString(Auth::id(), ['email']) }}` email and id column but didn't worked for me.

**Comment by cmgmyr** [comment]
Hi @more-yogesh,
`{{ $thread->participantsString(Auth::id(), ['email']) }}` works for me in a new `6.9.0` project. Your error is about the `body` property which, I'm guessing, is and issue with the `$thread->latest_message->body` somewhere, or similar?

**Comment by more-yogesh** [comment]
Thanks, @cmgmyr for the response let me check this out :)
