### ISSUE TITLE
Migrations foreign key not set 

### ISSUE THREAD

**Issue by aliwesome** [cmgmyr/laravel-messenger#329]
Hi, 
Why migrations are not merged? they can be merged just in case adding `$table->softDeletes()` into the previous migrations instead of making new one.
also there is problem that foreign key is not set.

**Comment by cmgmyr** [comment]
This was done mainly for backward compatibility. If someone installed and ran the migrations before the soft-deletes were added, then we added the soft-deletes to the same migration file then that user wouldn't get them added to the correct tables. Maybe if we end up working on a V3 we'll squash them down, but for now, they can remain separate. 

I initially had foreign keys set up for the package, but it introduced too many issues for users, so I ended up dropping them. Users of the package can always add foreign keys themselves if they feel the need.
