### ISSUE TITLE
L5  name in 'user' table

### ISSUE THREAD

**Issue by UnrulyNatives** [cmgmyr/laravel-messenger#33]
I'd suggest to modify the VIEW files to comply with standard user table in L5. 
It containts 'name' column for user names. 'first_name' and 'last_name' should be optional and for reference only.

I can take the trouble to do the changes if you confirm here that my pull request would be accepted.

**Comment by kfrankperson** [comment]
:+1: First and last name should be removed and the default laravel users table should be used, makes installing the package a lot easier for new projects.

**Comment by cmgmyr** [comment]
Thanks for the suggestion. This has been updated in the latest `2.4` release
