### ISSUE TITLE
The MessengerController example seems to return all users.

### ISSUE THREAD

**Issue by Rhym** [cmgmyr/laravel-messenger#331]
I'm using the example controller from the examples folder, and it seems to return all users that aren't participants rather than users who are:

https://github.com/cmgmyr/laravel-messenger/blob/master/examples/MessagesController.php#L57

**Comment by cmgmyr** [comment]
Hi @Rhym, yes that is intended and completely optional. The idea is that you could see anyone who isn't on the current thread and [include them](https://github.com/cmgmyr/laravel-messenger/blob/2ba36bac5f14e0780c553bd7af138bfa859ed8f0/examples/views/messenger/partials/form-message.blade.php#L11-L19) in the view. If you don't want this functionality there is no harm in removing it.

The example files are just to show what is possible, but not very performant if used as-is. I'd recommend to pare down on anything you don't need.

**Comment by Rhym** [comment]
@cmgmyr Ah, my mistake completely. Thank you for your prompt response. Have a great day!
