### ISSUE TITLE
Laravel 7 support

### ISSUE THREAD

**Issue by timramseyjr** [cmgmyr/laravel-messenger#332]
Is there plans to support Laravel 7?

**Comment by antonkomarev** [comment]
Yes. But you always could speed it up by providing Pull Request.

**Comment by timramseyjr** [comment]
> Yes. But you always could speed it up by providing Pull Request.

Fair enough.  I will see about doing this at the beginning of next week.

**Comment by messerli90** [comment]
Just created a PR #333

**Comment by eduarguz** [comment]
@laravel-shift

**Comment by jasonmccreary** [comment]
@eduarguz, looks like @messerli90 has it in #333. However, if there is more to do, let me know.

**Comment by eduarguz** [comment]
> @eduarguz, looks like @messerli90 has it in #333. However, if there is more to do, let me know.

Sorry, I was testing how it worked  😬  
amazing work Jason, Thanks

**Comment by cmgmyr** [comment]
Thanks all! This has been merged, but I'll hold off on tagging for a few days to make sure there are no issues. You can use `v2.x-dev` in the meantime.

**Comment by cmgmyr** [comment]
`2.20` has been tagged 🎉
