### ISSUE TITLE
Getting Same thread as many times as message is present when used Thread::forUser()

### ISSUE THREAD

**Issue by amyth74** [cmgmyr/laravel-messenger#335]
![image](https://user-images.githubusercontent.com/28001104/76926573-d4407080-6904-11ea-97b9-a9a84b92db5f.png)
![image](https://user-images.githubusercontent.com/28001104/76926621-ecb08b00-6904-11ea-97d5-874f44d707ba.png)

**Comment by cmgmyr** [comment]
Hi @amyth74,
I'm not seeing that in my tests. Can you tell me what version of Laravel and the package you are using?
