### ISSUE TITLE
Help get a list of methods available in the package

### ISSUE THREAD

**Issue by giantthinker** [cmgmyr/laravel-messenger#336]
Hello Chris, thanks for this amazing package. Please can you help me get a list of methods available to me?
Thanks.

**Comment by cmgmyr** [comment]
Hi @giantthinker, thanks for using the package!

No, I don't have a documented list of available methods, but you can view the source of the models and user trait [here](https://github.com/cmgmyr/laravel-messenger/tree/master/src). Please let me know if you need help and I can hopefully point you in the right direction.
