### ISSUE TITLE
sending a message logs me into account assigned to users.id = 1

### ISSUE THREAD

**Issue by UnrulyNatives** [cmgmyr/laravel-messenger#34]
As in title. 

I use newest Laravel 5 with these mods:
- i changed last_name and first_name in your app into 'name', to make your package compatible with L5
- my main admin account is not id = 1 - for security reasons

**Comment by kfrankperson** [comment]
You need to use your own authentication system as the comment on the construct in the example controller says.


https://github.com/cmgmyr/laravel-messenger/blob/master/src/Cmgmyr/Messenger/examples/MessagesController.php#L15

**Comment by UnrulyNatives** [comment]
The error was unrelated to your package. Sorry.
