### ISSUE TITLE
Upgrade to Laravel 7

### ISSUE THREAD

**Issue by zagovorichev** [cmgmyr/laravel-messenger#340]
Hello,

In the code we have
https://github.com/cmgmyr/laravel-messenger/blob/master/src/Models/Message.php#L32
without strict types declared, but in the laravel:
protected array $fillable = [];

**Comment by cmgmyr** [comment]
Hi @zagovorichev,
Sorry, I'm not sure I understand the issue. It appears that [Laravel 7's](https://github.com/laravel/framework/blob/eacc34162b4cd7c1648f3029e8861e3add01f9ef/src/Illuminate/Database/Eloquent/Concerns/GuardsAttributes.php#L14) signature is the same. Please feel free to add more information above and a code snippet and I can take another look.

**Comment by zagovorichev** [comment]
yes, sure, @cmgmyr , sorry, I thought it is clear:
    `protected $fillable = ['thread_id', 'user_id', 'body'];` in your code inherits this:
`protected array $fillable = [];` from the laravel

so, I've gotten `PHP Fatal error:  Type of Cmgmyr\Messenger\Models\Message::$dates must be array (as in class Illuminate\Database\Eloquent\Model)` error

**Comment by zagovorichev** [comment]
Now I'm looking for the place, why do I have this strict types :)

**Comment by zagovorichev** [comment]
Interesting, it was in the laravel framework v7.7.1, but after the update I have 7.13 and now I need to fix all my code, because there are no strict types declared, really weird :)

thank you for response!

**Comment by cmgmyr** [comment]
Thanks for the update! I have noticed PHPStorm being a little more aggressive in its reformatting/refactoring actions. Maybe a bug, or intended, but just something to look out for.
