### ISSUE TITLE
Remove messages older than a certain days

### ISSUE THREAD

**Issue by omidMolaverdi** [cmgmyr/laravel-messenger#341]
cmgmyr messenger is a great messaging package for laravel.Thanks a lot.

 I need to remove messages older than 10 days and the corresponding threads (if empty). Can you please advice?

**Comment by cmgmyr** [comment]
Thanks for using the package!

I'd probably create a scheduled job/cron to delete the messages, then check and delete the threads if empty.

**Comment by omidMolaverdi** [comment]
I do not actually know how to do it.

I use the query below to remove messages older than 10 days. But how can I remove the participants and threads?
DB::table('messages')
            ->select('id')
            ->whereRaw('updated_at < NOW() - INTERVAL 10 DAY')->delete();

**Comment by omidMolaverdi** [comment]
Can you please provide some clues, I really appreciate.

**Comment by omidMolaverdi** [comment]
hello
