### ISSUE TITLE
Call to undefined method User::addEagerConstraints()

### ISSUE THREAD

**Issue by diegomagikal** [cmgmyr/laravel-messenger#342]
Using
**Laravel v7.X**
**laravel-messenger v2.20**

Hello,

I get this error when using the `creator` relationship from `Thread` model:

`Call to undefined method User::addEagerConstraints()`

I'm trying to get the creator id in `show.blade.php`, adding the following code in `MessagesController`:

`$thread = Thread::with('creator')->findOrFail($id);`

**Comment by cmgmyr** [comment]
Hi @diegomagikal,
The reason for this is because `creator()` isn't a relationship on the `Thread` model, but just a getter method. So you'll have to get the thread first, then call for the creator.

```php
$thread = Thread::findOrFail($id);
$creator = $thread->creator();
```

if you'd like to eager load the users, you can do that with

```php
$thread = Thread::with('participants.user')->findOrFail($id);
```
