### ISSUE TITLE
How can I call the calss?

### ISSUE THREAD

**Issue by omidMolaverdi** [cmgmyr/laravel-messenger#343]
When I put the function {{Thread::userUnreadMessagesCount(auth()->user()->id)}} in the view I get the error below:

local.ERROR: Class 'Thread' not found

How can I resolve please?

**Comment by pvdptje** [comment]
You are probably missing a use statement.

**Comment by omidMolaverdi** [comment]
@pvdptje thanks very much for your reply. That is exactly what I do not know. What should I put in use?

**Comment by omidMolaverdi** [comment]
is there any update on this issue please?

**Comment by pvdptje** [comment]
At the top of your PHP file, add this line:

`use Cmgmyr\Messenger\Models\Thread`

Let me know if that helps.

**Comment by omidMolaverdi** [comment]
Thanks. It works now but a silly question, why it does not return the number of unread messages?

**Comment by pvdptje** [comment]
Not without seeing any code

**Comment by omidMolaverdi** [comment]
Sorry for not being clear. The code is like:

```
$uid = auth()->user()->id;
 $a = new Thread();
    $urm = $a->userUnreadMessagesCount($uid);
```

**Comment by pvdptje** [comment]
Try calling the method staticly, instead of instanting a new Thread object, like this:

`$count = Thread::userUnreadMessagesCount( auth()->user()->id );`

**Comment by omidMolaverdi** [comment]
Thanks. If I call the function as you suggested, I get:

local.ERROR: Non-static method Cmgmyr\Messenger\Models\Thread::userUnreadMessagesCount() should not be called statically

**Comment by omidMolaverdi** [comment]
Thanks a lot. I am already using the sample files. The problem that I trying to solve is that I want to show the unread message counter in another view (like in the main menu of the website). So I call the function userUnreadMessagesCount()  outside the MessagesController.

**Comment by pvdptje** [comment]
And if you call the `userUnreadMessages` method, do you get any results at all?

**Comment by omidMolaverdi** [comment]
If I call $urmessagesThread =  Thread::userUnreadMessages( auth()->user()->id );

I get the error below:
local.ERROR: Non-static method Cmgmyr\Messenger\Models\Thread::userUnreadMessages() should not be called statically

**Comment by pvdptje** [comment]
Then call it not staticly, just like you did before

**Comment by omidMolaverdi** [comment]
But in the example file provide I have {{ $thread->userUnreadMessagesCount(Auth::id()) }} that returns the unread messages for a thread. It seems that I am missing something

**Comment by omidMolaverdi** [comment]
Thanks a lot. If I run
```

    $a = new Thread();
    $urmessagesThread =  $a->userUnreadMessages( auth()->user()->id ); 
```
I get:
local.ERROR: Object of class Illuminate\Support\Collection could not be converted to int

**Comment by omidMolaverdi** [comment]
Okay my bad I had  $urmessagesThread>0 that was wrong. So the code below returns []

```
 $a = new Thread();
    $urmessagesThread =  $a->userUnreadMessages( auth()->user()->id ); 
```

**Comment by pvdptje** [comment]
That problaby means there are no unread messages.  Are you 100% sure there are unread messages?

**Comment by omidMolaverdi** [comment]
It seems there are. When I login as user A, there is no new message that is right (as I just sent messages). However, when I login as user B and go to the threads, there is a little message saying that I have two new messages. But I cannot retrieve the number of new messages with the code below:

$a = new Thread();
    $urmessagesThread =  $a->userUnreadMessagesCount( auth()->user()->id );

**Comment by omidMolaverdi** [comment]
Maybe a workaround is to get threads ids and iterate (and add up) with userUnreadMessagesCount?

**Comment by pvdptje** [comment]
I think the problem is in the fact that your Thread object has no information behind it, it didn't load anything from the database.

I would suggest something like this:

1. Fetch all the threads this user participates in
2. Per thread, count the total unread messages for the user

**Comment by omidMolaverdi** [comment]
I can simply get the threads a user has participated from the df. However, not sure how to iterate

**Comment by pvdptje** [comment]
Assuming you have fetched the threads, you could do something like this:

`   $threads = [];

        $totalUnreadMessages = 0;
        foreach($threads as $thread){
            $totalUnreadMessages += $thread->userUnreadMessagesCount(Auth::id());
        }

        return $totalUnreadMessages;`

**Comment by omidMolaverdi** [comment]
Oh thanks a lot. I highly appreciate your support

**Comment by omidMolaverdi** [comment]
very sorry


I still can not make it running :(

```
use Cmgmyr\Messenger\Models\Thread;

$uid = auth()->user()->id;

    $threads = DB::table('participants')->where('user_id', $uid)->get();

    $totalUnreadMessages = 0;
    foreach ($threads as $thread) {
        $totalUnreadMessages += $thread->userUnreadMessagesCount(Auth::id());
    
```

**Comment by pvdptje** [comment]
Add this trait to your user model: https://github.com/cmgmyr/laravel-messenger/blob/master/src/Traits/Messagable.php

And fetch your threads like this:

`$threaths = auth()->user()->threads`

**Comment by omidMolaverdi** [comment]
Horray It now works. I put the function below for others if they like and DEEPLE appreciate your help.

function getUnreadMessages()
{
    if (!Auth()->check())
        return (0);
    $uid = auth()->user()->id;

    $threads = Thread::forUser($uid)->latest('updated_at')->get();
    $totalUnreadMessages = 0;
    foreach ($threads as $thread) {
        $totalUnreadMessages += $thread->userUnreadMessagesCount($uid);
    }
    return ($totalUnreadMessages);
}

**Comment by pvdptje** [comment]
You're welcome and well done!
