### ISSUE TITLE
where is the doc

### ISSUE THREAD

**Issue by CreationLee** [cmgmyr/laravel-messenger#344]
Where is the documention, i haven't found one

**Comment by cmgmyr** [comment]
Hey @CreationLee, I'm sorry but there isn't any official documentation besides the [readme](https://github.com/cmgmyr/laravel-messenger/blob/master/readme.md), [example files](https://github.com/cmgmyr/laravel-messenger/tree/master/examples) and docblock comments in the [src](https://github.com/cmgmyr/laravel-messenger/tree/master/src).

**Comment by CreationLee** [comment]
@cmgmyr thanks
