### ISSUE TITLE
arcanedev/laravel-messenger does not support Laravel 7

### ISSUE THREAD

**Issue by Hamza-Liaqat1** [cmgmyr/laravel-messenger#345]
`Moving from laravel 6 to 7x getting this error, `arcanedev/laravel-messenger 7.2.0 requires arcanedev/support ^5.1`

**Comment by cmgmyr** [comment]
That must be a fork of this package or some alteration, you'll need to make an issue on that repo - https://github.com/ARCANEDEV/LaravelMessenger
