### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by farad4y** [cmgmyr/laravel-messenger#346]
https://github.com/cmgmyr/laravel-messenger/blob/8fa8d3634332923cc8530298883fbd55073ecb38/src/Models/Message.php#L104

Thanks for package but, this query is some kind of nightmare for SQL, If you have millions of messages and user, the app will be fucked up. We can't use this query without caching.

**Comment by cpy466** [comment]
> 
> 
> https://github.com/cmgmyr/laravel-messenger/blob/8fa8d3634332923cc8530298883fbd55073ecb38/src/Models/Message.php#L104
> 
> Thanks for package but, this query is some kind of nightmare for SQL, If you have millions of messages and user, the app will be fucked up. We can't use this query without caching.

Don't bother using this package for real life apps. Take a look at $thread->creator()->name for example, your queries will duplicate to the sky if you have only 200 messages. Not to mention unread .. etc. Sorry guys but it is !

**Comment by cmgmyr** [comment]
Thanks for the feedback. I realize there needs to be some performance improvements to the package. I haven't had the time lately to work through them. I'm sure with moving forward with the latest Laravel versions we could utilize newer features as well. Always happy to take a look at PRs 🙂

**Comment by cpy466** [comment]
> Thanks for the feedback. I realize there needs to be some performance improvements to the package. I haven't had the time lately to work through them. I'm sure with moving forward with the latest Laravel versions we could utilize newer features as well. Always happy to take a look at PRs 🙂

@cmgmyr Thank you. :)
