### ISSUE TITLE
Upgrade to Laravel 8

### ISSUE THREAD

**Issue by WimDeMeester** [cmgmyr/laravel-messenger#349]
I can not install cmgmyr/laravel-messenger in laravel 8. I get the following error:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install laravel/framework 5.7.x-dev
    - Conclusion: remove cmgmyr/messenger 2.20|install laravel/framework 5.7.x-dev
    - Conclusion: don't install cmgmyr/messenger 2.20
    - Conclusion: don't install cmgmyr/messenger 2.19
    - Conclusion: don't install cmgmyr/messenger 2.18
    - Conclusion: don't install cmgmyr/messenger 2.17
    - Conclusion: don't install laravel/framework v8.0.3
    - Conclusion: don't install laravel/framework v8.0.2
    - Conclusion: don't install laravel/framework v8.0.1
    - Installation request for cmgmyr/messenger ^2.17 -> satisfiable by cmgmyr/messenger[2.17, 2.18, 2.19, 2.20, v2.x-dev].
    - Conclusion: don't install laravel/framework v8.0.0

**Comment by cmgmyr** [comment]
@WimDeMeester the `master` branch has been updated to install the package with Laravel 8. You can update your `composer.json` to use `dev-master`. I'll plan on tagging it next week if there are no issues that are reported.

**Comment by titizali** [comment]
Laravel 8 using dev-master gives this error:

 @php artisan package:discover --ansi

   Error

  Class 'App\Models\User' not found

  at vendor/cmgmyr/messenger/src/MessengerServiceProvider.php:102
     98▕
     99▕         Models::setUserModel($model);
    100▕
    101▕         Models::setTables([
  ➜ 102▕             'users' => (new $model)->getTable(),
    103▕         ]);
    104▕     }
    105▕ }
    106▕

      +9 vendor frames
  10  [internal]:0
      Illuminate\Foundation\Application::Illuminate\Foundation\{closure}()

      +5 vendor frames
  16  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error cod
e 1

**Comment by cmgmyr** [comment]
@titizali can you try uncommenting out [this line](https://github.com/cmgmyr/laravel-messenger/blob/master/config/config.php#L5) in your published config file?

**Comment by cmgmyr** [comment]
Just tagged `2.21` and updated release notes
