### ISSUE TITLE
Add remove thread function

### ISSUE THREAD

**Issue by LenkaSoma** [cmgmyr/laravel-messenger#352]
Hello,

First of all, congratulations your package is really cool!
I would like to know if there would be an upcoming update that incorporated being able to delete threads?

Currently I am not able to develop this myself (I only do it from the front) hence my request, otherwise don't worry it's not very serious: x

Thank you,

**Comment by Cedric331** [comment]
Hello
If you need a function to delete a threads, here is the code:

$id est l'id du thread

    public function delete($id)
    {
        try {
            $thread = Thread::findOrFail($id);
        } catch (ModelNotFoundException $e) {
            Session::flash('error_message', 'Error');
            return redirect()->route('messages');
        }

        $thread->delete();
        return redirect()->back();
    }

Hope this helps you

**Comment by LenkaSoma** [comment]
Thank you very much, would it be possible to delete the posts and participants related to the deleted topic at the same time? : o

**Comment by LenkaSoma** [comment]
For those looking to do like me, here's how:

```
public function delete($id)
    {
        try {
            $thread = Thread::findOrFail($id);

        } catch (ModelNotFoundException $e) {
        Session::flash('error_message', 'Error');
        return redirect()->route('messages');
        }

    $message = Message::where('thread_id', $thread->id)->delete();
    $participants = Participant::where('thread_id', $thread->id)->delete();

    $thread->delete();

    return redirect()->back();
    }
```

However this will not delete them completely (due to SoftDeletes), if you want to delete them from the database, use `forceDelete()` instead of `delete()`.

**Comment by cmgmyr** [comment]
Hi @LenkaSoma, thanks for the question! I specifically didn't include deleting in this package so that the developer could choose how to handle it - since all apps will handle deletions or hiding/archiving differently. Glad you got it worked out and thanks for using the package!
