### ISSUE TITLE
Not see the user name before the first reply

### ISSUE THREAD

**Issue by omidMolaverdi** [cmgmyr/laravel-messenger#358]
Hi great folks.

Is there any easy way to hide the user name in the thread before the first reply?

**Comment by cmgmyr** [comment]
The blade files are just for example and sometimes to use as a starter. Feel free to add any logic you need to hide/show information.

**Comment by omidMolaverdi** [comment]
Thanks @cmgmyr. I have a bit of difficulty with the logic. do you have any recommendation please?

**Comment by cmgmyr** [comment]
You could probably change [this line](https://github.com/cmgmyr/laravel-messenger/blob/9d6b5443792ee573e4f229206b0ac323395bc3c3/examples/views/messenger/partials/messages.blade.php#L7) to something like this.

```php
@if($thread->messages->count() > 1)
<h5 class="media-heading">{{ $message->user->name }}</h5>
@endif
```

But I'd probably create a new variable in the controller and pass it to the views so you only need to make that calculation once.

```php
// Controller
$shouldShowUserNames = $thread->messages->count() > 1;

// View
@if($shouldShowUserNames)
<h5 class="media-heading">{{ $message->user->name }}</h5>
@endif
```
