### ISSUE TITLE
Feature proposal

### ISSUE THREAD

**Issue by UnrulyNatives** [cmgmyr/laravel-messenger#36]
As Admin of my project I'd be happy to send a message not to particular users, but to say... all users with role 'Moderator'. 

In my case I use this package: https://github.com/romanbican/roles

Is there any way the feature can be done from your package side?

**Comment by kfrankperson** [comment]
I don't think it is worth adding as it would add another layer of complexity and everyone has their own method of authentication and roles.

**Comment by avlastenok** [comment]
That Would be really easy to do by you. 
It does not belong on a package to do something through another package the idea seems silly. 
You can find a list of people with a certain role through User::role('moderator')->get() there you get all their info the rest should be quite straight forward.

**Comment by cmgmyr** [comment]
I agree with the last 2 comments. This does not belong in the package, but can be easily added on in the parent app
