### ISSUE TITLE
v2.23 Breaks Non-Int User IDs

### ISSUE THREAD

**Issue by lorenzoaiello** [cmgmyr/laravel-messenger#365]
I use `UUID` as the primary key type on my user models and v2.23 has a regression that causes it not to work any longer.

Git Blame: https://github.com/cmgmyr/laravel-messenger/blob/be9d58a619a11a2b93f6a492536d825db5796def/src/Models/Message.php#L109

Sample Error:

```
TypeError
Cmgmyr\Messenger\Models\Message::scopeUnreadForUser(): Argument #2 ($userId) must be of type int, string given, called in /laravel/framework/src/Illuminate/Database/Eloquent/Model.php on line 1475 (View: /resources/views/test.blade.php) 
```

**Comment by cmgmyr** [comment]
Hi @lorenzoaiello, thanks for reporting! I pushed a commit to the `master` branch that should fix the regression. Can you pull in `dev-master` in your `composer.json` file and let me know if the issue is fixed?

**Comment by lorenzoaiello** [comment]
@cmgmyr thanks for the quick turnaround - working for me from `master` as expected. Thanks

**Comment by cmgmyr** [comment]
Just tagged a release for `2.24.0`. Please let me know if you have anything else come up. Thanks so much for using this package!
