### ISSUE TITLE
How to get the creator of thread?

### ISSUE THREAD

**Issue by thehamsterofgod** [cmgmyr/laravel-messenger#38]
I tried this:
```
$thread->messages()->first()->user()->first()
```
it works but is there a better way to get the creator of thread? something specific?

**Comment by cmgmyr** [comment]
Unfortunately that's the only option at the moment. I can see where this could be helpful though. I'll add a helper method that will make this a little easier. Something like `$thread->creator()` or something.

**Comment by thehamsterofgod** [comment]
Thanks that would be very useful and neat :+1:
