### ISSUE TITLE
Add column name to the config instead of hard-coding it into the package src

### ISSUE THREAD

**Issue by askaoru** [cmgmyr/laravel-messenger#39]
I think that for something that is not included in the package itself and might be different for each people that uses this package should be easily customized via config. For example in my case, I do not have name column in my users table, i have instead a username column. 

Sure it can be changed easily in the source but it would get overwritten each time the package got updated.

**Comment by cmgmyr** [comment]
Sorry, I'm not sure what you mean. For `$thread->participantsString()` you can assign your own columns if `name` doesn't work for you. So something like this: `$thread->participantsString($userId, ['username'])` or `$thread->participantsString($userId, ['first_name', 'last_name'])`.

Does that help?

**Comment by askaoru** [comment]
Yep, that's how I did it too. But then the next time the package got updated, it will be overwritten back to original value. So i think it'll be nicer to add it to config into something like this

    <?php
    return [
        // Define your application user model  	
        'user_model' => 'App\User',
    
        // Database column that defines your users identity
        // Example: 'name', 'username'
        'user_name' => 'name',
    ];

This would ease up the package installation for people that uses custom users table.
That's just my opinion on this.

**Comment by cmgmyr** [comment]
What would be overwritten? The use of `$thread->participantsString()` would be in your controller or views which wouldn't be overwritten if you updated the package.

**Comment by avlastenok** [comment]
I think your a bit off on this, Chris is not telling you to edit his package but rather your view file as
Composer will not update your view files, so just update the line with:
{!! $thread->participantsString(Auth::id()) !!}
and make it something like:
{!! $thread->participantsString(Auth::id(), ['username']) !!}
if it was username you had instead of name.
If this still comes with an error go into your cmd/console and write: php artisan cache:clear I had a problem with the cache not updating so clearing it will help.

**Comment by askaoru** [comment]
Ah alright.. i guess I've been looking around the wrong files.. Still quite a newbie here.. Thanks for your time and your great package @cmgmyr , and also @avlastenok for clearing things up. You may close this issue.

**Comment by cmgmyr** [comment]
No problem at all! Thanks for using the package and I'm glad you like it. If you have any other questions just let me know.
