### ISSUE TITLE
Participant model last_read property casts MISSING under Laravel 10

### ISSUE THREAD

**Issue by deviddev** [cmgmyr/laravel-messenger#393]
**Hi!**

In Laravel 10 the **$dates** model property **was removed**, so the Participants model **last_read** property **is not casts to datetime** _(Carbon instance)_, this will be string.
[Laravel 10 Upgrade Guide](https://laravel.com/docs/10.x/upgrade#model-dates-property)

This makes exceptions if u want to use last_read with Carbon methods.

### Solution
Just add "direct' casts to last_read property in Participant model.
```
protected $casts = [
    'last_read' => 'datetime'
];
```

**Comment by cmgmyr** [comment]
Thanks!
