### ISSUE TITLE
Laravel 5.1

### ISSUE THREAD

**Issue by Kryptonit3** [cmgmyr/laravel-messenger#42]
for laravel 5.1 you will need to make the following change to `Messagable.php` 

find
~~~
$participants = Participant::where('user_id', $this->id)->lists('last_read', 'thread_id');
~~~

replace with
~~~
$participants = Participant::where('user_id', $this->id)->lists('last_read', 'thread_id')->all();
~~~

When using `lists` in 5.1, an object (collection) is returned. Your logic calls for an array so to make data an array `all()` must be added after `lists()`

[source](http://laravel.com/docs/master/upgrade)

**Comment by opheliadesign** [comment]
Need fix for this ASAP, using this package throughout a project and this is breaking it.

**Comment by Kryptonit3** [comment]
@opheliadesign did my changes not fix it for you? Fork this and change them and install your fork repo until it is fixed.

**Comment by cmgmyr** [comment]
I'll be working on this shortly

**Comment by cmgmyr** [comment]
Ok, we should be in good shape now. Please update to the latest `2.5.1` release and let me know if anyone has any issues. The update will work with 5.0 and 5.1+
