### ISSUE TITLE
Send message to all users

### ISSUE THREAD

**Issue by alexeitav** [cmgmyr/laravel-messenger#47]
Hello there,

Is there a way to send a message to all users on the system, without the need to select one by one?
Thanks in advance.

Alexei

**Comment by FrankDupree** [comment]
When looping through all the users, enable the check property in the checkbox to true check="checked", then you could also go ahead and set the visibility to hidden. That way, you don't display all the users and thier check boxes checked in the browser.

**Comment by cmgmyr** [comment]
There isn't a message all users function right now. However, you could just use the `$thread->addParticipants()` method and add all user id's to that. Just get all of the user id's from the database, then pass it into that function as an array.

I'm assuming that this would be more of an admin function, so I would probably create an admin only route/method that would do this automatically. That way you wouldn't have to worry about checking all of the user boxes or messing with any additional html.

I'm going to close this as an issue for now, but please feel free to comment if you have any additional questions/comments.
