### ISSUE TITLE
Too much logic in the models and controllers.

### ISSUE THREAD

**Issue by RaoulDijksman** [cmgmyr/laravel-messenger#49]
Hey guys,

I would like to make a pull request to move out a lot of the logic in the models. I recommand a more SOA/DDD approach: 

**Models:** I think that the model should represent an entity. With Laravel, I only use the model class to add things like `fillable`, `guarded`, `table` and the relations. (If the Repository Pattern isn't used,  the model would also have the save, update, find, etc methods/scopes).

**Services:** The home of global logic, containing functions that are used throughout the app. This service class can then be a single point of entry and give the app a lot of the required functionality, as an example, functions like `sendMessage`, `createThread` would handle the the required logic to send a message or to create a new thread.  Making the controller of the app slim, DRY and less error prone.

A service class will also allow the creation of a facade. 

How does this sound? Would you be interested in moving logic into a separate class?

Raoul

**EDIT:** I forgot to mention that a service class also allows for beter testing and will allow for beter eager loading! At the moment eager loading in this package is a big problem if the default functions are used.

**Comment by override-chaos** [comment]
:+1: This gets my vote !

**Comment by cmgmyr** [comment]
Yes, I have toyed around with this and I would personally like this a lot better. The original idea of this package was to just keep it simple, open, and as easy to use in Laravel as possible. New users look to controllers and models to see what's going on and might get confused with more abstraction. I'm hesitant to make this package more abstracted and much less "simple".

So with that, in my mind we have two options:

1. Do it anyways with this package
2. Make a new package, DDD it up, and maybe offer it to other frameworks too. Similar to what [Cartalyst](https://cartalyst.com/) does with it's packages.

Thoughts?

**Comment by avlastenok** [comment]
my vote is on option 1, people should learn not to put all the logic in the models and it's not too hard to look through the code anyway they should know that they have it all available under the vendor folder.

**Comment by override-chaos** [comment]
I would go with option 1, but create a new version with the new improvements (2.x.x) and leave the old version there as legacy (1.x.x) just support bug fixes.

This way people can use the old "easier" method or the newer version package.

**Comment by RaoulDijksman** [comment]
I would go with option 1. I agree that this package needs to remain simple. But i believe by adding a service class it will become a simpler. 
@override-chaos Isn't this package already at 2.x? Lets make this a 3.x version branch.

**Comment by cmgmyr** [comment]
Ok, let's move forward with option 1. What about branching from the current master to a v2 branch, and keeping this new v3 version on master (develop branch initially)?

**Comment by RaoulDijksman** [comment]
@cmgmyr Sounds great .

So this is how i see it:
Thread is the aggregate. This means the first step for an app would be to get a thread object(s).
`$threads = $messenger->getAllTreadsForUser()`
`$threads = $messenger->getThreadsBetweenUsers()`

All methods are called on thread objects. 
`$thread->sendMessage()`
`$thread->addParticipant()`

This is a very OOP way of handling it. What do you think?

**Comment by RaoulDijksman** [comment]
The functions that are requiered as entry point that i can think of are:
```php
public function getThread($threadId)
public function getAllThreads()
public function getAllTreadsForUser($userId)
public function getUpdatedTreadsForUser($userId)
public function getThreadsBetweenUsers($participants)
public function createThread($participants)
```

**Comment by cmgmyr** [comment]
Thanks everyone, I'm just doing some housecleaning right now. `v2` and `develop` branches have been made. Also added a milestone for `v3` to better track the changes that need to be done. I'm going to close this issue in favor of #51. I'll add everything into that issue shortly. Thanks for all of the input so far!
