### ISSUE TITLE
Viewing messages that you aren't participating in

### ISSUE THREAD

**Issue by caseylouisee** [cmgmyr/laravel-messenger#50]
I have looked through the code and am using it in my current project but am yet to find a method that blocks a user from seeing other people's messages, if they are not in the thread participants list. I can probably create something myself but as a message system I feel this should be implemented at the start.

**Comment by caseylouisee** [comment]
This is my error, plenty of methods exist throughout the program to enable this feature. Apologies to the creator!

**Comment by FrankDupree** [comment]
lol

**Comment by caseylouisee** [comment]
also apologies for the repeated issue post as I haven't really used github before I didn't know how to view the closed issues! All is fixed now and thanks for the great messaging package!

**Comment by FrankDupree** [comment]
its understandable, good luck with what it is you working on.
