### ISSUE TITLE
API Planning

### ISSUE THREAD

**Issue by cmgmyr** [cmgmyr/laravel-messenger#51]
This is to discuss the basics of the new API and classes at a high level. Class/method/pseudo code examples would also be helpful. We got a start in #49, but let's continue here. I'll put an initial gist together and update this shortly.

**Comment by RaoulDijksman** [comment]
I've made a little gist of the possible APIs. Ofcourse this is only a gist and doesn't have tests.

**Comment by cmgmyr** [comment]
Looks good so far! I don't know why GH duplicated it 3 times, that's weird. I've duplicated this code on my machine and made a few small changes. I'll play with it a little more before I push anything up. Hopefully I'll get to that today. Thanks for the help so far!
