### ISSUE TITLE
SQLSTATE[42S22]

### ISSUE THREAD

**Issue by tigia** [cmgmyr/laravel-messenger#54]
this is my error
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'users.name' in 'field list' (SQL: select concat(users.name) as name from `users` inner join `participants` on `users`.`id` = `participants`.`user_id` where `participants`.`thread_id` = 1 and `users`.`id` != 1) (View: ********************/app/views/messenger/index.blade.php)

have you any idea?

**Comment by cmgmyr** [comment]
You'll have to specify the user's name columns if you aren't using `name`, which is just a default for Laravel. Please check out #44
