### ISSUE TITLE
[Request] Simple function to send message programmatically 

### ISSUE THREAD

**Issue by niknetniko** [cmgmyr/laravel-messenger#56]
(Perhaps there is a way to do this, but I haven't found one yet)

I think there should be a simple way to send a message to one or more users. This could be something like this:
```php
$user = User::find($id); //An new user from the database.
$admin = User::find(1); //An other user, used as admin here.

$subject = "New user";
$text = "A new user with ID $id was created.";

$message = new Message($subject, $text);
$message->addRecipient($admin);
$message->send();
```
I know the `Message` class is used already, so maybe we could go with something like `MessageSender` or similar.

However, the important part is this: I would really find it handy to not have to deal with Threads, Participants, etc. just to send a simple message to an user. It's also a lot of work: you need to read a lot of the source code to know which parameters are needed for each element, then you need to get the order you create them in right (or the database might throw errors with non-existing ID's), ...

It would be nice if the package dealt with this, instead of me having to do it every time.

**Comment by cmgmyr** [comment]
Thank you for the request. A V3 of this package is currently in the works now and will take care of a lot of this. At this point I don't have an ETA, but there are a bunch of Issues with the V3 tag if you want to keep track of where I am. I'll note your code in the planning ticket.

ref #51

**Comment by niknetniko** [comment]
OK, thank you a lot.
