### ISSUE TITLE
[Bug] PostgreSQL syntax error

### ISSUE THREAD

**Issue by niknetniko** [cmgmyr/laravel-messenger#57]
When using a PostgreSQL database, there are some migrations that fail. This affects the following migrations:
* add_nullable_to_last_read_in_participants_table.php
* alter_last_read_in_participants_table.php

For example, when the first one is run, following error is thrown in the console:
```
  [Illuminate\Database\QueryException]
  SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near "`"
  LINE 1: ALTER TABLE `participants` CHANGE COLUMN `last_read` `last_r...
                      ^ (SQL: ALTER TABLE `participants` CHANGE COLUMN `last_read` `last_read` timestamp NULL ON UPDATE CURRENT_TIMESTAMP DEFAULT CURRENT_TIMESTAMP;)

  [PDOException]
  SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near "`"
  LINE 1: ALTER TABLE `participants` CHANGE COLUMN `last_read` `last_r...
                      ^
```

I am using the latest stable version of both Laravel and this package. The PostgreSQL version I use is 9.4.4

**Comment by cmgmyr** [comment]
Thanks for reporting, I'll take a look

**Comment by mrgwilliam** [comment]
Same issue here, it would appear since this is a direct SQL statement instead of table() type migration, when it is run on PostgreSQL it will fail.

**Comment by RaoulDijksman** [comment]
Same issue here! The postgreSQL grammer is different from that to mySQL to alter a table.

**Comment by cmgmyr** [comment]
I'm going to have to re-work a few things to get this to work. Currently I'm relying on MySQL's `ON UPDATE CURRENT_TIMESTAMP` which is some of the problem. I'll have to set a timestamp through the code instead, then I can adjust the migrations from there

**Comment by vlakoff** [comment]
This might be due to the PostgreSQL gotcha mentioned on this [SO answer](http://stackoverflow.com/questions/18067614/how-can-i-set-the-default-value-of-a-timestamp-column-to-current-timestamp-on-u#20822267).

**Comment by sutonium** [comment]
this also happens in SQL Server 2008R2

**Comment by joshrainwater** [comment]
Any update on this one? Kind of kills the process if you're using anything other than MySQL

**Comment by KodeStar** [comment]
So a year later this is still a bug?  What is the purpose of these migrations? 
from the looks of it if you have an up to date version of 5.2 according to this PR https://github.com/laravel/framework/commit/15c487fecc00c1a58837ce5692396fec78a5bd9d this should work:

$table->timestamp('last_read')->useCurrent();
or
$table->nullableTimestamps('last_read')->useCurrent();

**Comment by KodeStar** [comment]
Ok, looking through the code I see the issue now, you want last_read to initially be null (as in not yet read), but do you need to update it on update as the markAsRead function sets the date anyway: $participant->last_read = new Carbon();

**Comment by leonardosapiras** [comment]
This bug also happens to me. Is there any chance to solve it?

**Comment by cmgmyr** [comment]
I apologize for the long delay in this bug. My hesitation was how the migrations were previously laid out and not wanting to alter them. Ideally, new migrations are to be made for any new changes, but when previous changes affect new installs, it's a problem. I've opted for fixing the original migration and removing two other migration files. I have a PR right now and just waiting for the tests to pass. Once completed, I'll merge this into `master` so that a few of you can test them out. Once we have a few 👍 then the changes will be tagged.

**Comment by cmgmyr** [comment]
The changes are now in `master`. @leonardosapiras can you try again with `dev-master` in your composer.json file?

**Comment by leonardosapiras** [comment]
@cmgmyr, with the update made in dev-master the migration worked with PostgreSQL.

Thanx and good work!

**Comment by cmgmyr** [comment]
now in `2.12`
