### ISSUE TITLE
Ajax page refresh ?

### ISSUE THREAD

**Issue by ssnukala** [cmgmyr/laravel-messenger#58]
Thanks for the package. I am new to Laravel, I followed all the instructions and enabled this chat, it works. 

But when i am in chat, i have to manually refresh my page to see the updated chat, is there a ajax refresh that I am not aware of or is that not a feature yet ?

**Comment by cmgmyr** [comment]
Thanks for using the package! Unfortunately this package will not handle anything to do with the front end of your app, that part will have to be up to you. I have a demo (work in progress) with Pusher [here](https://github.com/cmgmyr/laravel-messenger-pusher-demo) that you can check out to help out with this process. There are many other ways to accomplish this though. If you have any other questions, please feel free to ask
