### ISSUE TITLE
vendor:publish

### ISSUE THREAD

**Issue by uusa35** [cmgmyr/laravel-messenger#60]
after composer update

php artisan vendor:publish --provider="Cmgmyr\Messenger\MessengerServiceProvider"

it gives nothing to publish ?? 

any ideas please ? !

**Comment by cmgmyr** [comment]
what's the specific version of Laravel that you have installed?

**Comment by uusa35** [comment]
Laravel Ltd 5.1

**Comment by uusa35** [comment]
Lts*

**Comment by cmgmyr** [comment]
Ok thanks, do you know what the patch release is too? The full version will be in your `composer.lock` file (5.1.x). Also what OS are you running?

**Comment by uusa35** [comment]
vagrant@homestead:~/code/projects/ebook$ php artisan vendor:publish --provider="Cmgmyr\Messenger\MessengerServiceProvider" --force
Nothing to publish for tag [].

this messages always appears without any copying for migration files or messenger.php

Laravel Framework version 5.1.8 (LTS)

**Comment by cmgmyr** [comment]
Looks like you still need to add `Cmgmyr\Messenger\MessengerServiceProvider::class,` in your `config/app.php` file in the `providers` array. Once that is in there you can try the same `vendor:publish` command

**Comment by uusa35** [comment]
i thank you for your concern 
i have fixed your package manually and it's working perfect.
thank you for your effort and ur time.

**Comment by cheles** [comment]
@cmgmyr: this was closed but how it was solved: i have fixed your package manually and it's working perfect.

@uusa35  can you tell me what you've "fixed"?

Thanks guys

**Comment by cmgmyr** [comment]
Please look at my comment on [Aug 4](https://github.com/cmgmyr/laravel-messenger/issues/60#issuecomment-127764171), you'll need to add the service provider in your config before you run the vendor publish command

**Comment by cheles** [comment]
It's already in config/app.php. I followed all the steps

**Comment by cmgmyr** [comment]
I was just able to install https://github.com/intrip/laravel-authentication-acl and this package without seeing that issue. I was able to publish the assets successfully.

**Comment by vool** [comment]
Getting the same issue here.

Running v5.2.36

**Comment by vool** [comment]
if you are using caching

``php artisan cache:clear``

**Comment by andrew-za** [comment]
Had the same issue and running the full command `php artisan vendor:publish --provider="Cmgmyr\Messenger\MessengerServiceProvider" --tag="config"` did not want to work for me, so I read somewhere to simply run `php artisan vendor:publish` and it worked.

**Comment by chocolim** [comment]
Same here. 
It didnt work with --provider="Cmgmyr\Messenger\MessengerServiceProvider" --tag="config
But with just php artisan vendor:publish I did get the config and the migrations working

**Comment by a-komarev** [comment]
Have you completed [installation 3rd step](https://github.com/cmgmyr/laravel-messenger#installation-laravel-5x)?

> Add the service provider to config/app.php under providers:

```php
'providers' => [
    Cmgmyr\Messenger\MessengerServiceProvider::class,
]
```

**Comment by chocolim** [comment]
Yes i did 

Cristhian Benitez

On vie, abr. 14, 2017 at 9:15 AM Pe Ell

<
mailto:Pe Ell <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

Have you completed
https://github.com/cmgmyr/laravel-messenger#installation-laravel-5x
?

Add the service provider to config/app.php under providers:

'

providers

'

=>

[

Cmgmyr\Messenger\

MessengerServiceProvider

::

class

,

]

—

You are receiving this because you commented.

Reply to this email directly,
https://github.com/cmgmyr/laravel-messenger/issues/60#issuecomment-294151711
, or

**Comment by a-komarev** [comment]
and what will be if you'll add `--force` flag?
