### ISSUE TITLE
One to one messaging (private or direct thread)

### ISSUE THREAD

**Issue by paulocastellano** [cmgmyr/laravel-messenger#61]
Hi,

I trying make chat for my app and, you said i can use one-to-one message, i see should all the code but i don't found who i can make this.

I trying make chat one-to-one, like facebook chat. Without subject, only direct chat.

You can post a example?

Thanks!

**Comment by avlastenok** [comment]
All the backend is there the only thing that you really have to make is the front end.
If that is too much I'd suggest that you start some courses on laravel or php in general a Google search will give you something to get started.

**Comment by cmgmyr** [comment]
Please also check out closed issue #29 for some additional information
