### ISSUE TITLE
Issue with forUserWithNewMessages()

### ISSUE THREAD

**Issue by dtirer** [cmgmyr/laravel-messenger#62]
I'm having a bit of an issue with this method.  What i'm finding is this:

lets say you have a conversation between two people.

A sends message to B
B sends Message to A
A sends message to B
B sends Message to A
A sends message to B
B sends Message to A
....

This will create seven Participant records (one extra for the initial creation, which makes a Participant for each User involved).

However, I'm finding that even after reading a message and calling `markAsRead()` in those cases, this only effects the first participant record.  Because `markAsRead()` calls `getParticipantFromUser()`, which uses `firstOrFail()`.  So this means, if theres four Participant records for this Thread for User A, only the FIRST one is being updated by `markAsRead()`.

So then when I cal `scopeForUserWithNewMessages()`, it searches the Participants table for ANY records,where `participants.last_read` < then `threads.updated_at`, and uses that to determine if there's a new message.

I'm using the code per the examples provided in the Controllers.  In a one-to-one conversation after a bout 3 or 4 back-and-forths,  `scopeForUserWithNewMessages()` seems to return records even if the Users have read the Threads more recently.

**Comment by dtirer** [comment]
Actually, I just solved this.  The issue was in the `update()` query where it does `firstOrCreate()`.  My code had an extra attribute, and therefore, was never finding the `first`.  And then it just continued to create participant records with each message.

I thought it was a strange design choice :)

**Comment by cmgmyr** [comment]
glad everything worked out. just let me know if you have any issues/questions in the future. thanks for using the package!
