### ISSUE TITLE
Issue with different table name or columns name

### ISSUE THREAD

**Issue by LonnyX** [cmgmyr/laravel-messenger#64]
Hello,

I am including this package into my project but I have to modify a lot of things before it works... Because my users table is not in English and even my columns...

I think it will be a better way to place these data on the config file no?

**Comment by avlastenok** [comment]
You know what, the funny thing here is...
It is placed in a configure file. 
As it is with laravel packages you need to publish the config with artisan command.

**Comment by LonnyX** [comment]
All what I see on config it is the Users Model location. I'm talking about table name and column name that you hard-coded on the source (Thread.php etc...)

**Comment by avlastenok** [comment]
You can overwrite it that is also quite easy to see if you look at the source but take a look at #39 that should clear things up for you.

**Comment by LonnyX** [comment]
Yes I know, I edited and it works perfectly but I think it will be better to include it on the source for these who don't know. 

PW: I am using the example controller and I see that every message is visible for everyone not only for the participants... I think I have to use scopeForUser instead of getAllLatest method but not sure what to give on first paramter.

**Comment by avlastenok** [comment]
From the example file controller
$threads = Thread::forUser($currentUserId)->latest('updated_at')->get();
Where currentUserId is the logged in user

**Comment by LonnyX** [comment]
Cool it works :+1:
