### ISSUE TITLE
how to differentiate sender and receiver

### ISSUE THREAD

**Issue by lorvent** [cmgmyr/laravel-messenger#65]
Hi,

How can i differentiate who is the sender and receiver?

is there any direct way?

---

In my app i want to have two tabs inbox, sent

in inbox i want to show messages sent to current user

in sent i want to show messages sent by current user

just like email system.

---

thanks.

**Comment by marcelotk15** [comment]
I make like this im my atual work. https://gist.github.com/marcelotk15/2e4c5a34314907c72a9f

**Comment by lorvent** [comment]
Hi Marce

thanks for sharing your work.

but actually trying to implement something like inbox,sent etc so i am looking if there is any elegant way of doing it built in methods.
thanks.

**Comment by JacklynWyatt** [comment]
@lorvent Were you able to come up with a solution to this issue?  I am looking to do the same thing.

**Comment by azeos** [comment]
+1

**Comment by awh521** [comment]
@lorvent 
One to one messaging (private or direct thread)
 `$threads = Thread::forUser(Auth::id())->latest('updated_at')->with(['participants'=>function($query){
            $query->with('user')->where('user_id','<>',Auth::id());
        }])->paginate(15);`

**Comment by lorvent** [comment]
thanks for that,
but still its not able to figure out who originated discussion (like in mail...you get mails into inbox, mail you sent are into sent box)

for that, database schema has to be changed.

**Comment by tvzone** [comment]
this is  what i did


    /**
     * Returns threads that the user is associated with.
     *
     * @param $query
     * @param $userId
     *
     * @return mixed
     */
    public function scopeSentBy($query, $userId)
    {
        $messagesTable = Models::table('messages');
        $threadsTable = Models::table('threads');

        return $query
            ->where($messagesTable . '.user_id', "=", $userId)
            ->where($threadsTable . '.deleted_at', "=", null)
            ->join($messagesTable, $threadsTable.'.id', '=', $messagesTable.'.thread_id')
            ->select($threadsTable.'.*', $messagesTable.'.user_id');
    }

**Comment by tvzone** [comment]
i'm currently using this :)

    /**
     * Show all sent message threads from user.
     *
     * @return mixed
     */
    public function sent()
    {
        $currentUserId = Auth::user()->id;
        $threads = Thread::forUser($currentUserId)
        ->where('messages.user_id', $currentUserId)
        ->join('messages', 'threads.id', '=', 'messages.thread_id')
        ->latest('updated_at')->get();

        return view('messenger.index', compact('threads', 'currentUserId'));
    }

**Comment by lss007** [comment]
* Show all sent message threads from user.
 *
 * @return mixed
 */
public function sent()
{
    $currentUserId = Auth::user()->id;
    $threads = Thread::forUser($currentUserId)
    ->where('messages.user_id', $currentUserId)
    ->join('messages', 'threads.id', '=', 'messages.thread_id')
    ->latest('updated_at')->get();

    return view('messenger.index', compact('threads', 'currentUserId'));
}

**Comment by Gummibeer** [comment]
@tvzone you are duplicating some checks and overcomplicating the query: I think this will be faster:

```php
public function sent()
{
    $currentUserId = Auth::id();
    $threads = Thread::where('user_id', currentUserId)
    ->orderBy('updated_at')
    ->with('messages')
    ->get();

    return view('messenger.index', compact('threads', 'currentUserId'));
}
```

How I know `latest()` just picks the latest single entry - so not all threads - and `forUser()` and the `where()` are duplicated queries.
