### ISSUE TITLE
Thread search.

### ISSUE THREAD

**Issue by Tjoosten** [cmgmyr/laravel-messenger#66]
Hi, 

I was thinking. What if you implement a option to search the threads?

**Comment by marcelotk15** [comment]
If you want to search by name you can make a simple search system, no?

**Comment by Tjoosten** [comment]
Indeed a full text search based on the name.

**Comment by cmgmyr** [comment]
this would probably be helpful to a lot of users. I'll tag it for V3

**Comment by Pandahisham** [comment]
+1

**Comment by cmgmyr** [comment]
Reopening this since the search is not as complete as I'd like it to be. More to come on this soon

**Comment by Tjoosten** [comment]
@cmgmyr any update on this one?

**Comment by xitude** [comment]
Could you not use something like [Laravel Scout](https://laravel.com/docs/5.4/scout) for this?

**Comment by cmgmyr** [comment]
Yup, Scout would work really well for this. I don't think it should be a dependency for the package though, but a suggestion. Thoughts?

**Comment by ridislam** [comment]
Can you show us a process we can search threads?

**Comment by Gummibeer** [comment]
@ridislam 

search the treads by **user**:
1) search your user table
2) get all participants for the found users
3) get all threads by the participants
This could be done in one query I think and using distincts will help.

search the threads by **subject**:
this is already in the package if I see it right in #116 but if you want to do it yourself, it's a simple where-like query.

What you have to add on both queries would be any kind of filter to just display threads the current user has access to.

**Comment by zilveer** [comment]
Any updates on search?

**Comment by wrabit** [comment]
Was this closed because the feature was added?

**Comment by wrabit** [comment]
Ok, it was a sinch to add without any package api needed:

```
        $threads = Thread::forUser(auth()->user()->id);
        
        if (!empty($this->search)) {
            $threads->whereHas('messages', function(Builder $query) {
                $query->where('body', 'like', '%' . $this->search . '%');
            });
        }

        return view('livewire.messages', [
            'threads' => $threads->paginate(10)
        ]);
```

**Comment by ridislam** [comment]
> @ridislam
> 
> search the treads by **user**:
> 
> 1. search your user table
> 2. get all participants for the found users
> 3. get all threads by the participants
>    This could be done in one query I think and using distincts will help.
> 
> search the threads by **subject**:
> this is already in the package if I see it right in #116 but if you want to do it yourself, it's a simple where-like query.
> 
> What you have to add on both queries would be any kind of filter to just display threads the current user has access to.

thanks for your reply, it helped me a lot. Sorry for being little to reply to you back.
