### ISSUE TITLE
column name in users table different than default

### ISSUE THREAD

**Issue by UnrulyNatives** [cmgmyr/laravel-messenger#67]
Hi,

In my `users` table the column with name of the user is not `name` but `username`.
In consequence, running your package ends up with

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'users.name' in 'field list' (SQL: select concat(users.name) as name from `users` inner join `participants` on `users`.`id` = `participants`.`user_id` where `participants`.`thread_id` = 3 and `users`.`id` != 1) (View: /var/www/PROJECTNAME/resources/views/messenger/index.blade.php)

Is there any way of setting the name of this column in `config.php` file?

Peter

**Comment by avlastenok** [comment]
First step is to open the closed issues tab and see if your question has been answered and it has a number of times take a look at #39
