### ISSUE TITLE
Warning: Ambiguos class resolution

### ISSUE THREAD

**Issue by bustarice** [cmgmyr/laravel-messenger#68]
Hello,

I am getting Ambiguos class resolution during composer update. It is working but this error is happening all the time.

Here is what it says in detail:

```
Warning: Ambiguous class resolution, "CreateThreadsTable" was found in both "$baseDir . '/database/migrations/2014_10_28_175635_create_threads_table.php" and "C:\lamp\www\dnasys\vendor\cmgmyr\messenger\src\migrations\2014_10_28_175635_create_threads_table.php", the first will be used.
Warning: Ambiguous class resolution, "CreateMessagesTable" was found in both "$baseDir . '/database/migrations/2014_10_28_175710_create_messages_table.php" and "C:\lamp\www\dnasys\vendor\cmgmyr\messenger\src\migrations\2014_10_28_175710_create_messages_table.php", the first will be used.
Warning: Ambiguous class resolution, "CreateParticipantsTable" was found in both "$baseDir . '/database/migrations/2014_10_28_180224_create_participants_table.php" and "C:\lamp\www\dnasys\vendor\cmgmyr\messenger\src\migrations\2014_10_28_180224_create_participants_table.php", the first will be used.
Warning: Ambiguous class resolution, "AddSoftDeletesToParticipantsTable" was found in both "$baseDir . '/database/migrations/2014_11_03_154831_add_soft_deletes_to_participants_table.php" and "C:\lamp\www\dnasys\vendor\cmgmyr\messenger\src\migrations\2014_11_03_154831_add_soft_deletes_to_participants_table.php", the first will be used.
Warning: Ambiguous class resolution, "AddNullableToLastReadInParticipantsTable" was found in both "$baseDir . '/database/migrations/2014_11_10_083449_add_nullable_to_last_read_in_participants_table.php" and "C:\lamp\www\dnasys\vendor\cmgmyr\messenger\src\migrations\2014_11_10_083449_add_nullable_to_last_read_in_participants_table.php", the first will be used.
Warning: Ambiguous class resolution, "AlterLastReadInParticipantsTable" was found in both "$baseDir . '/database/migrations/2014_11_20_131739_alter_last_read_in_participants_table.php" and "C:\lamp\www\dnasys\vendor\cmgmyr\messenger\src\migrations\2014_11_20_131739_alter_last_read_in_participants_table.php", the first will be used.
Warning: Ambiguous class resolution, "AddSoftdeletesToThreadsTable" was found in both "$baseDir . '/database/migrations/2014_12_04_124531_add_softdeletes_to_threads_table.php" and "C:\lamp\www\dnasys\vendor\cmgmyr\messenger\src\migrations\2014_12_04_124531_add_softdeletes_to_threads_table.php", the first will be used.
```

Please advise how to fix this.

Thanks.

**Comment by semsphy** [comment]
+1

**Comment by nuukcillo** [comment]
I deleted the files in 'vendor\cmgmyr\messenger\src\migrations' folder as a temporary solution.

**Comment by bustarice** [comment]
@nuukcillo I guess I'll have to do that for now. Hopefully if it needs to update again it would have that issue fixed by then.

**Comment by cmgmyr** [comment]
Thanks for reporting this everyone. Please update the package and let me know if this shows up again, should be fixed now.

**Comment by csmind** [comment]
I have the same error now with the latest version after installing any packages using composer

`Warning: Ambiguous class resolution, "CreateThreadsTable" was found in both "$baseDir . '/database/migrations/2014_10_28_175635_create_threads_table.php" and "
C:\xampp2\htdocs\allwhispers\vendor/cmgmyr/messenger/src/migrations\2014_10_28_175635_create_threads_table.php", the first will be used.
Warning: Ambiguous class resolution, "CreateMessagesTable" was found in both "$baseDir . '/database/migrations/2014_10_28_175710_create_messages_table.php" and
 "C:\xampp2\htdocs\allwhispers\vendor/cmgmyr/messenger/src/migrations\2014_10_28_175710_create_messages_table.php", the first will be used.
Warning: Ambiguous class resolution, "CreateParticipantsTable" was found in both "$baseDir . '/database/migrations/2014_10_28_180224_create_participants_table.php" and "C:\xampp2\htdocs\allwhispers\vendor/cmgmyr/messenger/src/migrations\2014_10_28_180224_create_participants_table.php", the first will be used.
Warning: Ambiguous class resolution, "AddSoftDeletesToParticipantsTable" was found in both "$baseDir . '/database/migrations/2014_11_03_154831_add_soft_deletes_to_participants_table.php" and "C:\xampp2\htdocs\allwhispers\vendor/cmgmyr/messenger/src/migrations\2014_11_03_154831_add_soft_deletes_to_participants_table.php", the first will be used.
Warning: Ambiguous class resolution, "AddSoftdeletesToThreadsTable" was found in both "$baseDir . '/database/migrations/2014_12_04_124531_add_softdeletes_to_threads_table.php" and "C:\xampp2\htdocs\allwhispers\vendor/cmgmyr/messenger/src/migrations\2014_12_04_124531_add_softdeletes_to_threads_table.php", the first will be used.
`

**Comment by cmgmyr** [comment]
@csmind hmm, I'm not seeing this on my 5.3 install. Can you:

1. delete the messenger migrations from `database/migrations`
2. run: `composer dump-autoload -o`
3. re-publish the migrations: `php artisan vendor:publish --provider="Cmgmyr\Messenger\MessengerServiceProvider"`
4. run: `composer dump-autoload -o`

hopefully, you shouldn't see this error anymore.
