### ISSUE TITLE
how i can disable minimize and close icon...

### ISSUE THREAD

**Issue by YnievesDotNet** [cmgmyr/laravel-messenger#70]
I need hide both buttons, without css.

I'm can change the template of chat??

I'm can create an box similar at facebook chat for this messenguer?

Best regards, Ynieves.

**Comment by cmgmyr** [comment]
The template files included in the package are just for a simple example, you can copy these into your application's views directory and adjust them any way you need to. Using the templates as-is is not really recommended.
