### ISSUE TITLE
I like do...

### ISSUE THREAD

**Issue by YnievesDotNet** [cmgmyr/laravel-messenger#71]
my idea is that.

    public function thread($id)
    {
        try {
            $thread = Thread::findOrFail($id);
        } catch (ModelNotFoundException $e) {
            Session::flash('error_message', 'The thread with ID: ' . $id . ' was not found.');

            return redirect('messages');
        }
        $userId = Sentinel::check()->id;
        $messages = $thread->messages->take(-5);
        ini_set('max_execution_time', 300);
        $response = new \Symfony\Component\HttpFoundation\StreamedResponse(function() {
            echo 'data: ' . json_encode($messages) . "\n\n";
            $last_message = array(); //in this value I need store the last read message. how I cant ontain that?
            while (true) {
                if ($thread->isUnread($userId)) {
                    $messages = $thread->messages->take(-5); // Here I need read the messages newer that $last_message.
                    echo 'data: ' . json_encode($messages) . "\n\n";
                    ob_flush();
                    flush();
                }
                sleep(1);
                $thread->markAsRead($userId);
            }
        });
        $response->headers->set('Content-Type', 'text/event-stream');
        return $response;
    }
send via SSE the new messages in the thread, but say error 500. why?

In my view I have...

            <div ng-controller="chat as vm">
                <irontec-simple-chat
                    messages="vm.messages"
                    username="vm.username"
                    input-placeholder-text="Escriba su mensaje..."
                    submit-button-text="Enviar"
                    title="{!! $thread->subject !!}"
                    theme="material"
                    submit-function="vm.sendMessage"
                    visible="vm.visible">
                </irontec-simple-chat>
            </div>

and the script I have that:

<script>
angular.module('plantelApp').controller('chat', chat);
function chat() {
    var vm = this;
    vm.subject = 'test';
    vm.messages = [];
    vm.username = 'username1';
    vm.sendMessage = function(message, username) {
        if(message && message !== '' && username) {
            vm.messages.push({
                'username': username,
                'content': message
            });
        }
    };
    vm.visible = true;
    var es = new EventSource("<?php echo action('Api\MessagesController@thread', $id); ?>");
    es.addEventListener("data", function(e) {
        arr = JSON.parse(e.data);

        for (x in arr) {
            vm.messages.push({
                'username': arr[x].name,
                'content': arr[x].message,
            });
        }
    }, false);
};
</script>

Thanks.

Ynieves.

**Comment by YnievesDotNet** [comment]
the scripts is

angular.module('plantelApp').controller('chat', chat);
function chat() {
    var vm = this;
    vm.subject = 'test';
    vm.messages = [];
    vm.username = 'username1';
    vm.sendMessage = function(message, username) {
        if(message && message !== '' && username) {
            vm.messages.push({
                'username': username,
                'content': message
            });
        }
    };
    vm.visible = true;
    var es = new EventSource("<?php echo action('Api\MessagesController@thread', $id); ?>");
    es.addEventListener("data", function(e) {
        arr = JSON.parse(e.data);

        for (x in arr) {
            vm.messages.push({
                'username': arr[x].name,
                'content': arr[x].message,
            });
        }
    }, false);
};

Thanks Again.

**Comment by cmgmyr** [comment]
Sorry, I don't think this is the right place to ask these questions. Please take a look at the forums at https://laracasts.com/discuss
