### ISSUE TITLE
Nothing to publish for tag [].

### ISSUE THREAD

**Issue by cheles** [cmgmyr/laravel-messenger#72]
Hi, I wanted to include your package to my Laravel app but I get "Nothing to publish for tag []" when I run php artisan vendor:publish --provider="Cmgmyr\Messenger\MessengerServiceProvider" on my server

Tried also with --force but with the same result. 

Thank for your help

**Comment by cmgmyr** [comment]
Hi, please take a look at #60

**Comment by vool** [comment]
If you are using caching

php artisan cache:clear
