### ISSUE TITLE
Can't use in laravel 5.1.* project

### ISSUE THREAD

**Issue by selmonal** [cmgmyr/laravel-messenger#73]
Can't use in laravel 5.1.* project. Composer displays errors like below

[InvalidArgumentException]
  Could not find package cmgmyr/laravel-messenger at any version for your min
  imum-stability (stable). Check the package spelling or your minimum-stabili
  ty

Please upgrade version of laravel.

**Comment by cmgmyr** [comment]
I just tried a fresh install of Laravel 5.1, and ran `composer require cmgmyr/messenger` which installed 2.7.1 without any issue. Can you try again?

**Comment by selmonal** [comment]
Now it works. Thank you but I don't understand what was going on.

**Comment by cmgmyr** [comment]
I'm not sure, maybe something was going on with packagist and/or GitHub at the time that you were trying to install everything. I'm glad it's working for you now though
