### ISSUE TITLE
Hardcoded users table name

### ISSUE THREAD

**Issue by a-komarev** [cmgmyr/laravel-messenger#75]
One more small thing - if in application user's table is named like: `user` or `account` for example - it's hard to use this package without forking it and perform renaming of all occurrences of users table usage.

Here I see 2 solutions:
- have in configuration users table name and if it's not provided - use `users` as default;
- take table name from Users model, because it's already assigned in configuration, so it could easily return that value. It could be stored in Thread model on instance creation as attribute once and use when needed later.

```php
$userModel = config('messenger.user_model');
$userTable = (new $userModel)->getTable();
```

I'm not sure that current feature will be useful for a lot of developers, but it could be helpful tho.

**Comment by cmgmyr** [comment]
Thanks for reporting, good idea. I should have this shortly

**Comment by cmgmyr** [comment]
@a-komarev how do the changes in `dev-master` look to you? Would you be able to test this in your own app? I've tested it in a few local apps that I have.

**Comment by a-komarev** [comment]
It's working out of the box now! Thanks a lot for a quick fix.

**Comment by cmgmyr** [comment]
:+1: glad it worked out!

**Comment by cmgmyr** [comment]
tagged `1.8` & `2.8`
