### ISSUE TITLE
Running publish copies over the migration files will cause problem when doing a migrate:refresh --seed

### ISSUE THREAD

**Issue by gibtang** [cmgmyr/laravel-messenger#76]
As 'php artisan migrate:refresh' will recreate the entire database according to the timestamp, so the migration file such as 2014_10_28_175710_create_messages_table.php will be executed first and that will cause a foreign key conflict as it tries to create a foreign key to the user table which user creates at current time which is much later than 2014. 

To replicate. Create a user table at current time such as 9th Sept 2015. Then when you execute the command to copy the migration files such as 2014_10_28_175710_create_messages_table to the migrations folder and then run 'php artisan migrate:refresh'. You will get an error as php artisan migrate:refresh will try to create a foreign key to the user table which does not exist yet. Solution is to remove $table->foreign('thread_id')->references('id')->on('threads');
            $table->foreign('user_id')->references('id')->on('users')->onUpdate('cascade'); and then tell user to create a migration which will add this foreign key

**Comment by greenbicycle** [comment]
Can you just change the name of the migration file before you migrate?

**Comment by cmgmyr** [comment]
can you update your app to use `dev-master` to see if the recent commits have fixed this issue? I'm going to look into a few other issues before I tag the next version. Thanks!

**Comment by gibtang** [comment]
The easier fix is to to modify the migration file to remove the foreign key creation and then modify the readme to tell the uset to create a migration file and insert the foreign key. Anyway, if you can verify this issue exists. I can do the fix and the submit a pull request

**Comment by cmgmyr** [comment]
I've already removed the key creation from the initial migrations. I'll leave it up to the dev's desecration if they want to create the foreign keys in their app. I don't think it needs to be specified in the readme

**Comment by gibtang** [comment]
Cool, are the foreign keys necessary as there is no mention in the realm??

**Comment by cmgmyr** [comment]
No, I don't think they are really necessary in some instances. They are helpful because they constrain data more within the database, and also have some build in functionality to where if you delete a record in the database that can cascade down to delete other records in other tables. That said, it seems like more people have had problems with them than it's worth

**Comment by cmgmyr** [comment]
tagged `1.8` & `2.8`
