### ISSUE TITLE
Table names prefixes

### ISSUE THREAD

**Issue by a-komarev** [cmgmyr/laravel-messenger#78]
One more thing which I found very important for this package is has an ability to set table names prefixes. I'm not talking about global application's database table names prefixes. That's mostly ability to group tables which this package is used and prevent table names conflicts with other packages.

For example what I want to see in my database:
`messenger_threads`, `messenger_participants`, `messenger_messages`

Table names could stay unchanged and don't have prefixes by default to not break current deployed applications.

Raised this question because got one more task for future implementation where tables with such names are already exists: `threads` are used in Forums package and `messages` are used in Comments package.

**Comment by askaoru** [comment]
:+1:  on this

**Comment by selmonal** [comment]
And table name prefix should be configurable.

**Comment by cmgmyr** [comment]
Good idea, I like this :+1:

**Comment by radiart** [comment]
Inform when you add that feature! :+1:

**Comment by a-komarev** [comment]
I've made some sketches in one of my projects, but it's too raw. But I found an issue:

**Thead.php**

```php
public function scopeBetween($query, array $participants)
{
    $query->whereHas($this->getParticipantTable(), function ($query) use ($participants) {
        $query->whereIn('user_id', $participants)
            ->groupBy('thread_id')
            ->havingRaw('COUNT(thread_id)=' . count($participants));
    });
}
```

Are you sure `$this->getParticipantTable()` must be dynamic? Because if I named my table of participants as `messenger_participants` - I'm receiving:

```php
Call to undefined method Illuminate\Database\Query\Builder::messenger_participants()
```

So, hardcode fixed it:

```php
public function scopeBetween($query, array $participants)
{
    $query->whereHas('participants', function ($query) use ($participants) {
        $query->whereIn('user_id', $participants)
            ->groupBy('thread_id')
            ->havingRaw('COUNT(thread_id)=' . count($participants));
    });
}
```

**Comment by divdax** [comment]
+1
prefixed tables are much more organized! When you have a database with more than 50 tables it's a bit messy. :smiling_imp:

**Comment by cmgmyr** [comment]
This has been merged into the `master` branch. Huge thanks to @a-komarev for the PR again. I'm going to leave this in `master` for a bit so others can test out the new feature before I add it to the next minor version. Please post to this thread if you run across any issues

**Comment by a-komarev** [comment]
Take a not that there is no way to define global table prefix, but there is an option to define table name for each model:

In messenger config file you can add optional variables:

```php
'messages_table' => 'messenger_messages',
'participants_table' => 'messenger_participants',
'threads_table' => 'messenger_threads',
```

**Comment by schonhose** [comment]
Am I correct in assuming the package for laravel hasn't been updated yet? I tried the settings below but I get the following error:

> Base table or view not found: 1146 Table 'database.threads' doesn't exist

Seems like the new table names are not carried over yet, presumable due to the package not being updated.

**Comment by a-komarev** [comment]
@schonhose you should have use `dev-master` branch defined in composer.json to have unstable code downloaded.

```json
"cmgmyr/messenger": "dev-master",
```

**Comment by schonhose** [comment]
@a-komarev Will this work with 5.1? The fact it is unstable is not really an issue since I am still developing. However, I do need it to work under Laravel 5.1.

**Comment by a-komarev** [comment]
I believe this messenger working with 5.*

**Comment by divdax** [comment]
This changes are not updatable. I already installed this package via composer. An update has to be done manually. No migration files for existing tables.

**Comment by cmgmyr** [comment]
Correct, the changes would have to be done manually if you want the prefixed tables. Probably in `V3` I'll make the prefixed tables a default and provide migration/upgrade instructions. No ETA on that at the moment though unfortunately.

@a-komarev I'm going to call this complete at the moment and tag this shortly.

**Comment by cmgmyr** [comment]
tagged `2.10`

**Comment by dmarman** [comment]
Could somebody please put an example on how to use `scopeBetween()`? I am having a hard time to figure out what to put in the argument `$query`.

**Comment by Promixius** [comment]
the argument is $query
so
scopeBetween($query) {
  return $query->where('whatever', 'whatever')->take(1);
}

**Comment by dmarman** [comment]
I am sorry but I still don't understand. `scopeBetween()` is defined first with two arguments one. And second I don't know where this method should be applying to.
`$x->between($y, array(1 , 2)) ` I don't know what `$x` and `$y` should be.
If this has some kind of explanation somewhere jaut tell me and I would read it.

**Comment by froid24** [comment]
The complete migrations files are important and should be added sooner rather than later. If you have a simple installation, adding the deleted_at field manually might be an option. But if you are developing a multi-tenant application, that would involve a manual step every time you add a new tenant...
Why have the optional table names in the manual when they are not fully functional yet?

**Comment by a-komarev** [comment]
@froid24 custom table names are fully functional. I'm using them in many of my applications.

**Comment by froid24** [comment]
Strange then, I installed the package today, and the migration for adding soft deletes for the messages table did not use the custom table name, throwing an exception when migrating. I had to update it myself, following the example of the other two tables.

**Comment by cmgmyr** [comment]
@froid24 you're correct, that change hasn't been tagged yet. I will do this shortly, but in the mean time you can use the master branch
