### ISSUE TITLE
Getting latestMessage sender name 

### ISSUE THREAD

**Issue by tim-peterson** [cmgmyr/laravel-messenger#79]
I see that you can get the `user_id` of the `latestMessage` when looping through the `$threads`, but it would be great to get the `lastestMessage` `name` and possibly other things one would likely have in the User table, e.g., avatar url. 

Basically i'm advocating for the `lastestMessage` DB call to do a `JOIN` on the Users table.

**Comment by cmgmyr** [comment]
You should be able to do something like `$thread->latestMessage->user->name` or `$thread->latestMessage->user->avatar`. It will use some more DB queries because you are digging down with Eloquent. I'll look into making this a little easier in V3

**Comment by tim-peterson** [comment]
Hey thanks, I also opened an issue #81, that shows that there are already too many queries. I know its not Eloquent but I may just clean this up for myself by doing a classic raw query with a JOIN on my user and assets tables. I know Eloquent looks nice but when it results in greater than 10 queries (forget about 350), you know its time for some refactoring :)

**Comment by cmgmyr** [comment]
Yeah, definitely needs some refactoring :+1:

**Comment by zilveer** [comment]
How is the refactoring going, any updates?

**Comment by ronlinet** [comment]
@zilveer  I have posted an optimized version of Thread::getAllLatest method here => https://github.com/cmgmyr/laravel-messenger/discussions/372#discussion-3736938
