### ISSUE TITLE
Count of new messages

### ISSUE THREAD

**Issue by Turgori** [cmgmyr/laravel-messenger#80]
How can I get the count of new messages in thread?

**Comment by askaoru** [comment]
It's on the example file provided.here
https://github.com/cmgmyr/laravel-messenger/blob/master/src/Cmgmyr/Messenger/examples/views/messenger/unread-count.blade.php

````
Auth::user()->newMessagesCount();
````

**Comment by Turgori** [comment]
newMessagesCount() returns the number of threads with new messages

**Comment by Kenny11CZ** [comment]
bump, I would appreciate it, too

**Comment by a-komarev** [comment]
+1 for this feature

**Comment by cmgmyr** [comment]
This is now in `master`, please let me know if there are any bugs that come up. I'm going to make some adjustments as well as maybe change the API a bit. Once everything is set I'll tag and release it.

**Comment by trinhsong** [comment]
How can i get a slidedown of unread threads in navbar? Thank you!

**Comment by cmgmyr** [comment]
The implementation in your design will be up to you, but now you can use the `userUnreadMessages($user_id)` or `userUnreadMessagesCount($user_id)` methods on the `Thread` model

**Comment by a-komarev** [comment]
@cmgmyr see #120 please. I've found couple of bugs related to this feature and resolved them.

**Comment by cmgmyr** [comment]
These changes have been tagged `2.11` along with one small API change. Please see the release notes for more info. Going to close this for now. If anyone has any issues with the update, please submit a new ticket. Thank you, everyone, for your input and work on this!
