### ISSUE TITLE
Messenger makes huge number of database queries in view file

### ISSUE THREAD

**Issue by tim-peterson** [cmgmyr/laravel-messenger#81]
I've noticed in testing that creating multiple, say 10-20, messages results in hundreds of database queries using the example view, `index.blade.php`, most of them being repeat queries. This is happening in the `foreach` loop not surprisingly. I really don't think database calls should be happening in the view file (its not the MVC-way) so I'm wondering how the code base can be cleaned up. 

<img width="866" alt="screen shot 2015-10-01 at 8 59 49 pm" src="https://cloud.githubusercontent.com/assets/1173307/10237443/7b88f820-687f-11e5-9b04-c68de6e12d32.png">

**Comment by cmgmyr** [comment]
Thanks for reporting. The example files and the use of Eloquent as-is is just for simple example purposes. Devs should try to optimize the use depending on their app. I'll take a hard look at this for the next version though

**Comment by tim-peterson** [comment]
Yes I get that the example files are just examples. Just looking to help improve them. Thanks again for such as great library!

**Comment by cmgmyr** [comment]
I'm all up for making the code/examples better, so feel free to make a PR if you want :+1:

**Comment by tim-peterson** [comment]
Will do, do you mind if I add some straight up raw SQL queries to the threads model? I guess the challenge is not everyone needs more data about a thread's users besides a `user_id`. Probably at the minimum, most people will have a users table where they will want the user name to be associated with each message. 

I also found it limiting that on the get all `/messages` endpoint, the unread threads list the creator of the thread and not who sent the message itself. Like with Github issues, it would be good to know the thread creator but also know who wrote the latest message as that's often not the thread creator.

**Comment by tim-peterson** [comment]
Actually Eloquent solves this, see **eager loading**: http://laravel.com/docs/5.1/eloquent-relationships#eager-loading (edited)

**Comment by rbkkbr** [comment]
Maybe I got a solution!!! OPTIMIZE using a eager loading!!!, the same as tim-peterson was wrote!

**Comment by tim-peterson** [comment]
@rbkkbr That's awesome!! Would it be possible to share your solution?

**Comment by robbiepaul** [comment]
I managed to refactor the code to introduce eager loading and reduce the n+1 problem

I'll share a couple of the steps here and hopefully people will be able to replicate.

In my `User` model I added this relationship
```php
public function threads()
{
        return $this->belongsToMany(Thread::class, 'messages', 'user_id', 'thread_id')
            ->withTimestamps()
            ->withPivot(['body'])
            ->groupBy('thread_id')
            ->latest('updated_at');
}
```
Then in my `MessagesController` changed the `index` method to:
```php
public function index()
{
        $currentUserId = Auth::id();
        $user = User::find($currentUserId)->with('threads', 'threads.messages', 'threads.participants', 'threads.messages.user')->first();
        return view('messenger.index', compact('user', 'currentUserId'));
}
```
Then finally in the `Thread` model (I had to copy it across to my own app namespace). I had to make a few changes...
```php
public function getParticipantFromUser($userId)
{
        // we already have participants collection because of eager loading so we just need to filter it
        return $this->participants->filter(function($user) use ($userId) {
            return $user->id == $userId;
        })->first();
}
```
and
```php
public function creator()
{
        return $this->messages->last()->user;
}
```
and
```php
public function getLatestMessageAttribute()
{
        return $this->messages->first();
}
```
and
```php
public function isUnread($userId)
{
        try {
            $participant = $this->getParticipantFromUser($userId);
            if ($this->updated_at > $participant->last_read) {
                return true;
            }
        } catch (\Exception $e) { 
             //No longer need ModelNotFound exception as we're not performing another query
       
        }
        return false;
}
```

There may have been some others, but it got my number of queries down to 9 from 100+

**Comment by divdax** [comment]
@robbiepaul Thank you but one thing is wrong. This doesn't return the latest message:
```
public function getLatestMessageAttribute()
{
        return $this->messages->first();
}
```

**Comment by robbiepaul** [comment]
@divdax It works for me.

What's it returning for you?

Make sure your `messages` relationship in the `Thread` model is set up correctly:

```php
   public function messages()
    {
        return $this->hasMany(Config::get('messenger.message_model'), 'thread_id', 'id')->orderBy('created_at', 'desc');
    }
```

**Comment by divdax** [comment]
@robbiepaul Thank you now it works. My relation had no orderBy.

**Comment by robbiepaul** [comment]
No problem, I missed that change in my original reply. Glad it works now

**Comment by schonhose** [comment]
@robbiepaul Thanks for providing this. I really like it, except the fact I need to copy the Thread model. This makes it hard to update. Hopefully your suggestions will make it into the example files on the repository.

**Comment by divdax** [comment]
Yes please push this into the repo. I did a manually update but now an update with composer is impossible. :cry:

**Comment by schonhose** [comment]
In retrospect, we should probably move the models to our own app space since they are only provided as examples.

**Comment by Promixius** [comment]
@schonhose since when?
The example files are located in the example folder but beside nothing. 
Instead extend the package models in your own that way you can make changes without messing anything up on composer updates

**Comment by jenellej** [comment]
Quick question, has this been pushed to the examples already?

**Comment by yoan1005** [comment]
i use your solution, but with your modification when i want count unread threads  i have an error: 

> Unknown column 'messenger_participants.last_read' in 'where clause'  

i thinks is in messagable model : 
```
 public function threadsWithNewMessages()
    {
        return $this->threads()
            ->where(function ($q) {
                $q->whereNull(Models::table('participants') . '.last_read');
                $q->orWhere(Models::table('threads') . '.updated_at', '>', $this->getConnection()->raw($this->getConnection()->getTablePrefix() . Models::table('participants') . '.last_read'));
            })->get();
    }
```

How can i resolve this please ? You can help me ?

Sry for my english guys i'm french..

**Comment by Xationch** [comment]
@robbiepaul 

I think there is a little mistake in your code. The return of this function is wrong.

```
public function getParticipantFromUser($userId)
{
        return $this->participants->filter(function($user) use ($userId) {
            return $user->id == $userId;
        })->first();
}
```
You compare the thread_id and not the user_id.
You need change like this ```return $user->user_id == $userId;```

Otherwise thanks for your help

**Comment by robbiepaul** [comment]
@Xationch thanks, I've updated my original answer
