### ISSUE TITLE
Argument 1 passed to Illuminate\Auth\Guard::login() must implement interface Illuminate\Contracts\Auth\Authenticatable, null given

### ISSUE THREAD

**Issue by shep1990** [cmgmyr/laravel-messenger#82]
Hi there,

I am getting the following issue whenever I run the messenger application and since I am new to Laravel I am not 100% sure what is causing this problem. I have tried Googling the error but I am not getting a clear answer on this. 

Argument 1 passed to Illuminate\Auth\Guard::login() must implement interface Illuminate\Contracts\Auth\Authenticatable, null given

Could you help?

Thanks,

Rich

**Comment by cmgmyr** [comment]
Do you have `Authenticatable` on your `User` model? If you have your code up on GitHub I can take a closer look, but there could be a few things going on. Not sure if you can share or not.

**Comment by shep1990** [comment]
Hi there, 

Thank you very much for getting back to me! I do have Authenticatable in my User model, I have put my code on github, https://github.com/shep1990/messenger. This is just a clean instillation of LaraveL with Messenger installed, I wanted to see if it happened on a clean install. 

Thanks again. 

Richard.

**Comment by brianveltman** [comment]
Having the same issue.

**Comment by brianveltman** [comment]
Of course.. the example code of MessagesController.php is using a user with the ID of 1. If the user does not exist an error will be thrown.

I have updated my code to this:

MessagesController.php
```
public function __construct()
    {
       $user = Auth::user();
    }
```

**Comment by cmgmyr** [comment]
The constructor in the example controller should be removed in the real application, and a better authentication process should be put into place. The initial code is just for testing purposes. Once this is removed, you should be all set...

```php
/**
* Just for testing - the user should be logged in. In a real
* app, please use standard authentication practices
*/
public function __construct()
{
    $user = User::find(1);
    Auth::login($user);
}
```

**Comment by Fenn-CS** [comment]
I am having a similar problem, something like :: 
FatalErrorException in User.php line 10: Interface 
'Illuminate\Contracts\Auth\Authenticable' not found

**Comment by mrkhanakia** [comment]
<?php

namespace App;
use Eloquent;

use Zizaco\Entrust\Traits\EntrustUserTrait;
// use Illuminate\Foundation\Auth\User as Authenticatable;

use Illuminate\Contracts\Auth\Authenticatable;
use Illuminate\Auth\Authenticatable as AuthenticableTrait;

class User extends Eloquent implements Authenticatable

{
     use EntrustUserTrait; // add this trait to your user model
     use AuthenticableTrait;
 
}

**Comment by ranjan-chaurasia05** [comment]
still not working

**Comment by a-komarev** [comment]
In previous versions of Laravel, you could access session variables or the authenticated user in your controller's constructor. This was never intended to be an explicit feature of the framework. In Laravel 5.3, you can't access the session or authenticated user in your controller's constructor because the middleware has not run yet.

As an alternative, you may define a Closure based middleware directly in your controller's constructor. Before using this feature, make sure that your application is running Laravel 5.3.4 or above:

```php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\Controller;

class ProjectController extends Controller
{
    /**
     * All of the current user's projects.
     */
    protected $projects;

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware(function ($request, $next) {
            $this->projects = Auth::user()->projects;

            return $next($request);
        });
    }
}
```

**Comment by digu087** [comment]
Do not change anything inside User.php (Model file), keep it as default, as it is at the time of installation of new laravel file

**Comment by supershazwi** [comment]
I got this error when trying to use socialite. I checked both my 'social_providers' table and 'users' table and realise that the row in 'social_providers' table was referencing the wrong user_id. So I just changed the ids to match and I stopped getting this error. 

Not sure whether this will help anyone.

**Comment by prkspkrl** [comment]
i have same problem what can i do ??

**Comment by ashish135** [comment]
you need to return $user after the create() method.

**Comment by CrhistianDLM** [comment]
Probaste cambiando Auth::login($user->id)  a Auth::login($user)

**Comment by nickforbizz** [comment]
my issue ...

Argument 1 passed to Illuminate\Auth\SessionGuard::login() must be an instance of Illuminate\Contracts\Auth\Authenticatable, null given, called in C:\xampp\htdocs\writersBay\app\Http\Controllers\Admin\Auth\RegisterController.php

**Comment by nkmswot** [comment]
@nickforbizz  i too having the same issue.. I'm on the middle of 5.1 to 5.2 now... what can i do now?

**Comment by nickforbizz** [comment]
I think in the user model, you should extend authenticatable instead of
model and also import it...

**Comment by DengSihan** [comment]
Laravel 6.2
I got the same issue. Different from the above.
My User model is
```php
namespace App\Models;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\SoftDeletes;
abstract class User extends Authenticatable
{
    use Notifiable,SoftDeletes;
    ...
}
```
And I am building a SPA by vue and Laravel, I use `api` as my guards instead of `web`
in `config/auth.php`
```php
'guards' => [
    // 'web' => [
    //     'driver' => 'session',
    //     'provider' => 'users',
    // ],
    'api' => [
        'driver' => 'token',
         // 'provider' => 'users',
        'provider' => getSubdomain(),
        'hash' => false,
    ],
],
...
'providers' => [
     // 'users' => [
     //     'driver' => 'eloquent',
     //     'model' => App\Models\User::class,
     // ],
    // 'users' => [
    //     'driver' => 'database',
    //     'table' => 'users',
    // ],
    'worker' => [
        'driver' => 'eloquent',
        'model' => App\Models\Worker::class
    ],
],
```
then I add 
```php
    'index' => [
        'driver' => 'eloquent',
        'model' => null
    ],
```
to `providers` in `config/auth.php`
I fixed it.
So, you need to provide a `provide` for each part even if it is empty.
Help it can helps you

**Comment by maseranw** [comment]
> I got this error when trying to use socialite. I checked both my 'social_providers' table and 'users' table and realise that the row in 'social_providers' table was referencing the wrong user_id. So I just changed the ids to match and I stopped getting this error.
> 
> Not sure whether this will help anyone.

Thanks,

**Comment by Judgement1995** [comment]
gfffh
