### ISSUE TITLE
5.1.19 requires changes to $_ENV

### ISSUE THREAD

**Issue by damienwebdev** [cmgmyr/laravel-messenger#83]
Line 54 of Trait/Messagable.php requires 

    if (env('APP_EMV', 'local') == 'testing' || !str_contains(\Illuminate\Foundation\Application::VERSION, '5.0')) 
      {
        $participants = $participants->all();
      }

**Comment by damienwebdev** [comment]
I made the above fix to resolve an issue in 5.1.19 where $_ENV was unable to access the 'APP_ENV' from the .env file.

**Comment by cmgmyr** [comment]
Thanks for reporting, I've fixed this in `2.8.1`, just run a composer update on the package and you should be all set.
