### ISSUE TITLE
Remove Foreign Keys Error

### ISSUE THREAD

**Issue by mmeindl** [cmgmyr/laravel-messenger#84]
Hey, I have Laravel 5.0 and the latest version of your messenger. To install your messenger i did everything step by step as you said but when I do "php artisan migrate" I get that error:

[Illuminate\Database\QueryException]
SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'messages_thread_id_foreign'; check that column/key exists (SQL: alter table `messages` drop foreign key messages_thread_id_foreign)

Can you tell me how to fix that?

**Comment by cmgmyr** [comment]
Since this is a new install, you could probably just remove the `2015_09_25_133458_remove_foreign_keys.php` file from your migrations directory, then try again.

**Comment by mmeindl** [comment]
Thank you for the fast answer! That problem is solved, but when i do now "php artisan migrate:refresh" i get the following error:

[Symfony\Component\Debug\Exception\FatalErrorException]
  Class 'AddSoftdeletesToThreadsTable' not found

Maybe you can help me with that one again?

**Comment by cmgmyr** [comment]
hmm, maybe a `composer dumpautoload` would work? That file should still be in your migrations directory

**Comment by mmeindl** [comment]
yeah that was it. Thank you very much!

**Comment by impleri** [comment]
This should be addressed differently. Perhaps a check on the table to see if the key exists? Otherwise, people will have to delete the migration every time the run `vendor:publish`.

**Comment by kishorkmishra** [comment]
Now i got error.... Argument 1 passed to Illuminate\Auth\Guard::login() must implement interface Illuminate\Contracts\Auth\Authenticatable, null given

**Comment by BKD-Digital** [comment]
Any luck with this Kish?

**Comment by cmgmyr** [comment]
FYI, the migration to remove foreign keys have been moved to the example dir in the latest versions

**Comment by MarwenBenTalebAli** [comment]
Hello,
im getting the same problem and i don't know where is the migrations directory?

**Comment by a-komarev** [comment]
@MarwenBenTalebAli `./database/migrations`
