### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by smnjuguna** [cmgmyr/laravel-messenger#88]
![error](https://cloud.githubusercontent.com/assets/4638578/10557204/3e6b3218-74ab-11e5-9648-be55a65a999f.png)
Hi am using the examples at the git repository, but am getting the error above.

**Comment by askaoru** [comment]
Hello there, 
Have you added the messageable trait to your user model?

``` php
use Cmgmyr\Messenger\Traits\Messagable;

class User extends Model {
    use Messagable;
}
````
like so?

**Comment by cmgmyr** [comment]
@smnjuguna have you done this? ^^

**Comment by smnjuguna** [comment]
Hello Chris, I have added the code in the user controller and it works.
Thanks so much.

**Comment by smnjuguna** [comment]
Hi cmgmyr/laravel-messe,

Simon Njuguna wants to connect with you on LinkedIn.
Join now to view their profile and start your own.

Confirm that you know Simon: https://www.linkedin.com/e/v2?e=0-iolsb39s-z4&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=Hf8oIZWS&invitationId=6140943511027007488








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-iolsb39s-z4&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQH462bdWQdqZwAAAVTkDvfG3OoSVgHRSSMcpeBRNKkXT4J6HEAkGGSi7b4vxfpNCmYCsje6TU2o7kanI2NV4MOGshQR69fhczlQbvgbw-qhUKwTde03Y8m6toJqiROLsOXb5oSSNBvB1dZcIts_GSsawJz7owP1hJHd-Jlk9OblqDFHB9J3uE3Drg607Nv1j6uK&eid=0-iolsb39s-z4


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-iolsb39s-z4&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by smnjuguna** [comment]
Simon Njuguna would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=Hf8oIZWS&invitationId=6140943511027007488&trk=eml-first_guest_reminder_01-hero-14-accept_text&trkEmail=eml-first_guest_reminder_01-hero-14-accept_text-null-8t293k%7Eiovf6x5j%7E74

View Simon Njuguna&#39;s profile: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=Hf8oIZWS&invitationId=6140943511027007488&trk=eml-first_guest_reminder_01-hero-3-profile_text&trkEmail=eml-first_guest_reminder_01-hero-3-profile_text-null-8t293k%7Eiovf6x5j%7E74





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=8t293k-iovf6x5j-74&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=16&m=unsub&ts=HTML&eid=8t293k-iovf6x5j-74&loid=AQF2IIc7wr4d3AAAAVUHXiU7ytgVKTup4psD1P7GobajDBFKrKHcT3BpI4duOFuthSrpa3UKD_gegKP4d_5Ft_TrzsvjUXw5Yhn6j_60mRNAFEfrvpdJtSD8yTwcmEkjqk7eeMevdmJre7ZcwwAcVqK4Ip3avOpVx-mSiZUE_kqgBxhYM4uJ6uPHS-U9QIw-Zm5j

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=8t293k-iovf6x5j-74&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.
