### ISSUE TITLE
database tables seems not Eloquent friendly

### ISSUE THREAD

**Issue by woodytang** [cmgmyr/laravel-messenger#90]
when I was trying to execute "$user->messages()->delete();", it thrown something like this :

Integrity constraint violation: 1052 Column 'updated_at' in field list is ambiguous ....

and I have to delete them manually:
```
        $threads_to_be_deleted = DB::table('participants')->where('user_id',$this->id)->lists('thread_id');

        DB::table('threads')->where('id',$threads_to_be_deleted)->delete();
        DB::table('participants')->where('user_id',$this->id)->delete();
```

**Comment by cmgmyr** [comment]
thanks for reporting, let me look into this a little more

**Comment by cmgmyr** [comment]
I was able to run the command: `$user->messages()->delete();` in my test app without a problem. What version are you on?

It looks like I need to add a `participants` relationship to the users trait so we can also call: `$user->participants->delete()`. So if you were to delete a user from the system, it would look like:

```php
$user = App\User::find(1);
$user->messages()->delete();
$user->participants()->delete();
$user->delete();
```

I'll take a better look at this process in `V3` to make deleting a user and removing them from threads easier.
