### ISSUE TITLE
 Migration problem : Syntax error or access violation:

### ISSUE THREAD

**Issue by texnika01** [cmgmyr/laravel-messenger#91]
Problem in php artisan migrate(Laravel 5.1):
[Illuminate\Database\QueryException]
  SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'messages_thread_id_foreign'; c
  heck that column/key exists (SQL: alter table `messages` drop foreign key messages_thread_id_forei
  gn)
  [PDOException]
  SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'messages_thread_id_foreign'; c
  heck that column/key exists

**Comment by askaoru** [comment]
you may refer to issue #84

**Comment by texnika01** [comment]
Thank you
