### ISSUE TITLE
Extending Thread and Messages Model?

### ISSUE THREAD

**Issue by tusharvikky** [cmgmyr/laravel-messenger#92]
How can I extend app/Messages.php Model by package Message Model. I want to add certain relationships with messages and threads?

**Comment by cmgmyr** [comment]
you can extend the model classes like any other class. you could do something similar to this:

```php
<?php

use Cmgmyr\Messenger\Models\Thread as MessengerThread;

class MyThread extends MessengerThread
{
    // ...
}

```

**Comment by tusharvikky** [comment]
My Users Meta is stored in another table. How can I have $thread->meta();
