### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by RudolfFussek** [cmgmyr/laravel-messenger#93]
Hey! I have install the package but I have a error:

Call to undefined method Illuminate\Database\Query\Builder::newMessagesCount() (View: /var/www/html/resources/views/messenger/unread-count.blade.php) (View: /var/www/html/resources/views/messenger/unread-count.blade.php) (View: /var/www/html/resources/views/messenger/unread-count.blade.php)

The unread-count.blade.php file:
<?php $count = Auth::user()->newMessagesCount(); ?>
@if($count > 0)
<span class="label label-danger">{!! $count !!}</span>
@endif

Thanks for help!

**Comment by cmgmyr** [comment]
Your user might not be logged in before that was called. Make sure you are checking if they are logged in first. I'll make that change to the example view file. Please let me know if you need anything else.

**Comment by raghavendra89** [comment]
Hi,

Even I'm getting the same error:

BadMethodCallException in Builder.php line 2073:
Call to undefined method Illuminate\Database\Query\Builder::newMessagesCount()

I did check if the user is logged in using Auth::check(). 

        if (Auth::check()) {
	    $count = Auth::user()->newMessagesCount(); 
	}

But still getting the same error.

Thanks!!!

**Comment by raghavendra89** [comment]
This is my user model: 

      namespace App;

      use Illuminate\Auth\Authenticatable;
      use Illuminate\Database\Eloquent\Model;
      use Illuminate\Auth\Passwords\CanResetPassword;
      use Illuminate\Foundation\Auth\Access\Authorizable;
      use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
      use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
      use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;

      use Cmgmyr\Messenger\Traits\Messagable;

**Comment by raghavendra89** [comment]
ok, solved it. made the simple error: forgot to include this line in the User model. 

       use Messagable;

**Comment by muralidharan143** [comment]
<?php $count = Auth::user()->newThreadsCount(); ?>
@if($count > 0)
<span class="label label-danger">{!! $count !!}</span>
@endif

Note: Insted of calling newMessageCounte(), use newThreadCount()

**Comment by chinnalamahesh** [comment]
<?php $count = Auth::user()->newThreadsCount(); ?>
@if($count > 0)
{!! $count !!}
@endif

Note: Insted of calling newMessageCount(), use newThreadCount()
Here, **newThreadsCount** is the method called in both the package and controller.
you are supposed to call same method name of what declared inside the package and controller.
