### ISSUE TITLE
Login to user id 1

### ISSUE THREAD

**Issue by RudolfFussek** [cmgmyr/laravel-messenger#95]
Hey! I have install this package but I have a error...

When I go to site.com/message white my user (id=1) than its function perfect.

When I logged into userid 2 and go to site.com/message I logget automatically into the userid 1? Why?... I have test it whit another Browser, the same... I logged into userid_2 go to site.com/message and I'm logging white userid_1...

Can anyone help me?

**Comment by RudolfFussek** [comment]
Also, when I logged out and I go to site.com/messages, I'm logged in white user_id 1...

Big mistake and unsure :-1:

**Comment by cmgmyr** [comment]
Hi,
You're going to have to remove these [two lines](https://github.com/cmgmyr/laravel-messenger/blob/master/src/Cmgmyr/Messenger/examples/MessagesController.php#L21) from your application since they are only for testing/demo purposes. Please let me know if you need anything else.

**Comment by RudolfFussek** [comment]
Thanks for your help!
