### ISSUE TITLE
Order by id

### ISSUE THREAD

**Issue by RudolfFussek** [cmgmyr/laravel-messenger#96]
Hey!

My question, can I messages order by ID?

**Comment by cmgmyr** [comment]
You are able to call the `Thread` model any way you'd like. So something like this would work:

```php
$threads = Thread::orderBy('id', 'DESC')->get();
```

**Comment by RudolfFussek** [comment]
Hey! I mean the the messages in the threads...

**Comment by Gummibeer** [comment]
Same answer like @cmgmyr, yes you can:

```
$thread->messages()->orderBy('id', 'desc')->get()
```

**Comment by RudolfFussek** [comment]
Thanks @Gummibeer I can't find

$messages = $thread->messages()->get()

that I can edit it?...
