### ISSUE TITLE
Group messaging

### ISSUE THREAD

**Issue by mhluzi** [cmgmyr/laravel-messenger#99]
Hi there

This is not really an issue as such - more of a question.

Thanks for the package - still learning how things connect together but one aspect I am trying to get my head around is if the group messaging functionality can be used to contact the same group in different threads.

I have an application where people can belong to projects. All project members should then be able to chat on various aspects of that project. Each aspect would effectively be a thread. 

Would that be possible using this package? Perhaps if I joined the participants with the project members table?

Apologies if this is not the correct forum for such a question.

M.

**Comment by mydnic** [comment]
When you create a project, you can create a new thread at the same time, and add the project's users in the thread's participants, that would be the simpliest thing to do.

**Comment by cmgmyr** [comment]
Yes, I agree with what @mydnic stated. That would be a good workflow to implement. 

Thanks for using the package!

**Comment by mhluzi** [comment]
Thanks - appreciated!

**Comment by mhluzi** [comment]
Is it possible/logical to create a thread without an initial message?

**Comment by cmgmyr** [comment]
yes, you can have a thread without an initial message. You could check if no messages are available, then display something like: `Welcome to the X project! Kick off the discussion and add a welcome message to the rest of the team`. Alternatively you can have that message attached to a "system" user too. Just depends on how you'd like to handle it.
